### ISSUE TITLE
should indicate if postgres is not running

### ISSUE THREAD

**Issue by mrbrdo** [PostgresApp/PostgresApp#118]
If postgres crashes or exits, PostgresApp still says it's "running on port 5432", even though it's not. There are probably a couple of options:
- just exit postgresapp
- display different icon
- change text in menu to indicate it's down

Refer to issue https://github.com/PostgresApp/PostgresApp/issues/41#issuecomment-9168576

**Comment by jakob** [comment]
Postgres.app 2.0 now checks if the server is running every time you open the status menu.
