### ISSUE TITLE
New User Experience

### ISSUE THREAD

**Issue by schneems** [PostgresApp/PostgresApp#119]
Howdy i'm in the process of setting up a new machine and since our docs recommend Postgres.app i'm using it. Thought I would share some of the experience in the hopes of improving in the future. 
## Not Identified

App downloaded but App is not "identified", makes me change a preference (see image) If this is for beginners and senior devs, would be nice to figure out how to get this app signed if possible, so it "just works"(™)
http://cl.ly/image/181k471V1p3S
## Auto Open

Default is for it to not auto open on login. Difficult to debug if your rails app starts getting a vague connection warning
http://cl.ly/image/181k471V1p3S
## Adding Binaries to Path

From the docs:

PostgreSQL ships with a constellation of useful binaries, like pg_dump or pg_restore, that you will likely want to use. Go ahead and add the /bin directory that ships with Postgres.app to yourPATH (preferably in .profile, .bashrc, .zshrc, or the like to make sure this gets set for every Terminal session):

Adding a "enable command line tools" button that puts makes a symlink from /usr/local/bin or something would be great. GITX does this well. Bonus points for telling the user to do this after install and for telling them how to verify it worked too. 

On a side note I completely missed this step when i tried out Postgres.app last time and as a result is was basically non-functional for me (though I didn't know why).
## Thanks

Love postgres.app thank everyone for your involvement :heart:

**Comment by jakob** [comment]
1. Postgres.app is now signed correctly (as long as you don't try opening it outside of /Applications, unfortunately -- but we've discossed this at length, and there is no easy way to fix it)
2. Postgres.app now autostarts by default (which can be turned off)
3. The home page now prominently tells you to configure command line tools.

I think this should fix most of the problems, and we can now finally close this issue :)
