### ISSUE TITLE
psql suddenly prompting for password

### ISSUE THREAD

**Issue by meat-and-breath** [PostgresApp/PostgresApp#125]
So, everything worked fine for a couple of days, but now suddenly psql has started to prompt for a password:

$ ~/Applications/Postgres.app/Contents/MacOS/bin/psql -d postgres -f refresh-db.sql 
Password: 
psql: FATAL:  password authentication failed for user "tgoodsell"

It seems like maybe the pg_hba.conf file isn't getting read, but I can't confirm that since I can't find the logs. (See other tickets someone else opened a while back.)

Suggestions on how I can figure out what's happening?

**Comment by es6Test** [comment]
no luck for me either, I did install the official download fro postgresql's site before this app, maybe that messed it up.
