### ISSUE TITLE
FATAL:  database "dave" does not exist

### ISSUE THREAD

**Issue by bingomanatee** [PostgresApp/PostgresApp#139]
using the "psql" menu item (OSX 10.8.4) I get

Last login: Sat Oct 19 07:59:28 on ttys009
/Applications/Postgres.app/Contents/MacOS/bin/psql ; exit;
Daves-MacBook-Pro:~ dave$ /Applications/Postgres.app/Contents/MacOS/bin/psql ; exit;
psql: FATAL:  database "dave" does not exist
logout

[Process completed]

**Comment by raychenon** [comment]
I first tried with Homebrew then I ran into this error. Then uninstalled postgres by brew
I installed PostgresApp, this error showed up again.
How can you check if you have previous Postgres installed on the mac ?
I use 
>which psql
but it will show me  /Applications/Postgres.app/Contents/Versions/9.4/bin/psql

**Comment by kenju254** [comment]
is there a solution to this yet ? I am getting the same error

**Comment by yangman-c** [comment]
just do like this:
step 1: createdb
step 2: psql -h localhost or psql

hope useful to you.

**Comment by kultgenj** [comment]
When I type createdb USERNAME i get the response command not found, could you assist me?

**Comment by jakob** [comment]
1. First, make sure you remove older intallations of PostgreSQL before starting Postgres.app. To do so, follow the instructions here: http://postgresapp.com/documentation/remove.html
2. Restart your Mac after uninstalling other PostgreSQL installations, and open Activity Monitor to make sure there are no processes named "postgres" running.
3. Now open Postgres.app. If it still doesn't work, try using the `created USERNAME` command in Terminal.
4. Make sure you set up your $PATH correctly: http://postgresapp.com/documentation/cli-tools.html

**Comment by jakob** [comment]
The new version of Postgres.app now checks if the port is in use before attempting to init a server and create a database. This makes it much less likely to fail. Additionally, Postgres.app displays more reasonable error messages when a problem occurs.

And finally, the troubleshooting section in the docs now explains how to fix this problem.

**Comment by AgoniNemo** [comment]
```
createdb -h localhost -p 5432 -U <USERNAME> testDB

psql testDB
```

**Comment by sarkarchandan** [comment]
For me as well, "database doesn't exist" error was showing up. While trouble shooting I figured that I accidentally dropped the database with my name that Postgresapp creates while initialising.

I simply created one database with my name and things were fine. Thus, I assume that every time I launch the Postgresapp it checks connection for the database with my name. Please correct me if I am wrong.

Thanks in advance.

**Comment by Monroe100** [comment]
> Could you try connecting to the "postgres" database:
> `psql -d postgres`
> and then execute the following command:
> `show data_directory;`
> On 9.3.1.0-alpha1 that should return `/Users/USERNAME/Library/Application Support/Postgres93/var`
> Then check which databases exist on the server using the shorthand `\l`
> 
> If all that works, it seems that Postgresapp called initdb successfully, but createdb failed. You can do that manually, just execute `createdb USERNAME` from the terminal (not inside psql)
