### ISSUE TITLE
Support for iTerm

### ISSUE THREAD

**Issue by brandondrew** [PostgresApp/PostgresApp#168]
It would be very nice if PostgresApp supported iTerm.  If you don't want to have a Preference pane, you could just check for iTerm and use it if it's available.

**Comment by hicksca** [comment]
+1

**Comment by shenzhun** [comment]
+1

**Comment by MattOates** [comment]
also iTerm2 is there a reason why you can't just launch the default terminal app?

**Comment by davedub** [comment]
+ 1

**Comment by sdlovecraft** [comment]
+1

**Comment by hicksca** [comment]
@MattOates we are to lazy to alias '/Applications/Postgres.app/Contents/Versions/9.4/bin'/psql -p5432
psql (9.4.4) ;)

**Comment by jakob** [comment]
If you set up your PATH (http://postgresapp.com/documentation/cli-tools.html) you can just type `psql`

**Comment by luckydonald** [comment]
@jakob https://github.com/PostgresApp/PostgresApp/issues/168#issuecomment-33304487
The offered AppleScript:
![Terminal.app applescript commands](https://cloud.githubusercontent.com/assets/2737108/12010995/162dcbf4-acbd-11e5-9dec-df13ce8c0e07.png)
![iTerm.app applescript commands](https://cloud.githubusercontent.com/assets/2737108/12010996/1f117e64-acbd-11e5-8a37-51d46dfc3d51.png)

**Comment by bithavoc** [comment]
@jakob I have the iTerm integration working. I noticed the header for Terminal.app is being generated on build and I wonder if I should the include the generated `iTerm.h` directly in the `xcodeproj` instead creating another build step to generate `iTerm.h`.

**Comment by jakob** [comment]
@bithavoc awesome!

Please just include the iTerm.h header, otherwise we can build Postgres.app only with iTerm installed -- something I'd like to avoid.

**Comment by jakob** [comment]
Postgres.app 2.0 now has a preference to open databases in iTerm 2 instead of Terminal.

**Comment by nlpjoe** [comment]
when I open database in iTerm2, there is a error that "The operation couldn’t be completed. (com.postgresapp.Postgres2.ClientLauncher error 0.)"

**Comment by chrispysoft** [comment]
You have to make sure that iTerm is located inside your Applications folder. Since Postgres.app opens iTerm via Apple Script, you can check its availability using the following script:
```
tell application "iTerm"
	activate
end tell
```

This command should open iTerm, otherwise you'll be asked for its location. Hope this helps!
