### ISSUE TITLE
gem install pg ... fails 

### ISSUE THREAD

**Issue by HerbertKoelman** [PostgresApp/PostgresApp#187]

**Comment by jmca** [comment]
@HerbertKoelman Thanks for the solution, worked perfect for me.

**Comment by Zoso7728** [comment]
I spent the past two days all over the web trying to solve this same issue but this solved it instantly. Many thanks!

**Comment by chemibarowgma** [comment]
It didn't work for me and finally I tried this on OS X and it worked! :)
<code>
brew install postgresql
</code>

**Comment by nikhammerellis** [comment]
@jakob YUS I have been looking this stuff up for HOURS!

**Comment by YonasBerhe** [comment]
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.3/bin

Postgres.app is missing from my application folder. @jakob I having the same error as the person who started the thread.

**Comment by jakob** [comment]
@YonasBerhe This thread only deals with Postgres.app. If you don't use Postgres.app, I can't help you.

Please also note that the path for the current version is 
`export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.4/bin` (note the major version number in the path, ie. 9.4 instead of 9.3)

**Comment by adityanagla1996** [comment]
Can anyone say me how it works in windows? i tried gem install pg , gem install pg --with-pg-config="path to pg_config.exe" & also ARCHFLAGS="-arch x86_64" gem install pg . but still it doesnt works. @jakob

**Comment by jakob** [comment]
@adityanagla1996 I'm sorry, I can't help with installation on Windows.

**Comment by tharrington** [comment]
I am having this same issue when trying to install with $ bundle install

additional messaging:

```
checking for pg_config... yes
Using config values from /usr/local/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib
	--with-pqlib
	--without-pqlib
	--with-libpqlib
	--without-libpqlib
	--with-ms/libpqlib
	--without-ms/libpqlib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/tyler/Desktop/pepper/pepperapi/vendor/bundle/ruby/2.3.0/extensions/universal-darwin-17/2.3.0/pg-1.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/tylerharrington/Desktop/pepper/pepperapi/vendor/bundle/ruby/2.3.0/gems/pg-1.0.0 for inspection.
Results logged to /Users/tyler/Desktop/pepper/pepperapi/vendor/bundle/ruby/2.3.0/extensions/universal-darwin-17/2.3.0/pg-1.0.0/gem_make.out

An error occurred while installing pg (1.0.0), and Bundler cannot continue.
Make sure that `gem install pg -v '1.0.0'` succeeds before bundling.
```


However the command listed above works fine:

$ sudo ARCHFLAGS="-arch x86_64" gem install pg -v '1.0.0'


It appears the context of bundler is breaking something...

**Comment by montaserfzy** [comment]
@imechemi Thanks Man Worked for me

**Comment by mig-hub** [comment]
I am having the same problem now on a new Mac with M1 ship. I have tried the provided solution with `ARCHFLAGS="-arch arm64"` instead but it does not work. Anyone had a chance to make this work on Apple M1 Mac?

**Comment by tbussmann** [comment]
This issue contains partially outdated information, multiple topics and off-topic comments, I'm going to lock it. In case you are experiencing a problem connecting to PostgresApp with Ruby, please file a new issue containing information on your environment, your intention, what you have tried so far and what is the error or result. Thanks!
@mig-hub: please do so as well, I'm unsure what you mean by "the same problem" ;)
