### ISSUE TITLE
Postgres.app - Could not start on Port 5432

### ISSUE THREAD

**Issue by JoeFryer** [PostgresApp/PostgresApp#197]
Hi,

I'm getting the message 'Could not start on Port 5432' when launching Postgres.app (it says the same from the menu bar item). 

I've exhausted Google/SO, and I can't seem to fix it. From my research, I feel it may be related to the fact that I previously had pgAdmin installed on my machine.

Can anyone help with this?

**Comment by thanhlevu** [comment]
$ sudo pkill -u postgres

**Comment by Shahdevanshee** [comment]
> $ sudo pkill -u postgres

this helped me

**Comment by tbussmann** [comment]
> `$ sudo pkill -u postgres`

just to explain what this does: it sends a `SIGTERM` signal to all processes currently running under a effective (system) user named 'postgres'. 
Please be aware that there is no default user with that name on macOS nor does PostgresApp create such a user, so this is targeting a third party instance. There is the chance this one is configured to be kept alive or automatically started at boot time, so you better properly uninstall such a third party distribution if you want to get rid of it.

PostgresApp's uninstall instructions for other postgres distributions can be found [here](https://postgresapp.com/documentation/remove.html). I like to mention, while not recommended, it is perfectly possible to run multiple installations from multiple source simultaneously if you carefully manage the `$PATH` and ports.

**Comment by marcomcnulty** [comment]
I had forgotten that I had previously installed and started postgres with Homebrew, so I was really confused as to why the process regenerated every time I killed it (stopping Postgres.app from working). The solution was to run the command:

`brew services stop postgres`

as per: https://stackoverflow.com/a/50043459/6619089

**Comment by victortejeda** [comment]
> $ sudo pkill -u postgres me funcionó a mi también gracias
