### ISSUE TITLE
Could not start on port 5432

### ISSUE THREAD

**Issue by idigit** [PostgresApp/PostgresApp#200]
I can't get Postgres Version 9.3.5.0 to start - I get the following error:

> Could not start on port 5432

I followed issue #152, and still am having trouble.

Following the troubleshooting, I'm getting:

```
LOG:  could not translate host name "localhost", service "5432" to address: nodename nor servname provided, or not known
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
```

nslookup localhost shows:

```
Server:     10.0.1.1
Address:    10.0.1.1#53

Non-authoritative answer:
Name:   localhost
Address: 127.0.0.1
```

/etc/hosts shows:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1   localhost
255.255.255.255 broadcasthost
::1             localhost 
fe80::1%lo0 localhost
```

Any ideas?

**Comment by lichtamberg** [comment]
I may have a solution for this problem:

I was changing my /etc/hosts file with sublime text (Stable, v. 3065), saved (was asked for my password), and postgres didn't work anymore.. 

I opened up again my hosts file with sublime and everything looked fine.. Couldn't find any problems..!

But when I opened the file via vim/cat, I saw that the linebreaks were somehow corrupted by sublime..
After pasting the content from sublime into vim, everything worked fine again!

**Comment by kirothehero1** [comment]
For others who may experience this problem, I had the same issue. I did some digging around and discovered that it's an issue with the /private/etc/hosts file.  I tried opening it with vim but it turns out for some reason it didn't exist. So I went into terminal  did a `defaults write com.apple.finder AppleShowAllFiles YES` . Then I navigated to the /private/etc/ folder and  copied it to the desktop. I edited with text edit to reference the `127.0.0.1   localhost` line and copied it back into /private/etc. It worked!

**Comment by es6Test** [comment]
I just downloaded this app to day for my mac,  I have no ` /private/etc/hosts` file.

I'm getting

```
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
 ```

**Comment by ramseyjiang** [comment]
The same problem, I search on the google, but I cannot find the correct idea can fix the problem.

**Comment by ramseyjiang** [comment]
scutil -r localhost
Not Reachable

ping localhost
ping: cannot resolve localhost: Unknown host

**Comment by ramseyjiang** [comment]
I fixed it, it is caused by /etc/hosts

**Comment by julianpistorius** [comment]
For time travelers from the future, if you see this error - then it is almost certainly because you hit the 'Open Files Limit'.

See:

http://docs.basho.com/riak/kv/2.1.4/using/performance/open-files-limit/

**Comment by alexQueue** [comment]
@julianpistorius how did you come to that conclusion?

**Comment by aliabbas110** [comment]
I have been struggling on this also. It happens after a full restart of mac. could not get the cause but came up with following solution to fix this. 

`sudo killall -INFO mDNSResponder`

hope someone can get the cause and permanent solution.

**Comment by jakob** [comment]
Please stop posting comments to this issue. It's closed. If you have a similar problem, please open a new issue, and mention the number of this issue.

Thanks!
