### ISSUE TITLE
Could Not Open on Port 5432

### ISSUE THREAD

**Issue by klouie93** [PostgresApp/PostgresApp#206]
Hi I'm running OSX 10.8.5.0 and Postgres 9.3.5.0. As soon as I downloaded it and opened, it said it couldn't run on Port 5432. When I try to open it, it shows this: 

```
cmu-786603:~ klouie$ '/Applications/Postgres.app/Contents/Versions/9.3/bin'/psql -p5432
Password: 
```

and asks for a password. I thought it was my computer password, but it's not. When I try running it again, this happens:

```
cmu-786603:~ klouie$ psql
psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/pgsql_socket/.s.PGSQL.5432"?
```

UPDATE:
Followed troubleshooting instructions on Postgress site. Looked to see specific issues. Came up with:

```
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
```

**Comment by kevinzzz007** [comment]
Hi my app keep telling me there is another instance running already, but how do I shutdown that instance on Mac and restart Postgresql?  Thanks!

**Comment by jakob** [comment]
@kevinzzz007 Please follow [these instructions](http://postgresapp.com/documentation/remove.html).

If that doesn't help, please open a new issue -- your problem is probably unrelated to this issue.

**Comment by kevinzzz007** [comment]
Hi, I figured it out.  I just needed to figure out my server directory and use 

`pg_ctl -D /server/directory/postgres stop`

**Comment by jakob** [comment]
@kevinzzz007 Great. Just make sure your old installation isn't configured to start automatically when you reboot your computer.

**Comment by kevinzzz007** [comment]
@jakob actually pg_ctl didn't work, had to use launchctl to stop it.  I tried this solution(http://superuser.com/questions/244589/prevent-postgresql-from-running-at-startup) to stop my postgresql start at startup, but I couldn't find the file `com.edb.launchd.postgresql-9.0.plist`, is there an alternative to using the solution in the link?  Thanks!

**Comment by jakob** [comment]
Launchd files are stored in the following directories:
- ~/Library/LaunchAgents
- /Library/LaunchAgents
- /Library/LaunchDaemons
- /System/Library/LaunchAgents
- /System/Library/LaunchDaemons

But the best way to get rid of old PostgreSQL installations is to follow [these uninstall instructions](http://postgresapp.com/documentation/remove.html).

**Comment by thanhlevu** [comment]
try this:
$ sudo pkill -u postgres

**Comment by zctocm** [comment]
> try this: $ sudo pkill -u postgres

This works. Thanks
