### ISSUE TITLE
No GDAL drivers found

### ISSUE THREAD

**Issue by dreanod** [PostgresApp/PostgresApp#212]
When I run:

```
SELECT st_gdaldrivers();
```

I get:

```
NOTICE:  No GDAL drivers found
 st_gdaldrivers 
----------------
(0 rows)
```

Has this something to do with the fact that psql doesn't understand functions like ST_AsPNG or ST_AsGDALRaster?

For info, when I run 

```
SELECT postgis_full_version();
```

I get:

```
POSTGIS="2.1.3 r12547" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.0, released 2013/04/24" LIBXML="2.9.1" LIBJSON="UNKNOWN" TOPOLOGY RASTER
```

I'm running the Postgres version 9.3.5.0 on OS X 10.9.3.

**Comment by tbussmann** [comment]
This is expected as it is the default for PostGIS installations, see [PostGIS documentation](http://postgis.net/docs/postgis_gdal_enabled_drivers.html). You can define which drivers to enable using the GUC `postgis.gdal_enabled_drivers` on session, user, database and cluster level. To enable all drivers globally and permanently issue as superuser:
```
ALTER SYSTEM SET postgis.gdal_enabled_drivers = 'ENABLE_ALL';
SELECT pg_reload_conf();
```
