### ISSUE TITLE
Local connections sometimes fail via IPv6 on Yosemite

### ISSUE THREAD

**Issue by kallekoo** [PostgresApp/PostgresApp#234]
For local connections OS X Yosemite sometimes hands a socket from fe80::1%lo0 which is not present in Postgres.app's pg_hba.conf. This applies for both the 'psql' command and connections via Psycopg2.

Steps to reproduce:
bash$ while true; do psql -q -h localhost dbnamehere -c ""; done >> psqllog
psql: FATAL:  no pg_hba.conf entry for host "fe80::1%lo0", user "user", database "dbnamehere", SSL off
...

A workaround(?) is to add another line for the link-local address prefix to pg_hba.conf:
host   all             all             fe80::/64               trust

**Comment by jakob** [comment]
I'm closing this issue. I'm not sure when it was fixed, but I'm pretty sure that recent versions of PostgreSQL and OS X don't have that issue anymore.
