### ISSUE TITLE
Enable Debugging

### ISSUE THREAD

**Issue by rardoz** [PostgresApp/PostgresApp#236]
I'm trying to enable / install http://www.pgadmin.org/docs/1.8/debugger.html edb-debugger plugin and all documented methods do not work with the postgres.app. Any clue on how to get this working?

Thanks in advance!

**Comment by dizzus** [comment]
Agree, add debugger extension would be a great feature.

**Comment by avlad** [comment]
sure, exactly when on main page:
"Postgres.app is a full-featured PostgreSQL installation ..."

**Comment by xleliberty** [comment]
Hi, 
any progress on this ? 
thanks
