### ISSUE TITLE
pg_upgrade issues migrating data during 9.3 to 9.4 upgrade

### ISSUE THREAD

**Issue by albertlyu** [PostgresApp/PostgresApp#241]
I've since resolved this, but I wanted to report what I remember about the issues I had with upgrading 9.3 to 9.4. I used the instructions under 'Migrate data using pg_upgrade' under [this link](http://postgresapp.com/documentation/install.html). I completed each of Steps 1-4 exactly as written, then proceeded to run the following ```pg_upgrade``` command in my Terminal:

```
$ /Applications/Postgres.app/Contents/Versions/9.4/bin/pg_upgrade \
$ -d "/Users/albertlyu/Library/Application Support/Postgres/var-9.3" \
$ -D "/Users/albertlyu/Library/Application Support/Postgres/var-9.4" \
$ -b /Applications/Postgres.app/Contents/Versions/9.3/bin \ 
$ -B /Applications/Postgres.app/Contents/Versions/9.4/bin \
$ -v
```

(Note that I had to explicitly specify the right ```pg_upgrade``` 9.4 executable instead of the 9.3 one) In my first execution of that ```pg_upgrade``` script, I found the following in my ```pg_upgrade_utility.log```:

```
CREATE ROLE "postgres";
CREATE ROLE
ALTER ROLE "postgres" WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION PASSWORD 'md532e12f215ba27cb750c9e093ce4b5127';
ALTER ROLE
CREATE DATABASE "albertlyu" WITH TEMPLATE = template0 OWNER = "albertlyu";
psql:pg_upgrade_dump_globals.sql:43: ERROR:  database "albertlyu" already exists
```

So I dropped my 'albertlyu' database, and ran the upgrade script again. This time, I found the following in my Terminal output:

```
Checking database user is a superuser                       executing: SELECT rolsuper, oid FROM pg_catalog.pg_roles WHERE rolname = current_user
executing: SELECT COUNT(*) FROM pg_catalog.pg_roles 
ok

Only the install user can be defined in the new cluster.
Failure, exiting
"/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_ctl" -w -D "/Users/albertlyu/Library/Application Support/Postgres/var-9.4" -o "" -m fast stop >> "pg_upgrade_server.log" 2>&1
```

So I had to drop my non-install users (i.e. every user not named 'albertlyu', including 'postgres') after [reading this](http://www.postgresql.org/message-id/20130509171152.GC24522@momjian.us). I also dropped my 'albertlyu' database again. Only after this did I get the 'Upgrade Complete' message and did my data files get successfully migrated to the new data directory.

So my question is whether I made any mistakes along the way (given what I remember) or if this is a potential bug in Postgres.app dealing with ```pg_upgrade``` from 9.3 to 9.4? Installing the new Postgres 9.4 version automatically created 'albertlyu' as my superuser and the default database 'albertlyu', but the ```pg_upgrade``` script appears to try to migrate 'albertlyu' where 'albertlyu' already exists. Does my reasoning make sense here, or is this a non-issue? Whatever the case, I was able to successfully upgrade, but wanted to submit this issue here in case anyone else has similar issues.

**Comment by jace** [comment]
For anyone here trying to upgrade from 9.4 to 9.5, here's what you need to do:

1. Copy the `Contents/Versions/9.4` folder from the old app into the new app, as instructed. DO NOT RUN THE NEW APP YET.
2. Shut down the running server, if any.
3. Ensure the new app is now at `/Applications/Postgres.app`
4. If you did run the app, remove the default cluster it made for you: `rm -rf ~/Library/Application\ Support/Postgres/var-9.5` (**Warning:** Don't do this if you have data in the 9.5 cluster)
5. Create an empty cluster: `initdb -D ~/Library/Application\ Support/Postgres/var-9.5`
6. Run the upgrade: `/Applications/Postgres.app/Contents/Versions/9.5/bin/pg_upgrade -b /Applications/Postgres.app/Contents/Versions/9.4/bin -B /Applications/Postgres.app/Contents/Versions/9.5/bin -d ~/Library/Application\ Support/Postgres/var-9.4 -D ~/Library/Application\ Support/Postgres/var-9.5 -v`
7. PROFIT!

**Comment by jakob** [comment]
@jace Thanks for the write up. Would you like to add those directions directly to the docs (and then send a pull request)?

Here's the file: https://github.com/PostgresApp/postgresapp.github.io/blob/master/documentation/install.md

**Comment by jace** [comment]
Done. There's a German doc as well though.

**Comment by jakob** [comment]
Thanks! I added the German translation myself.
