### ISSUE TITLE
ST_Transform on raster not working?

### ISSUE THREAD

**Issue by JerryBlack** [PostgresApp/PostgresApp#243]
Not sure if I have a version problem, library problem, permission issues etc. 
```
SELECT PostGIS_Full_Version();
POSTGIS="2.1.4 r12966" 
GEOS="3.4.2-CAPI-1.8.2 r3921" 
PROJ="Rel. 4.8.0, 6 March 2012" 
GDAL="GDAL 1.11.1, released 2014/09/24" 
LIBXML="2.9.1" 
LIBJSON="UNKNOWN" (core procs from "2.1.0 r11822" need upgrade) 
RASTER (raster procs from "2.1.0 r11822" need upgrade)
```
ST_Transform does not appear to work on rasters (at least for me)
```
SELECT st_transform(rast,3573) as rast2 FROM dem2 limit 1 /* original SRID is 4617 */;
ERROR:  rt_raster_gdal_warp: Could not create GDAL transformation object for output dataset creation
CONTEXT:  SQL function "st_transform" statement 1
```
non-raster objects can be **ST_Transform**ed without any issue. **Is anyone else having problems with raster st_transform**?

This raster has these attributes
```
r_table_name r_raster_column srid      scale_x       scale_y blocksize_x blocksize_y same_alignment regular_blocking num_bands pixel_types
1         dem2            rast 4617 0.0002083333 -0.0002083333        1000        1000           TRUE            FALSE         1     {16BSI}
  nodata_values out_db
1      {-32767}    {f}
```

**Comment by JerryBlack** [comment]
Here is an example that generates a raster on-the-fly, which in my environment, generates the same error.
```
SELECT ST_Transform(
  ST_AsRaster(
   ST_GeomFromText(E'LINESTRING(100.495995129 13.7117836894,100.495962221169 13.7117761471941)',4326),
        100., -100.,
        ARRAY['8BUI', '8BUI', '8BUI', '8BUI']::text[],
        ARRAY[29, 194, 178, 255]::double precision[],
         ARRAY[0, 0, 0, 0]::double precision[]
           ) 
,32647);
ERROR:  rt_raster_gdal_warp: Could not create GDAL transformation object for output dataset creation
CONTEXT:  SQL function "st_transform" statement 1
```

**Comment by JerryBlack** [comment]
I have solved my problem by adding the PROJSO environment variable to an apple script which is executed at login. I also restrict the GDAL drivers to my minimum requirement, to hopefully reduce the security risk. The PROJSO may help with issue #239

    do shell script "launchctl setenv POSTGIS_GDAL_ENABLED_DRIVERS GTiff"
    do shell script "launchctl setenv PROJSO /Applications/Postgres.app/Contents/Versions/9.4/lib/libproj.dylib"

**Comment by jakob** [comment]
Thanks for reporting this, including the command to reproduce. The command now runs successfully with the latest build https://github.com/PostgresApp/PostgresApp/releases/tag/9.4.1.2

**Comment by JerryBlack** [comment]
Excellent!
(jakob please delete when read)
