### ISSUE TITLE
No Yosemite Dark Mode support

### ISSUE THREAD

**Issue by lachlanjc** [PostgresApp/PostgresApp#246]
When I’ve got Yosemite in Dark Mode, PostgresApp doesn’t use a white version of the icon in the menu bar.

![dark-mode-postgres](https://cloud.githubusercontent.com/assets/5074763/5693067/4f6e8bca-98db-11e4-856c-e384f7543092.png)

**Comment by jakob** [comment]
Which version are you using? I thought I fixed this already...

**Comment by lachlanjc** [comment]
@jakob 9.4.3.1 (23)

**Comment by lachlanjc** [comment]
@jakob Sorry! I downloaded the latest version and it’s looking :+1:. Thought PostgresApp was auto-updating.
