### ISSUE TITLE
I really need the Postgres.app version 9.2.2.0. Can anyone help me out??

### ISSUE THREAD

**Issue by ddd1600** [PostgresApp/PostgresApp#247]
I'm not the best developer in the world, but I've figured out how to do everything I need to do if I could just get my hands on a copy of Postgres.app version 9.2.2.0. The link at http://postgres-app.s3.amazonaws.com/PostgresApp-9-2-2-0.zip used to be live, but now its not.

Can anyone help me out?

**Comment by jakob** [comment]
You can find old versions at 
https://github.com/PostgresApp/PostgresApp/releases

Doesn't look like 9.2.2.0 is available. The AWS link pointed to @mattt's personal S3, I assume he removed it when we switched to hosting binaries on github.

Maybe someone still has a copy somewhere... Depending on your use case, it might be easier to just change the build script of the current version to build an older version of PostgreSQL. Let me know more about your problem, maybe I can help.

Jakob

**Comment by ddd1600** [comment]
This didn't end up being an issue because the latest version of Postgres.app (9.4ish) did not have the compatibility issues with OSX that the 9.3ish version I downloaded last year had.
