### ISSUE TITLE
Can't build helper on Xcode: No signing identity found

### ISSUE THREAD

**Issue by hcarvalhoalves** [PostgresApp/PostgresApp#249]
Hi. I made a fork to support Postgres 8.3 and compiled it successfully, now I'm trying to build the helper on XCode 6.1 but I get the error:

```
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
```
I just want a non-signed build to myself. How do I fix this?

**Comment by jakob** [comment]
1. Click on the "Postgres" project icon at the top of the left sidebar
2. Select "Postgres" in the target popup
3. In the "General" tab, set "Signing" to "none"
4. Select "Postgres-helper" in the target popup
5. Again set "Signing" to "none"

**Comment by jakob** [comment]
![](https://cloud.githubusercontent.com/assets/198305/6001966/3f8d194e-aaef-11e4-81bd-db11e6bd474e.png)

**Comment by hcarvalhoalves** [comment]
I tried that, but it kept nagging me about it. I ended up fixing by manually editing `project.pbxproj` and removing all mentions to `CODE_SIGN_IDENTITY`. Thanks.
