### ISSUE TITLE
Attempting to Use Postgres.app with RVM

### ISSUE THREAD

**Issue by lightbe** [PostgresApp/PostgresApp#251]
I did a clean install on my Mac Mini Server running Mavericks and the Server app.  Apparently RVM has changed where their stuff has to appear at the beginning of the PATH statement.  My PATH statement adds folders to the statement when I echo $PATH where the server app folders appear before the folder for postgres.app if I attempt to put the folder right after the RVM folders.

I did a site:postgresapp.com for RVM and found nothing.

Is anyone successfully using postgres.app and RVM? If so I could use some help with my bash statements.  If not I will remove RVM.  Postgres.app is way more important. My bash knowledge is very limited.

**Comment by eaglerockdude** [comment]
What is the issue?  I am using rvm and postgress.app...recently set up..everything seems to be ok..

**Comment by lightbe** [comment]
It appears that this is not a problem after all.  I still get a RVM error as described because postgres.app is at the beginning of the PATH, not RVM.  However I can successfully use both without experiencing any problems.  The warning message scared me a bit but is not causing problems with RVM.
