### ISSUE TITLE
how to debug remote connection to Postgres.app (yosemite) on LAN?

### ISSUE THREAD

**Issue by Roo123** [PostgresApp/PostgresApp#255]
Hi,

Thanks for a great app.. Have running on OS X Yosemite and connect on localhost with Navicat no problem.

Have been unable to connect from other machines on LAN (Debian with Psycopg2; iOS with Postgresql client). With and without firewall on (app is added to permitted apps). Router is Airport Extreme.

(Get standard error messages if server running and accepting TCP on 5432: as far as I can tell those conditions are met.)

How do I debug this?

R.

**Comment by jakob** [comment]
In the data directory in the file postgresql.conf, make sure that listen_address is * instead of localhost. Then make sure you also allow connections in pg_hba.conf

**Comment by Roo123** [comment]
Many thanks jakob. Most grateful.

Located the config files' path using "SHOW config_file;" in Postgres. Once edited as you suggested now works great.
