### ISSUE TITLE
Postgres 9.3.6 release?

### ISSUE THREAD

**Issue by joshma** [PostgresApp/PostgresApp#256]
Just wondering if/when there'll be a 9.3.6 release - thanks!

**Comment by jakob** [comment]
I didn't plan on doing it, but since there's demand for it I will make a build as soon as I have some spare time.

**Comment by jakob** [comment]
Just uploaded a 9.3.6 release.
https://github.com/PostgresApp/PostgresApp/releases/tag/9.3.6.0

**Comment by joshma** [comment]
:+1: thanks a ton
