### ISSUE TITLE
Failing to connect to server

### ISSUE THREAD

**Issue by EllaNancyFay** [PostgresApp/PostgresApp#257]
After restarting my mac I'm getting this error when trying to connect to psql:

psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

**Comment by jakob** [comment]
Did you set PostgresApp to start on login? Is it running, ie. is there an elephant in your menu bar?

**Comment by EllaNancyFay** [comment]
I'm not sure if it's set to start on login. Yes there is an elephant in my
menu bar.

**Comment by jakob** [comment]
Did Postgres.app show any errors when starting?

Also check the log (~/Library/Application Support/Postgres/var-9.4/postgres-server.log) for any startup errors.

**Comment by EllaNancyFay** [comment]
Yes. It says:

Could not initialize database cluster.
initdb: could not create directory "pg": Permission denied.

**Comment by jakob** [comment]
This sounds like a permissions issue. Make sure that you have read/write permissions on the data directory. Default is ~/Library/Application Support/Postgres/var-9.4/, unless you changed it in the preferences.

**Comment by jakob** [comment]
I assume this is resolved, so I'm closing this issue for now.

**Comment by JaredBoone** [comment]
I had this same issue. Check that you haven't inadvertently changed the path in the Preferences dialog. See http://stackoverflow.com/questions/30993794/postgres-app-wont-start for more detail.
