### ISSUE TITLE
Please add a automatic update mechanism for this app

### ISSUE THREAD

**Issue by patricks** [PostgresApp/PostgresApp#260]
It would be nice, if there where a automatic update mechanism for this app, so I don't have to look at the homepage every few month. Maybe you can include something like sparkle?

**Comment by jakob** [comment]
Yes, that would be useful. Sparkle is probably not suited. We would probably need to write our own thing that queries the Github API.

For now, you could try watching the repository on Github to be notified of updates (but then you'll also get notifications for new issues etc, I'm not sure if it's possible to filter the notifications...)

**Comment by patricks** [comment]
Ok, thanks for your infos. I looked at your source code and saw that you already added the sparkle.framework. I think the only way to provide a appcast.xml is via an static website.

**Comment by jakob** [comment]
Sparkle framework is a remnant from the distant past; I thing Mattt wanted to add support for automatic updates, but I think he never got around to it. It might be possible to get to work, but I'd prefer something that queries the Github API directly.

**Comment by connorshea** [comment]
Would love this!

**Comment by jakob** [comment]
Postgres.app 2.0 now has automatic updates, and we have decided to go with Sparkle. Integrating was actually easier than expected. (We just added an appcast.xml file that we're updating manually)
