### ISSUE TITLE
Support Yosemite dark theme

### ISSUE THREAD

**Issue by atapin** [PostgresApp/PostgresApp#261]
Would be great to have a white icon for dark theme in Yosemite.

![image](https://cloud.githubusercontent.com/assets/1181403/7766688/4b7980c6-0085-11e5-892d-60f45616c28b.png)

**Comment by jakob** [comment]
Are you running the latest version? I thought we fixed that already.

**Comment by atapin** [comment]
@jakob my bad, I should have checked the closed issues before posting a new one. Looks perfect on latest version.

**Comment by jakob** [comment]
No worry, issues that can be closed within minutes are my favorite :)

**Comment by jakob** [comment]
Btw: new PostgreSQL version is coming later today.

**Comment by atapin** [comment]
@jakob great news!

**Comment by jakob** [comment]
(It's just a bugfix update though -- 9.4.2)
