### ISSUE TITLE
Unable to download Postgresapp 9.3.5.0

### ISSUE THREAD

**Issue by oceanwap** [PostgresApp/PostgresApp#264]
I was trying to download from https://github.com/PostgresApp/PostgresApp/releases/tag/9.3.5.0
but timed out. 

I urgently need to setup Postgresapp 9.3.5.0. Please fix it.

**Comment by jakob** [comment]
This file is hosted by Github on Amazon S3. There's nothing I can do to help. Please contact Github support.

**Comment by oceanwap** [comment]
I understand. Earlier I thought file is missing but problem is everywhere. You can also host it somewhere as an alternate link for such situations. 

Thanks for responding too quick.
