### ISSUE TITLE
ossp-uuid extension no longer included in >= 9.3.6

### ISSUE THREAD

**Issue by cmordue** [PostgresApp/PostgresApp#265]
In the 9.3.6.0 and 9.3.7.0 builds of PostgresApp, the ossp-uuid extension is not installed (at least on OSX). Looks like this occurred at this commit: https://github.com/PostgresApp/PostgresApp/commit/2c817c08d753095c44eb226bd21629bd365e6827#diff-210e3527f52409b84fd1c50fcea0df2fL59 on the 9.3 branch. Subsequent releases of 9.3 were made off of this branch (reverting the postgres version from 9.4.x to 9.3.x) but the changes to ossp-uuid extension in this commit remain, causing the ossp-uuid extension to not be installed.

**Comment by kikar** [comment]
Using latest version and command `CREATE EXTENSION "uuid-ossp";` works fine for me

**Comment by jakob** [comment]
Hey @cmordue, thanks for reporting this issue. I finally got a chance to fix this. The UUID extension should work again in 9.3.9.0. Download from https://github.com/PostgresApp/PostgresApp/releases/tag/9.3.9.0
