### ISSUE TITLE
Add PSequel to list of GUI Applications

### ISSUE THREAD

**Issue by aristidesfl** [PostgresApp/PostgresApp#268]
Add [PSequel](http://www.psequel.com/) to list of [GUI Applications](http://postgresapp.com/documentation/gui-tools.html)

**Comment by jakob** [comment]
PSequel is already on the PostgreSQL Wiki page linked at the top of that page (incorrectly under Open Source software). I see no reason for a direct link.

**Comment by aristidesfl** [comment]
What about the other tools in the page?

**Comment by jakob** [comment]
pgAdmin is the official PostgreSQL GUI, and while the UI isn't pretty, it has very extensive support for most of PostgreSQL's features.

Induction and PG Commander are on the page because they are made by contributors to Postgres.app. (Mattt and myself, respectively).

**Comment by aristidesfl** [comment]
Makes sense, thought is was a collection of Postgres OS X Applications.

**Comment by jakob** [comment]
I reconsidered and added direct links to the page; there's now a link to PSequel in the [list of GUI Applications](http://postgresapp.com/documentation/gui-tools.html)
