### ISSUE TITLE
new patch version Postgres (9.4.3)

### ISSUE THREAD

**Issue by damirv** [PostgresApp/PostgresApp#270]

**Comment by Tafkas** [comment]
I submitted PR #269

**Comment by jakob** [comment]
Are you asking because you ran into problems with 9.4.2?

To my knowledge the permissions issues that were fixed in 9.4.3 don't really affect Postgres.app.

**Comment by damirv** [comment]
No you are right, just mentioned it to keep the project in sync :)

**Comment by jakob** [comment]
I'll try to release 9.4.3 as soon as I have a few spare hours.

**Comment by damirv** [comment]
Sure, no problem. There is no rush here, because, like you've said, the
updates don't affect Postgres.app.

Kind regards,

Damir Vandic | Ontostream

**Comment by diwu1989** [comment]
9.4.4 please

**Comment by Tafkas** [comment]
@diwu1989 I updated to 9.4.4 in PR #269

**Comment by jakob** [comment]
done
https://github.com/PostgresApp/PostgresApp/releases/tag/9.4.4.0
