### ISSUE TITLE
Unable to start PostgresApp

### ISSUE THREAD

**Issue by mjhamm75** [PostgresApp/PostgresApp#271]
I am trying to start the `PostgresApp`, `Version 9.4.4.0 `.  I have had no issues until today.  I had to restart my machine, `Yosemite`, and now I get this error:
`Could not initialize database cluster:`
`initdb: could not create directory "I": Permission denied`

I have tried googling, but cannot come up with an answer.

**Comment by jakob** [comment]
It looks like Postgres.app tries to create a new data directory. Did you change the data directory in the preferences?

Could you also check the permissions on the data directory? Make sure you have read/write access.

**Comment by jakob** [comment]
Default data directory is `~/Library/Application Support/Postgres/var-9.4`

**Comment by mjhamm75** [comment]
When it wouldn't start, I deleted the app by putting the icon in the `Trash` and I also deleted that directory on the command line.  When I reinstalled, it did not recreate the data directory and I also got the same error that I did previously.  I have just created the `Postgres` directory and the `var-9.4` directory underneath.  I gave permissions of `777` and still get the same error.

**Comment by andrewdisley** [comment]
I’ve been having similar issues of late on 10.9 and 10.10 with permission error which causing psql to fail to start.

I managed to solve my issue by running the following command in Terminal after every reboot:
`chmod 700 ~/Library/Application\ Support/Postgres/var-9.4`

**Comment by mjhamm75** [comment]
That didn't fix my problem.

**Comment by jakob** [comment]
1. Check the preferences to see if you changed the data directory setting. Click the "Use Default" button if necessary.
2. Delete the Postgres directory in your Application Support folder and try again.
3. Check "Console.app" if any messages are shown when PostgreSQL fails to start
4. Try initializing the cluster manually using a command like `initdb -D "~/Library/Application Support/Postgres/var-9.4" -EUTF-8 --locale=en_US.UTF-8`

**Comment by jakob** [comment]
Make sure you [configure your path](http://postgresapp.com/documentation/cli-tools.html) before calling initdb

**Comment by mjhamm75** [comment]
I guess I deleted my defaults somehow.  I did step one and everything works perfectly.  Thanks for you time.
