### ISSUE TITLE
Postgres.app says "identity of the developer cannot be confirmed"

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#272]
It seems that Postgres.app fails Gatekeeper validation when it is not in the Applications folder. This means that opening it directly from your Download folder fails.

Apparently Apple has changed Gatekeeper validation to be more thorough. It checks dynamic library files in all binaries. Since Postgres.app uses static paths, they can't be found before Postgres.app is moved to the Applications folder.

**The workaround is to manually move the downloaded file to the Applications folder**; then Gatekeeper will be able to verify the binary just fine.

I have to think about a solution to this problem, but I'm not sure how to best solve it. We need the absolute path names since otherwise 3rd party tools can't link with libraries included with Postgres.app. Maybe we can start distributing an installer instead, but that would be really unfortunate; the nice thing about Postgres.app is that it doesn't need an installer...

**Comment by duncand** [comment]
Requiring a location in /Applications is preferable to using an installer, given that installers would still put things in predefined locations anyway rather than the usual Mac custom of letting us put applications wherever we want to.

**Comment by sethk** [comment]
Perhaps instead of an installer, you could provide a dmg with a background image stating that it probably won't run from anywhere besides `/Applications/`, and a shortcut icon to drag-and-drop it on? =)

**Comment by duncand** [comment]
Installers are uncomfortable in principle, especially if they prompt for an administrator password, since they could be doing who knows what to the system.  It is better just to have the DMG with the background image stating please drag Postgres.app to the /Applications folder so it can run.  Having to enter an admin password to do almost anything implies that the one prompting wants to do something they have no business doing.

**Comment by jakob** [comment]
The DMG sounds like a good idea.

I really wish there was a way to fix the dylib linking mess...

**Comment by JetForMe** [comment]
I think this should be fixable now, since Xcode lets you embed libraries in the bundle. But I also thought relative dylib paths were supported with `@executable_path`. This [SO question](http://stackoverflow.com/questions/33902231/how-to-create-app-with-relative-path-to-dylib) might have some clues.

**Comment by jakob** [comment]
@jetforme
I'm not sure what you mean that Xcode lets me embed libraries in the bundle. Obviously Postgres.app includes a bunch of libraries in the bundle.

Getting Postgres.app itself to work with relative dylib paths is not an issue (can be done with @rpath; @executable_path only works if all binaries are in the same relative position to the libraries)

The problem is that we also want to support other stuff linking against libpq (eg the pg gem). The problem is that you'd need to make sure that whatever links against libpq has the right @rpath, or it won't find dependencies of libpq. I don't know how to do this.

Also, the new version of Postgres (https://github.com/PostgresApp/PostgresApp/releases) ships in a disk image, with an icon suggesting you move it to /Applications, so I hope that more people just move it before opening.

**Comment by JetForMe** [comment]
Ah, I see.

The problem I'm facing is that I don't want to put it in /Applications. I want to put it in /Applications/Development (a directory I have for collecting such things).

> On Oct 31, 2016, at 15:52 , Jakob Egger <notifications@github.com> wrote:
> 
> @jetforme
> I'm not sure what you mean that Xcode lets me embed libraries in the bundle. Obviously Postgres.app includes a bunch of libraries in the bundle.
> 
> Getting Postgres.app itself to work with relative dylib paths is not an issue (can be done with @rpath; @executable_path only works if all binaries are in the same relative position to the libraries)
> 
> The problem is that we also want to support other stuff linking against libpq (eg the pg gem). The problem is that you'd need to make sure that whatever links against libpq has the right @rpath, or it won't find dependencies of libpq. I don't know how to do this.
> 
> Also, the new version of Postgres (https://github.com/PostgresApp/PostgresApp/releases) ships in a disk image, with an icon suggesting you move it to /Applications, so I hope that more people just move it before opening.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- 
Rick Mann
rmann@latencyzero.com

**Comment by jakob** [comment]
With Postgres.app 2.0 being distributed as a disk image, and an explicit warning about having to move it to /Applications, I think we can close this issue now.
