### ISSUE TITLE
Initial superuser should be "postgres" by default; a secondary superuser $USER should be created afterward

### ISSUE THREAD

**Issue by nelsnelson** [PostgresApp/PostgresApp#275]
When installing Postgres.app, the superuser should be "postgres" by default, and a secondary superuser account "$USER" should be also created for easy psql login.

As it stands now, the name of the superuser is whatever $USER happened to open Postgres.app for the first time.

It breaks typical postgresql installation convention to have a user called $USER (whatever I happen to be called) owning all the system database stuff.

Affects version: 9.4.4.1

**Comment by nelsnelson** [comment]
Workaround:

Delete all existing installations and databases created by Postgres.app.
Create a new login user called "postgres".  
Login with "postgres" through the login screen.
Install Postgres.app into /Applications as the user "postgres".
Open Postgres.app.
From the command line, list the existing databases: `psql -U postgres --command="\l"`.
Confirm that the postgres database is installed, and that the "postgres" user owns all existing default system databases.
Logout of the session for the user "postgres".
Switch to your regular user.
Kill any existing Postgres processes.
As root, copy the directory /Users/postgres/Library/Application\ Support/Postgres to /Users/$USER.
Restart Postgres.app.
You may now use `psql -U postgres`.
You may now also create a login user/role for your own system user: `psql -U postgres --command="CREATE ROLE \"${USER}\" LOGIN;"`

**Comment by jakob** [comment]
Postgres.app is designed to be a lightweight PostgreSQL installation that does not change any of your system configuration. Therefore creating a new system user named "postgres" is out of the question.

Using a single username on the postgres side also makes administration easier. There's no need to provide a username when using tools like psql, pg_dump or createdb. You'll never run into permissions issues because you are the superuser.

The goal of Postgres.app is to make it easy to get started with PostgreSQL, and not let features designed for larger deployments get in the way. I assume that only very few people use a PostgreSQL server running on their Macbook as a multi user database.

If you want a more traditional installation of PostgreSQL, I'd recommend using the EnterpriseDB installer (which will set up a user account named "postgres"), or using a package manager like MacPorts or homebrew.

**Comment by nelsnelson** [comment]
I was not suggesting that a system user actually be created on a mac os install.

I only suggested that the default superuser for the PostgreSQL not be the system $USER (whatever it happens to be the first time Postgres.app is run), but instead, the default superuser should be the same as it is in every other PostgreSQL installation in any system: 'postgres'.

The default superuser was already 'postgres' until some recent change.  Do you need me to go back through changelogs here to figure out which version broke?  At least some recent previous versions of Postgres.app used 'postgres' for the default superuser.

This `superuser = $USER` change has broken my database scripts.  But now they are only broken when using Postgres.app, after having recently upgraded to the 9.4.4.1 version of Postgres.app.  My scripts are not broken in any other of my other installations of postgres, "EnterpriseDB" or otherwise.

It would be nice to not have a easy-to-use Postgres server break my development environment.  Perhaps an option for explicitly setting the superuser could be supported upon install?  It appears there is already a significant change in the way that Postgres.app sets its server up when it is ran for the first time, in that a new modal prompt is displayed, and the user is given the opportunity to make at least a couple adjustments.  This was not the case in at least some previous versions.

**Comment by tbussmann** [comment]
What postgres.app does when it starts for the first time (data dir not existing) is to do a initdb as the current user (this creates a superuser role named after the user) and a createdb for a database named after the current user. This has been the case for as long as I remember using Postgres.app. The benefit is that the client tools (like psql) default to a user and database named after the current login user, so you don't need to specify.

If you like full control over the init behaviour you can run these steps on your own (or using your own script) before you start Postgres.app for the first time with a data dir. You can then control the name of the superuser with the -U switch to initdb. Please note that the "Open psql" item in the menu of Postgres.app will probably not work out of the box if you use custom user / db names.

**Comment by jakob** [comment]
Tobi is right. I don't recall Postgres.app ever creating a (postgresql) root user named postgres.

You can find the initdb commands Tobi mentioned in the [README file](https://github.com/PostgresApp/PostgresApp/blob/master/README.md) or here in [this source file](https://github.com/PostgresApp/PostgresApp/blob/master/Postgres/PostgresServer.m#L299).

I agree that it would be nice if some features could be configured, but writing code to do it in the UI is a lot of effort.

Maybe we should just improve the documentation? It's currently not well documented how to manually initialize the cluster, start/stop the server etc.

**Comment by nelsnelson** [comment]
Improving documentation would be great.

Don't get me wrong, I totally understand why Postgres.app does what it does.

But it really is an inconvenience (and unexpected) to have to go through the workaround described above.  It would be really easy to just create a default 'postgres' superuser, like every other PostgreSQL installation out there -- but then to also create a non-superuser and database that can be automatically used by the current user $USER.  This way, you retain the ease-of-use of just being able to type `psql` without specifying the user with the `-U` flag, _and_ you retain the expected superuser naming convention.

I haven't done native Mac development in years, but I could tinker with the `PostgresServer.m` code a little and submit a patch that would support both the current ease of use, and also the conventional superuser configuration.  Would this be acceptable?

**Comment by jakob** [comment]
I don't want to change the default way that Postgres.app initializes the database cluster. The current setup seems to work fine.

You have a point that most other setups have a superuser named "postgres". If more people complain about this I might consider a change in a future version. Right now I want to leave it as it is.

(Also, part of the ease of use of Postgres.app is that the default user is a super user. If the default user is not a super user, you'll run into permission issues when restoring backups or when playing with features like table spaces or any number of other things.)

**Comment by jakob** [comment]
(I'm reopening this issue so it becomes more visible, and to invite others to comment on it.)

**Comment by nelsnelson** [comment]
Thanks, @jakob!

An additional step that could be taken is to include the conventional postgres superuser first, by default, and then as an additional automated step of the init process, create a second regular user based on $USER, along with their home database, and then finally to upgrade that user to superuser privileges: `ALTER USER $USER WITH SUPERUSER;`.

That might just solve for all concerns: both the convention and ease-of-use.

**Comment by Sogl** [comment]
+1
The current $USER decision only adds the problems.

**Comment by jakob** [comment]
I've now changed the behavior of Postgres.app to use the following procedure:

1. Postgres.app initialises the database using <br> `initdb -D DATADIR -U postgres --encoding=UTF-8 --locale=en_US.UTF-8`
2. Next it creates a user with the current system user name <br> `createuser -U postgres -p PORT --superuser  SYSTEM_USER_NAME`
3. Finally it creates a database for the new user <br> `createdb -p PORT SYSTEM_USER_NAME`

After this procedure, all system tables are owned by a user name postgres. Additionally, there's a superuser with the same name as the current system user name, and a database owned by that user.

I hope this fixes a few annoyances. Please download the latest 9.5 beta to try it out, along with the new features in 9.5: https://github.com/PostgresApp/PostgresApp/releases/tag/9.5beta2.0

Thanks to @nelsnelson and @tbussmann for your input!

**Comment by JerryBlack** [comment]
off topic somewhat... When I upgraded to the PostgresApp 9.5 beta 1, the upgrade seemed to work, but it appeared that PgAdmin3. 1.20.0 wouldn't work with my database.  Are others using PgAdmin3 1.20.0 with the 9.5 beta releases?

**Comment by jakob** [comment]
Just released 9.5.0.0, which should fix this issue. Thanks to everyone for their input!

**Comment by alexpchin** [comment]
@jakob Hello does the new version of 9.6 initialise with a user? 

Postgres.app initialises the database using 
`initdb -D DATADIR -U postgres --encoding=UTF-8 --locale=en_US.UTF-8`

Next it creates a user with the current system user name 
`createuser -U postgres -p PORT --superuser SYSTEM_USER_NAME`

Finally it creates a database for the new user 
`createdb -p PORT SYSTEM_USER_NAME`

I've had to manually:

`createuser $(whoami) -U postgres && createdb $(whoami) -U postgres` to prevent FATAL <user> not found error?

@eisacke @mickyginger

**Comment by jakob** [comment]
@alexpchin All versions of Postgres.app try to create a default user.

However, the legacy version of Postgres.app doesn't check if the port is available, so sometimes it fails to create a user when a different server was already running.

The new version of Postgres.app (2.0) should show an error in this case. However, if you already have a database set up, without a default user, it won't create it -- only when initially creating it.

Anyway, this is unrelated to this issue. If you have a problem with Postgres.app, please don't comment on closed issues. Please open new issues instead.
