### ISSUE TITLE
do you want the application postgres to accept incoming network connections pop up

### ISSUE THREAD

**Issue by toast9** [PostgresApp/PostgresApp#278]
I keep getting a pop up asking "do you want the application postgres to accept incoming network connections" every 2-5 seconds, and the box disappears after .5-5 seconds. Hitting allow or deny does nothing. This box pulls me out of whatever I'm working on and is making typing or just watching a video very very difficult. How can I get this to stop? And how do I stop postgres from automatically starting up on computer boot up, so I can just manually start it up? This is all on mac os x.

**Comment by jakob** [comment]
There's a checkbox in the preferences that allows you to select if you want Postgres.app to start automatically.

Those checkboxes are probably coming from a Firewall. Did you enable the built-in Firewall on your Mac, or install an app like Little Snitch? You might want to check if you've configured them correctly.

**Comment by toast9** [comment]
I have the box unchecked. It seems if I start postgres up the pop up stops, but I don't won't postgres running if I'm not using it. The Firewall is on, but postgres has been given access, so I'm not sure why it keeps asking.

**Comment by jakob** [comment]
Could it be that you have a different installation of PostgreSQL in additition to Postgres.app? For example the EnterpriseDB installer? If that's the case, you can find instructions to remove other installations here: http://postgresapp.com/documentation/remove.html

**Comment by jakob** [comment]
Closing this issue. Feel free to reopen if you have further questions.

**Comment by jakob** [comment]
A Postgres.app user contacted me via email and told me the following information:

> I had the same issue today and solved it by going to:
Mac > Preferences > Security & Privacy > Firewall tab > click lock > Firewall Options...
then removing the existing row for postgres.

> My PostgreSQL worked fine until installing Mac updates today and restarting.

**Comment by jbtpublic** [comment]
> A Postgres.app user contacted me via email and told me the following information:
> 
> > I had the same issue today and solved it by going to:
> > Mac > Preferences > Security & Privacy > Firewall tab > click lock > Firewall Options...
> > then removing the existing row for postgres.
> > My PostgreSQL worked fine until installing Mac updates today and restarting.

I had to point out the new location of postgres server in firewall before it stopped.
