### ISSUE TITLE
Symlinked .bashrc file is replaced with file copy. Target is not updated.

### ISSUE THREAD

**Issue by eliotsykes** [PostgresApp/PostgresApp#280]
Changes made by [`Postgres/PGShellProfileUpdater.m`](https://github.com/PostgresApp/PostgresApp/blob/28e9cf2d4957b4471b0f3598326d69cb4212de22/Postgres/PGShellProfileUpdater.m) to a symlinked `~/.bashrc` replaces the `.bashrc` symlink with a copy of the target file, and does not change the target file.

**Comment by peterhellberg** [comment]
I got the same issue just now. 

`Using Postgres.app for PostgreSQL 9.5.0`

**Comment by mamachanko** [comment]
Same here.

`Using Postgres.app for Postgres 9.4.6.1`

**Comment by jakob** [comment]
The newest version of Postgres.app no longer tries to automatically update your profile file.
