### ISSUE TITLE
How to start with PostgressApp

### ISSUE THREAD

**Issue by vinhqdang** [PostgresApp/PostgresApp#283]
Hello all

I downloaded and installed PostgresApp and pgadmin 1.2.0 in Mac OS. But I do not know how to continue: in Mac OS, I started Postgres and see the Elephant icon on Menubar already, and tried to connect pgadmin with Postgres, but what connection parameters I should use?

**Comment by tbussmann** [comment]
please have a to the documentation at http://postgresapp.com/documentation/gui-tools.html

**Comment by vinhqdang** [comment]
Hello

I took a look, but I am afraid that I do not understand much. I downloaded pgadmin as indicated in the website you mentioned, and start it, then try to connect the PostgresApp, but I do not know what connection parameters I should fill in?

**Comment by tbussmann** [comment]
With pgAdmin you only need to fill the Name field with any name you want to give the connection, it is just a description. The remaining parameters should be automatically filled with proper values to connect or can be left blank, respectively.

**Comment by vinhqdang** [comment]
Hello

When I tried to do as you said (thank you very much for your help), I met a problem: "the role postgres does not exist".

How can I resolve this problem?

**Comment by tbussmann** [comment]
in that case, it seems you've entered "postgres" in the Username field. You should use your local mac username in this place, which pgAdmin should fill in by default if you register a new server.

**Comment by powellmichael** [comment]
@vinhqdang did you get this issue resolved? If not I'd be happy to help you out. I use PostgresApp and Pgadmin daily with no issues.

**Comment by jakob** [comment]
Closing this issue now. If you have any more troubles, please feel free to open a new issue.
