### ISSUE TITLE
is PostgresApp El Capitan compatible?

### ISSUE THREAD

**Issue by JerryBlack** [PostgresApp/PostgresApp#285]
Not a bug report, but a question before I shoot myself in the foot with an incompatible El capitan upgrade.

**Comment by bloodycelt** [comment]
I upgraded to El Capitan, everything seems OK. Considering the current version puts the DB in $HOME/Library the only concern might be the log file, but it opened and let me connect to the db.

**Comment by jakob** [comment]
Yes, PostgresApp is completely El Capitan compatible.

Yes, the data directory is in the library folder, which is hidden by default. This has been the case since some time, and it shouldn't be a problem.
