### ISSUE TITLE
How to enable postgres user?

### ISSUE THREAD

**Issue by Sogl** [PostgresApp/PostgresApp#286]
Hi! 
Not an issue, but a question.

I'm working on both Windows and Mac machines and on Windows my standard username is `postgres`, but with this app my username in Mac OS X is equal as my system username. In result I have conflicts in my sql-scripts.

How can I change or enable standard `postgres` user?

**Comment by Sogl** [comment]
Anybody here? =)

**Comment by jakob** [comment]
You can create a user named postgres using the command 
```sql
CREATE USER postgres SUPERUSER
```
See the docs here: http://www.postgresql.org/docs/current/static/sql-createuser.html

It might also be helpful to read through issue #275

**Comment by jakob** [comment]
The latest 9.5 beta version now automatically creates a user name postgres during setup. I'm closing this issue; if you have further input, please comment on #275
