### ISSUE TITLE
pgrouting

### ISSUE THREAD

**Issue by spifftek70** [PostgresApp/PostgresApp#288]
I'm on OS X El Capitan and I'm using your latest version of the postgres.app.  I cannot get the pgrouting extension to install.  Is there anyway you can include this as an option?

**Comment by jakob** [comment]
Looks like pgrouting requires the boost library, which will make the binary quite a bit bigger. I'm not sure how many people would use pgrouting, so it would be nice if people who need this would voice there support here.

We could also just add build instructions to the docs, but right now I don't have the time to play with it to figure that out. If anyone knows how to build it, I'd appreciate it if you could write a tutorial for the docs!

**Comment by robe2** [comment]
I should add that postgis_sfcgal also relies on Boost and SFCGAL.  So if you package postgis_sfcgal, pgRouting doesn't add much extra.

**Comment by cvvergara** [comment]
+1

**Comment by citizenfish** [comment]
+1

**Comment by robe2** [comment]
FWIW I'm the windows application stackbuilder packager for PostGIS.

 I've already pushed for windows users for PostgreSQL 9.5 (the pgRouting 2.2.0).
I have no experience building for Mac though, but if you are worried about boost weight, keep in mind you don't need the full Boost library if you are building your own self-contained.

For windows I just build something like this:

```
	b2 toolset=gcc  --with-thread --with-system --with-date_time --with-serialization --with-graph --with-program_options

```

Which is sufficient for both SFCGAL and pgRouting.  So my boost total foot-print is about 5 MB which isn't too bad.

**Comment by jakob** [comment]
@robe2 thanks for your help! Are your full build scripts published somewhere?

**Comment by cvvergara** [comment]
@jakob 
I know she will be out for some conferences, but we use this scripts on Jenkins to test Windows in the repository:
https://github.com/pgRouting/pgrouting/tree/master/tools/winnie
I must mention the scripts don't do the testing of the newly added PgTap tests.
To test linux we do it on travis:
https://github.com/pgRouting/pgrouting/tree/master/tools/travis

**Comment by cvvergara** [comment]
Forgot to mention, a patch 2.2.1 might be coming out soon, so what if....
You make the scripts you need and we can add them to a directory into the pgRouting tools directory.

**Comment by jakob** [comment]
@cvvergara I'm not sure I understand. Are you suggesting the scripts that would build pgrouting for Postgres.app should be in the pgRouting repository?

**Comment by cvvergara** [comment]
@jakob 
"should" is not what I mean. 
 In tools, I have scripts that I use as a guide to do things that are done not very often, but to figure out how to do them was time consuming.
Was just a "what if".

**Comment by robe2** [comment]
@jasiek , the winnie scripts that @cvvergara pointed at are used by the PostGIS windows build bot to build the pgRouting packages.  So windows builds are done even for pre-releases for any windows user to test out and then I use these binaries as part of the PostGIS windows packages.  

In the postgis.net repo - there is similar the windows build bot uses the scripts in postgis repo - 

https://trac.osgeo.org/postgis/browser/tags/2.2.2/ci/winnie

For building postgis with sfcgal (although neither of these scripts include the cgal/boost compile but still might be useful)

**Comment by indie21** [comment]
so , pgroute will be supported soon ?

**Comment by vnnw** [comment]
+1

**Comment by chriszrc** [comment]
Seems like people are using homebrew to get around this issue. Can postgres app use the homebrew builds of pgrouting? Or should users who need pgrouting just install postgres with homebrew altogether?

**Comment by tbussmann** [comment]
As with most extensions it is not to hard to build them against the PostgresApp distribution. If you are comfortable with homebrew to provide the dependencies, you can roughly follow the following process to get pgrouting running:
```
brew install cmake boost cgal gmp
curl -LO https://github.com/pgRouting/pgrouting/releases/download/v2.6.2/pgrouting-2.6.2.tar.gz
tar xzf pgrouting-2.6.2.tar.gz
cd pgrouting-2.6.2
mkdir build
cd build
cmake  ..
make
make install
psql -c "CREATE EXTENSION postgis"
psql -c "CREATE EXTENSION pgrouting"
psql -c "SELECT version FROM pgr_version();"
```
Caveats:
* make sure the proper `pg_control` is in the path, if you follow the [installation instructions](https://postgresapp.com/documentation/install.html) this will be the one in the `latest` symlink which points to `11` currently
* due to a little error in the lastest releases (2019-02-14) at present building extensions does only work against pg11. This will be fixed soon, see #496 
* due to a bug in the CMake file of pgrouting, the linking will fail. I'll provide a patch upstream - so far use ``cmake -DPOSTGRESQL_EXECUTABLE=`pg_config --bindir`/postgres ..`` instead of `cmake ..`

**Comment by cvvergara** [comment]
@tbussmann 

For pgRouting V2.x
```
brew install cmake boost
```

For pgRouting V3.0 (plan of release date is on september 2019) it will be
```
brew install cmake boost
```
PS I will be making a PR soon to develop branch where cgal & gmp will not be needed.

**Comment by tbussmann** [comment]
Update: `pgrouting` does come bundled with Postgres.App since v2.6.4 (for PostgreSQL 15 and 16) - you simply can run `CREATE EXTENSION pgrouting CASCADE;` when connected to your database to install it.
