### ISSUE TITLE
Error when starting postgres.app

### ISSUE THREAD

**Issue by DanqingZ** [PostgresApp/PostgresApp#291]
Hi all, I am having some trouble installing postgres.app

I have been struggling with postgres,postgis and pgrouting for a long time on my computer, so I guess I have messed up a lot of things.

I tried to kill the PID according to this post: http://stackoverflow.com/questions/12028037/postgres-app-could-not-start-on-port-5432

And I think I have killed the process, for 
danqing0703@Danqings-MBP:~/Library$ ps auxw | grep post
danqing0703     22445   0.0  0.0  2432772    648 s001  S+    9:46PM   0:00.00 grep post

However, I still cannot start the postgresapp server. And still get the following bugs...What should I do ?

LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
 

This is what I get open the psql terminal:
danqing0703@Danqings-MBP:~$ '/Applications/Postgres.app/Contents/Versions/9.4/bin'/psql -p5432
psql: could not connect to server: Connection refused
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
danqing0703@Danqings-MBP:~$

**Comment by jakob** [comment]
Please follow these instructions to remove other Postgresql installs first:
http://postgresapp.com/documentation/remove.html
