### ISSUE TITLE
address_standardizer

### ISSUE THREAD

**Issue by brad-decker** [PostgresApp/PostgresApp#292]
How can i install the Postgis scripts to create the Address standardizer extension?

**Comment by jakob** [comment]
Installing PostGIS for the current database is pretty easy:
```sql
CREATE EXTENSION postgis;
```

However, Postgres.app doesn't bundle the address sanitizer, so you'll need to compile it yourself. Make sure that path is set up correctly (`which pg_config` should return `/Applications/Postgres.app/Contents/Versions/9.4/bin/pg_config`). Then you should be able to compile the extension.

**Comment by brad-decker** [comment]
Thanks!
