### ISSUE TITLE
psql: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [PostgresApp/PostgresApp#294]
Hi,

I am trying to run psql -h localhost however I get the following response:

psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

**Comment by kaiynne** [comment]
Have you tried explicitly calling it?

try:

*/Applications/Postgres.app/Contents/Versions/9.4/bin/psql*

You can test if you are calling the right version of psql by typing:

which psql

most likely you are calling /usr/local/bin/psql which is the default
location in OS X.

You can fix this by updating your bash file so your shell knows where to
look

See here: http://postgresapp.com/documentation/cli-tools.html



*Kain Warwick*
Managing Director
0404446925
blueshyft.com.au
*blueshyft*
Pier 8/9
Level 4, 23 Hickson Rd.
Millers Point, NSW 2000

**Comment by Dean-Christian-Armada** [comment]
<img width="1280" alt="screen shot 2015-11-29 at 1 52 45 pm" src="https://cloud.githubusercontent.com/assets/9837087/11455556/88ff7462-96a0-11e5-8339-17684551935c.png">

Unfortunately it did not work

**Comment by kaiynne** [comment]
Looking at your screenshot there it does not appear that you have
Postgres.app running.

You should have an elephant icon in the menu bar. see image here:

[image: Inline images 1]

I just realised I somehow have two elephant icons in my menu bar... One is
evernote, you are looking for the one second from the left.

You need to make sure to drag Postgres.app into your applications folder
and then run it from there.

Let me know how that goes?

*Kain Warwick*
Managing Director
0404446925
blueshyft.com.au
*blueshyft*
Pier 8/9
Level 4, 23 Hickson Rd.
Millers Point, NSW 2000

**Comment by Dean-Christian-Armada** [comment]
Hi

problem solved, I just reinstalled it, seems like a conflict occurred when I tried installing postgres with homebrew as well
