### ISSUE TITLE
Fixing documentation?

### ISSUE THREAD

**Issue by dret** [PostgresApp/PostgresApp#297]
is the documentation included? i could not find it.
the issue is that http://postgresapp.com/documentation/configuration-python.html probably should be fixed to say ``"USER": "[YOUR_USER_NAME]"`` instead of ``"USER": ""``.
i just started playing around with postgresapp and postico and everything seems to work after setting the ``USER`` as mentioned above.

**Comment by jakob** [comment]
The docs are part of the website, and they live in a different repository:
https://github.com/PostgresApp/postgresapp.github.io

**Comment by jakob** [comment]
Anyway, I just updated the instructions: https://github.com/PostgresApp/postgresapp.github.io/commit/96141d5550c21939370f2f81a0d78413b689c7de

Thanks for reporting this!

**Comment by dret** [comment]
On 2015-12-17 04:07, Jakob Egger wrote:
> Anyway, I just updated the instructions:
> PostgresApp/postgresapp.github.io@96141d5
> <https://github.com/PostgresApp/postgresapp.github.io/commit/96141d5550c21939370f2f81a0d78413b689c7de>
> Thanks for reporting this!

thanks for the update!
