### ISSUE TITLE
psql command runs at startup of every new Terminal window, even after uninstall

### ISSUE THREAD

**Issue by eric-brechemier** [PostgresApp/PostgresApp#302]
The `psql` command runs every time I open a new terminal. It ran successfully while Postgres.App was running, and now results in the following error after uninstalling it.

```
$ '/Applications/Postgres.app/Contents/Versions/9.5/bin'/psql -p5432
-bash: /Applications/Postgres.app/Contents/Versions/9.5/bin/psql: No such file or directory
```

Where does this command run from?

**Comment by jakob** [comment]
Postgres.app runs this command only when you select "Open psql" from the menu. It seems that for some reason, on your computer, Terminal seems to store this command somewhere and execute it again and again. Did you try quitting Terminal.app or restarting your computer?

**Comment by eric-brechemier** [comment]
> Postgres.app runs this command only when you select "Open psql" from the menu.

OK.

> It seems that for some reason, on your computer, Terminal seems to store this command somewhere and execute it again and again.

Any idea where? How does "Open psql" trigger the execution? What's changed?

> Did you try quitting Terminal.app or restarting your computer?

I will avoid it as long as I can because I currently have 31 Terminal windows open for various parts of the project I am working on, as well as 3 different documents opened in Preview.

**Comment by jakob** [comment]
Try running the following command in Terminal:

    osascript -e 'tell application "Terminal" to do script ""'

Maybe that gets Terminal back to normal.

**Comment by eric-brechemier** [comment]
> osascript -e 'tell application "Terminal" to do script ""'

That shall do.

Some of my existing Terminal windows still open new Terminal windows running `psql` but all the Terminal windows created with this command now open new Terminal windows without running `psql`.

Thanks for your support.

**Comment by jakob** [comment]
I'm pretty sure this is a bug in Terminal. I'll report it to Apple.

**Comment by jakob** [comment]
Apple confirmed the bug. Let's hope they fix it.

**Comment by eric-brechemier** [comment]
Wow, thanks for reporting it upstream.
