### ISSUE TITLE
PostgresApp hosed Psycopg2

### ISSUE THREAD

**Issue by ajilius** [PostgresApp/PostgresApp#303]
We just upgraded a machine to PostgresApp 9.5.

This is a developer workstation, with Python 3.5 and Psycopg2.

Now we're getting an application exception:

Library not loaded: /Applications/Postgres.app/Contents/Versions/9.4/lib/libssl.1.0.0.dylib

The first question in mind is why PostgresApp carries the Version information, as this is an application bundle, not a general purpose directory. And being OSX, users expect to upgrade by simply dragging the new program into the Applications folder.

The second question is, what is the best way to deal with this problem? I'd like to avoid reinstallation of Psycopg2 if possible.

**Comment by jakob** [comment]
Minor version upgrades (eg. 9.4.4 to 9.4.5) work as you expect. 

However, major PostgreSQL version upgrades (eg. 9.4 to 9.5) require that you recompile everything that links against binaries inside Postgres.app.

If you don't want to reinstall Psycopg2, just keep using the 9.4 branch of Postgres.app. I will continue making new builds with the latest versions of PostgreSQL 9.3, 9.4 and 9.5.

A long term solution might be to include multiple versions of PostgreSQL inside the app package, but that's a bigger project.

**Comment by ajilius** [comment]
Thank you for the explanation, Jakob. It makes sense to leave things the way they are.

It isn't a PostgresApp problem, but as much as I like PostgreSQL, I do miss the simplicity of in-place upgrades between versions of SQL Server :)
