### ISSUE TITLE
Can't change data directory in preferences

### ISSUE THREAD

**Issue by pbassut** [PostgresApp/PostgresApp#304]
What happens is that when I change it(either by typing it in or choosing a directory) and restart the application, it goes back to the default.
I'm assuming the settings are saved upon closing the dialog(when I open it up again my settings are still there).

I'm using El Capitan.
I could make an youtube video or something to show the issue.

**Comment by jakob** [comment]
Can you try hitting enter after editing the text field?

**Comment by pbassut** [comment]
Just tried it. Pressed it many times and still nothing.
Does it work with you?

**Comment by jakob** [comment]
Yes it does. What does `defaults read com.postgresapp.Postgres` say?

You can also try setting the data directory from Terminal:
```bash
defaults write com.postgresapp.Postgres DataDirectory95 "/path/to/datadir"
```

(It needs to be an absolute path)

**Comment by jakob** [comment]
Also, if you choose a directory that's not valid (eg. a data directory of a previous version of PostgreSQL), Postgres.app reverts to the default directory.

**Comment by pbassut** [comment]
```{
    DataDirectory95 = "/Users/patrickbassut/Library/Application Support/Postgres/var-9.5";
    NSNavLastRootDirectory = "/usr/local/var/postgres";
    NSNavPanelExpandedSizeForOpenMode = "{712, 448}";
}```

**Comment by pbassut** [comment]
I'm choosing a data directory of a postgres instance I already had installed before finding out about Postgress.app.

It looks like it does a lot a magic behind the scenes though. Notifying the user would be great. No?

**Comment by pbassut** [comment]
Looks like it's rolling back to the default one.

```{
    DataDirectory95 = "/Users/patrickbassut/Library/Application Support/Postgres/var-9.5";
    NSNavLastRootDirectory = "/usr/local/var/postgres";
    NSNavPanelExpandedSizeForOpenMode = "{712, 448}";
}
```

**Comment by jakob** [comment]
You are right, it would be better to show an error instead of rolling back to the default data directory.

You can download an older version of Postgres.app if you want to access your old data dir. You need the same major version as the PostgreSQL server that created the data dir. Check the file PG_VERSION inside the data dir to see what version of PostgreSQL was used to create it. Then download the appropriate version from here: https://github.com/PostgresApp/PostgresApp/releases
