### ISSUE TITLE
Unable to login to database (postgres).

### ISSUE THREAD

**Issue by MartyMcFly42** [PostgresApp/PostgresApp#306]
Hello. I'm using Poker Tracker 4 app which uses the functions of Postgres to some degree. It was all fine and working for a year, when suddenly, few hours ago, **I had a power outage**. When the electricity was restored and I got the PC running again, I had few errors all over the app spectrum.

Bear with me please.

* I couldn't start PokerStars app (would click on .exe file, it wouldn't do anything). So I've uninstalled it, installed it again and now I can run it. But cannot connect to the server (the "connecting bar" is endlessly running).
* Poker Tracker - so it gives me error:
*"Unable to login to database (postgres). Reason: could not translate host name "localhost" to address: Unknown server error"*
in this error message, I can click on CONFIGURE DEFAULTS or CANCEL. So CD gives me:
(I suppose) standard window with this info:
Server: localhost
Port 5432
Database User: postgres
Password: (here's the default pass, you know which one)

When I click on CONNECT, it gives me error "Unable to connect to this database. Please check the configuration"

I've tried:
1)Reinstall all three, PokerStars, Poker Tracker 4 and Postgress, having all in latest version (postgresql-9.5.0-1-windows-x64.exe)
2)Go to services.msc and restart the service
3)Restart the computer
4)Go to event viewer:

Event viewer gives me certain WARNING, source - User Profile Service:
>Windows detected your registry file is still in use by other applications or services. The file will be unloaded now. The applications or services that hold your registry file may not function properly afterwards.  

 >DETAIL - 
 2 user registry handles leaked from \Registry\User\S-1-5-21-2754011387-3914786246-3511611031-1004:
Process 2024 (\Device\HarddiskVolume2\Windows\System32\conhost.exe) has opened key \REGISTRY\USER\S-1-5-21-2754011387-3914786246-3511611031-1004\Control Panel\International
Process 2080 (\Device\HarddiskVolume2\Program Files\PostgreSQL\9.0\bin\postgres.exe) has opened key \REGISTRY\USER\S-1-5-21-2754011387-3914786246-3511611031-1004\Control Panel\International

So I suppose the reason is the blackout, something is wrong in my registry or something like that. The question I ask you guys, what to do, how to fix it?

**Comment by jakob** [comment]
Hey,

Postgres.app is a PostgreSQL distribution for Mac OS X. It doesn't seem like you are using Postgres.app. If you need help with PostgreSQL on other platforms I recommend to look at the available options at http://www.postgresql.org/support/.

That being said, the error message `could not translate host name "localhost" to address` sounds like a problem with name resolution on your machine. A common reason for this is when people modify their [hosts file](https://en.wikipedia.org/wiki/Hosts_%28file%29) and break it.

Anyway, apart from this tip I unfortunately can't offer any assistance.

**Comment by MartyMcFly42** [comment]
OK, got platforms mixed. Will try to use your help to solve my issue.
