### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by F1LT3R** [PostgresApp/PostgresApp#307]
On the page: http://postgresapp.com/ you have a broken download link for PostgreSQL 9.4.5.

Clicking the middle button in this picture just refreshes the page.

![screen shot 2016-01-21 at 10 08 43 am](https://cloud.githubusercontent.com/assets/1218446/12484187/216af29e-c027-11e5-865d-cc952340b18d.png)

**Comment by peterhurford** [comment]
In the meantime, you can download the version from the GitHub releases: https://github.com/PostgresApp/PostgresApp/releases

**Comment by jakob** [comment]
Hey,

thanks for telling me about this, and sorry for ignoring this issue so long -- I completely forgot about this.

The link should work again now, apologies for the inconvenience.

**Comment by Runehm** [comment]
Hi Jakob, 

At the moment none of the download links are working?

it seems to be a problem with https://github-cloud.s3.amazonaws.com

can you look into it please

**Comment by jakob** [comment]
@Runehm The download links work fine for me.

If you are having troubles, please open a new issue, and tell me what browser and what version of OS X you are using.

**Comment by Runehm** [comment]
@jakob Thanks for replying. I tried again on a different wifi and it works now. Sorry for the mistake.
