### ISSUE TITLE
Support for Luajit in OSX

### ISSUE THREAD

**Issue by stuta** [PostgresApp/PostgresApp#308]
Hello.

PL/Lua works well with normal Lua 5.1, but it crashes postgres with Luajit.
https://github.com/pllua/pllua/issues/18#issuecomment-174433373

http://luajit.org/install.html

If you're building a 64 bit application on OSX which links directly or indirectly against LuaJIT, you need to link your main executable with these flags:
-pagezero_size 10000 -image_base 100000000

Is it possible to add these linker flags?
- Pasi Mankinen

**Comment by jakob** [comment]
I don't have a clue what these options do and what effect they will have on the rest of Postgres.app. I'd love to hear more about these options and what they do.

Also, I'm not sure where to set these options -- Postgres.app contains dozens of binaries. I assume that these options actually only need to be set for the postgres server binary.

I assume that in order to set these options you probably need to add some params to the configure script here:
https://github.com/PostgresApp/PostgresApp/blob/master/src/makefile#L56

Unfortunately I don't have time to play around with this right now, so I'd love to get input from people who know more about this than I do.

**Comment by stuta** [comment]
I tried to add  -pagezero_size 10000 -image_base 100000000 to xcode other linker flags, bit it did not seem to help.

Then I tried to add LDFLAGS to makefile: 
LDFLAGS:=$(LDFLAGS) -pagezero_size 10000 -image_base 100000000
export LDFLAGS CFLAGS CXXFLAGS MACOSX_DEPLOYMENT_TARGET

Unfortunately my build fails with ERROR: `jade' is missing on your system. How can I build without postgre docs?

**Comment by stuta** [comment]
Postres app is just user interface and postgresql is the one that should have correct linker flags. There are extra info in postgre ./configure --help:
  LDFLAGS_EX  extra linker flags for linking executables only

I tried with homebrew and changed /usr/local/Library/Formula/postgresql.rb:
ENV.prepend "LDFLAGS_EX", "-pagezero_size 10000 -image_base 100000000"

Then I installed postgre with homebrew and installed PL/Lua with luajit and everything works.

So all what we need is to set LDFLAGS_EX="-pagezero_size 10000 -image_base 100000000".

**Comment by kingbuzzman** [comment]
@stuta did you get anywhere with the 

> ERROR: `jade' is missing on your system

 issue?

**Comment by jakob** [comment]
@kingbuzzman `jade` is required for building PostgreSQL docs. You can fix this in two ways:

1. Install jade on your Mac
2. Don't build docs.


## Installing Jade
See the *How To Build* section in the [README](https://github.com/PostgresApp/PostgresApp/blob/master/README.md). 

If you use Macports, the following command installs everything you need to build docs:
```bash
sudo port install docbook-dsssl docbook-sgml-4.2 docbook-xml-4.2 docbook-xsl libxslt openjade opensp
```

I don't think homebrew has all the necessary packages.

## Not building docs
Change the following lines in the makefile:
```bash
make -C "postgresql-$(POSTGRES_VERSION)" world
make -C "postgresql-$(POSTGRES_VERSION)" install-world
```
to 
```bash
make -C "postgresql-$(POSTGRES_VERSION)" all contrib
make -C "postgresql-$(POSTGRES_VERSION)" install
```
Then PostgreSQL should be built without docs. I haven't actually tried this, but I think it should work.

**Comment by stuta** [comment]
Thanks! Currently I don't need to use Luajit inside Postgre but this will be helpful in the future. Another option is new gc64 mode of Luajit that does not need "-pagezero_size 10000 -image_base 100000000".

**Comment by jakob** [comment]
If I understood correctly:
 - no-one can tell me what other effects `-pagezero_size 10000 -image_base 100000000` might have
 - adding these options is not required for recent versions of Luajit

So I've decided to not add these compilation options, and I'm closing this issue.

**Comment by bo01ean** [comment]
I was able to get around:

> ERROR: `jade' is missing on your system

by:

```
brew tap petere/sgml
brew install docbook docbook-dsssl docbook-sgml docbook-xsl openjade
```

And adding /usr/local/bin to PATH in the makefile:

https://github.com/bo01ean/PostgresApp/commit/5855b0460fd372f29bd6c9f6877479aaabab7109#diff-210e3527f52409b84fd1c50fcea0df2fR49


PR coming soon.
