### ISSUE TITLE
Fail to start the version 9.5.0.0 on Mac OS 10.7.5/10.8.5

### ISSUE THREAD

**Issue by dioobr** [PostgresApp/PostgresApp#310]
When trying to start for the first time, the following error appears:

**Could not initialize database cluster.
dyld: Library not loaded: /usr/lib/liblzma.5.dylib
  Referenced from: /Applications/Postgres.app/Contents/Versions/9.5/lib/libxml2.2.dylib
  Reason: image not found
no data was returned by command ""/Applications/Postgres.app/Contents/Versions/9.5/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/Applications/Postgres.app/Contents/Versions/9.5/bin/initdb".
Check your installation.**

Mac OS Lion 10.7.5
PostgresApp 9.5.0.0

**Comment by dioobr** [comment]
I found the liblzma.5.dylib file in VLC library and copied to /usr/lib/ directory
[liblzma.5.dylib.zip](https://github.com/PostgresApp/PostgresApp/files/110993/liblzma.5.dylib.zip)
. Postgresapp 9.5.0.0 works fine now.

**Comment by mactyr** [comment]
I had this same issue with PostgresApp 9.5.0.0 on OS X 10.**8**.5. I already had xz installed via macports, so I was able to work around the problem by doing:

```
sudo ln -s /opt/local/lib/liblzma.5.dylib /usr/lib/liblzma.5.dylib
```

**Comment by jakob** [comment]
Thanks everyone for posting this and the workarounds!

I've built the latest version (9.5.1.0) on an older OS X to avoid this issue. It should work without this workaround now. Could you try it and confirm?

https://github.com/PostgresApp/PostgresApp/releases

**Comment by dioobr** [comment]
Hi jakob, It's working perfectly on Lion 10.7.5. Thank you!

**Comment by mactyr** [comment]
Yep, working on 10.8.5 now too. Thanks jakob.
