### ISSUE TITLE
Fails to load plv8.so for Postgres 9.4.6

### ISSUE THREAD

**Issue by zar1** [PostgresApp/PostgresApp#311]
I'm running on OSX El Capitan and Postgres.app 9.4.6. I get the following error when attempting to load plv8:

```
$ psql
# create extension plv8;
ERROR:  could not load library "/Applications/Postgres.app/Contents/Versions/9.4/lib/postgresql/plv8.so": dlopen(/Applications/Postgres.app/Contents/Versions/9.4/lib/postgresql/plv8.so, 10): Symbol not found: _uint32_hash
  Referenced from: /Applications/Postgres.app/Contents/Versions/9.4/lib/postgresql/plv8.so
  Expected in: /Applications/Postgres.app/Contents/Versions/9.4/bin/postgres
 in /Applications/Postgres.app/Contents/Versions/9.4/lib/postgresql/plv8.so
```

If it's relevant, I downgraded to 9.4.6 from 9.5.1

**Comment by zar1** [comment]
In 9.4.5, plv8.so loads as expected, so it looks like 9.4.6 caused the issue.

**Comment by jakob** [comment]
Thanks for this bug report. I think I've found the problem -- there was an issue in the makefile I use for building.

Please download the new build here:
https://github.com/PostgresApp/PostgresApp/releases/tag/9.4.6.1


... and let me know if it fixes the issue!

**Comment by zar1** [comment]
That fixed it for me. Thank you very much!
