### ISSUE TITLE
Postgresql9.5.1 startup failed in OS X 10.11.3 EI Caption

### ISSUE THREAD

**Issue by Troland** [PostgresApp/PostgresApp#314]
I just install postgresql 9.5.1 and i can't startup the postgresql server.
My operating system is OS X 10.11.3 EI Caption.
The error message displayed:

    LOG:  could not bind IPv4 socket: Can't assign requested address
    HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    LOG:  could not bind IPv6 socket: Can't assign requested address
    HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    WARNING:  could not create listen socket for "localhost"
    FATAL:  could not create any TCP/IP sockets
    LOG:  could not bind IPv4 socket: Can't assign requested address
    HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    LOG:  could not bind IPv6 socket: Can't assign requested address
    HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    WARNING:  could not create listen socket for "localhost"
    FATAL:  could not create any TCP/IP sockets
    LOG:  could not bind IPv4 socket: Can't assign requested address
    HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    LOG:  could not bind IPv6 socket: Can't assign requested address
    HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
    WARNING:  could not create listen socket for "localhost"
    FATAL:  could not create any TCP/IP sockets

I don't remember if i install any dev tools or kernel extensions.
Any help is appreciated, thanks

**Comment by jakob** [comment]
Could you  try running `ping localhost` in the Terminal and show the output?

Then run `cat /etc/hosts` and show the output.

**Comment by Troland** [comment]
It's really weird that when i run `ping localhost` it displayed:

    PING localhost.dhcp (218.85.65.150): 56 data bytes
    64 bytes from 218.85.65.150: icmp_seq=0 ttl=56 time=7.668 ms
    64 bytes from 218.85.65.150: icmp_seq=1 ttl=56 time=9.163 ms
    64 bytes from 218.85.65.150: icmp_seq=2 ttl=56 time=8.805 ms

while when i shutdown my wifi it displayed:

    PING localhost (127.0.0.1): 56 data bytes
    64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.052 ms
    64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.125 ms
    64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.137 ms
    64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.076 ms

run `cat /etc/hosts` shows:

    ##
    # Host Database
    #
    # localhost is used to configure the loopback interface
    # when the system is booting.  Do not change this entry.
    ##
    127.0.0.1	localhost
    255.255.255.255	broadcasthost
    ::1             localhost

**Comment by jakob** [comment]
OK, this looks like it stems from a misconfigured DHCP server. Presumably your DHCP server has the search domain "dhcp" configured (check in network settings, under "DNS"), and then it returns an entry for localhost.dhcp. It's really odd that this overrides the entry from /etc/hosts. Are you connected to a VPN?

In any case, it looks like something fishy is going on. I wouldn't trust the wifi network you are connecting to -- if possible, talk to the network administrator.

I'm not sure I can provide any additional help, since this is far beyond my area of expertise. Please also keep that in mind with regard to my advise above -- I am not sure how accurate my suggestions above are.

**Comment by Troland** [comment]
Thanks jakob, it's the condition that i use a wifi router as a relay for the weak wifi signal, and maybe someday some strange things happened and localhost point to my public ip address.

But when i take my lap downstair, it fixed....
