### ISSUE TITLE
FATAL:  could not open lock file "/tmp/.s.PGSQL.5432.lock": Permission denied

### ISSUE THREAD

**Issue by nawrasbaghdadi** [PostgresApp/PostgresApp#315]
After installing the PostgresApp it wont run showing this error
FATAL:  could not open lock file "/tmp/.s.PGSQL.5432.lock": Permission denied

**Comment by jakob** [comment]
Hm... Maybe you have a different server running? Quit Postgres.app, then chech if you have any processes named 'postgres' running. If you do, uninstall the other postgresql installation (see docs), then restart your Mac.
If not, try to delete the lockfile and start Postgres.app again.

**Comment by nawrasbaghdadi** [comment]
thanks it works , i just had to restart my mac

**Comment by ryan-walsh-forte** [comment]
Restarting was necessary for me, too. Thanks.

**Comment by KyryloPikhno** [comment]
hmm, I have the same problem. I tried deleting this file, restarting the postgres service and rebooting my Mac, but nothing helped. I've been trying to fix this for a long time, I need to sleep, I'll try tomorrow again :)
