### ISSUE TITLE
compile with TRUST_STRXFRM

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#318]
In PostgreSQL 9.5.2 there was the new-to-9.5 feature "abbreviated keys for string-sorting" disabled for safety reasons (possible index corruption). See [Release announcement](http://www.postgresql.org/about/news/1656/) and [Release notes](http://www.postgresql.org/docs/9.5/static/release-9-5-2.html). The impact of this issue is detailed in the [Wiki](https://wiki.postgresql.org/wiki/Abbreviated_keys_glibc_issue) This change may degrade the performance significantly but ensures correct results when using indexes. You are encouraged to REINDEX affected indexes from 9.5.0 and 9.5.1. 

However - with PostgresApp on OSX we have quite a controlled environment that has the advantage (in this case) of broken UTF8 locales. All collations of UTF-8 locales map to 'C' as you can see by issuing `ls -lah /usr/share/locale/*.UTF-8/LC_COLLATE` (see also Issue #216) This leads to the conclusion that OS X effectively is not affected by the underlying [glibc bug](https://bugzilla.redhat.com/show_bug.cgi?id=1320356) whereby strcoll() ordering does not match strxfrm() ordering. I confirmed that again by running the test-suites and samples provided in the RedHat BugZilla. Furthermore, OSX does not seem to use glibc at all for libc. The PostgreSQL [commit](http://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=3df9c374e279db37b00cd9c86219471d0cdaa97c) that disables the abbreviated keys feature for 9.5.2 does indicate that in environments that are not affected by the bug, it is possible to compile with TRUST_STRXFRM flag to reenable the feature. Please consider doing so.

**Comment by tbussmann** [comment]
oh - I just see the following comment:
> Moreover, Darwin's strxfrm() implementations is known to not effectively concentrate a significant amount of entropy from the original string in earlier transformed blobs.
so it may be that the abbreviation feature is not used (aborted) on OS X anyhow. This first needs to be verified - TRUST_STRXFRM would effectively have no effect in that case.

**Comment by jakob** [comment]
Thanks for your suggestions, but since it isn't clear that this will improve anything, I'll leave it turned off. I hope that someone works on merging Palle's ICU patch at some point, then all this will become irrelevant...
