### ISSUE TITLE
man psql does not find man pages

### ISSUE THREAD

**Issue by stantonk** [PostgresApp/PostgresApp#319]
My path is configured as the docs describe:

```
$  echo $PATH | egrep -o "\/Applications\/Postgres.app\/Contents\/Versions\/latest\/bin"
/Applications/Postgres.app/Contents/Versions/latest/bin
```

yet:

```
$  man psql
No manual entry for psql
```

**Comment by jakob** [comment]
Do you have any other environment variables like manpath defined?

**Comment by jakob** [comment]
Since `man psql` works for me, and I got response for two weeks, I'm closing this issue. Feel free to reopen anytime if you have any additional information to share.

**Comment by tbussmann** [comment]
your grep did not reveal the end of the path, you have configured. When experimenting with `path_helper`  I experienced a similar issue when ending the path with an `/` - see (https://github.com/PostgresApp/PostgresApp/issues/259#issuecomment-112159644)
