### ISSUE TITLE
No pgcommon?

### ISSUE THREAD

**Issue by guyrixon** [PostgresApp/PostgresApp#321]
I have installed Postgres.app 9.5 and made it work. I now needs to compile and install an extension. This fails because libpgcommon is missing. How can I get this library? Should it have been included?

**Comment by jakob** [comment]
As far as I understand, libpgcommon is a static library that contains code shared between the frontend and backend. It's only used during building PostgreSQL, and not part of standard distributions.

If your extension depends on this, you probably need to build PostgreSQL from source. It might be worth checking if Macports or Homebrew include this library, but to be honest I doubt it.

What extension are you trying to build?

**Comment by guyrixon** [comment]
I need q3c, the spatial-indexing extension for astronomy.

I’ll install the non-app postgres from source. It’s a little less convenient than the app but I can manage.

Thanks for getting back so quickly,
Guy
