### ISSUE TITLE
Role “user“ doesn't exist

### ISSUE THREAD

**Issue by barjacks** [PostgresApp/PostgresApp#324]
I am new to psql and am trying to set it up using the http://postgresapp.com on my Mac. After installation and opening psql this is the message I get: 

> Last login: Sat May 21 07:10:21 on ttys000
> '/Applications/Postgres.app/Contents/Versions/9.5/bin'/psql -p5432
> MacBook-Pro:~ MYUSERNAME$ '/Applications/Postgres.app/Contents/Versions/9.5/bin'/psql -p5432
> psql: FATAL:  role "MYUSERNAME" does not exist

Using the trouble shooting section http://postgresapp.com/documentation/troubleshooting.html I used to the server manual for more information on the issue. This is the result:

> MacBook-Pro:~ MYUSERNAME$ /Applications/Postgres.app/Contents/Versions/9.5/bin/postgres -D "/Users/MYUSERNAME/Library/Application Support/Postgres/var-9.5"
> FATAL:  lock file "postmaster.pid" already exists
> HINT:  Is another postmaster (PID 1813) running in data directory "/Users/MYUSERNAME/Library/Application Support/Postgres/var-9.5"?

Has anybody got any suggestions how I could proceed?

**Comment by jakob** [comment]
This can happen when the postgresql server didnt shut down properly.

Open activity monitor, check that no process named postgres is running (use the search field). If there are any processes named postgres, quit the one with the lowest pid until there are none left.

Then open the postgres data directory, and delete the postmaster.pid file

**Comment by barjacks** [comment]
Thanks a lot Jakob, your help is very much appreciated. But the problem still persists:

1. I opened activity monitor and deleted all the processes named postgres, starting with the ones with the lowest PID.
2. I then looked for the postgres data directory under /Users/USERNAME/Library/Application Support/Postgres/var-9.5 for the postmaster.pid. This is file, however, disappears as soon as I kill the processes above.
3. The I restart postgres and I get the following message:

Last login: Sun May 22 17:50:57 on ttys002
'/Applications/Postgres.app/Contents/Versions/9.5/bin'/psql -p5432
MacBook-Pro:~ USERNAME$ '/Applications/Postgres.app/Contents/Versions/9.5/bin'/psql -p5432
psql: FATAL:  role "USERNAME" does not exist
MacBook-Pro:~ USERNAME$ 

(I tried deleting the programme after repeating the above mentioned steps and reinstalling it, and the same thing happens.)

I would be really grateful for any further advice you have,

Kind regards,
Barnaby

**Comment by jakob** [comment]
Hi!

Postgres.app creates a role with the same name as your username when you first start it.

When you change your system user name, those names don't match any more.

The easiest way to fix this, if you don't have any data yet in the database, is to quit Postgres.app and delete the data directory, then start Postgres.app again.

You can also specify the user name when connecting, eg.

    psql -U postgres

and create a new user with the createuser command

    createuser -U postgres NEWUSERNAME

**Comment by barjacks** [comment]
Thanks, that worked nicely!

**Comment by guyrandalf** [comment]
@jakob You can save a life. You have just saved mine
