### ISSUE TITLE
Adding pguri extension to Postgresapp

### ISSUE THREAD

**Issue by natoinet** [PostgresApp/PostgresApp#326]
Hello,

I'm trying to add pguri extension to Postgresapp. Following the README at https://github.com/petere/pguri, when I do:

    make PG_CONFIG=/Applications/Postgres.app/Contents/Versions/latest/bin/pg_config

I get the following error:

    Makefile:10: liburiparser not registed with pkg-config, build might fail
    Package liburiparser was not found in the pkg-config search path.
    Perhaps you should add the directory containing `liburiparser.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'liburiparser' found
    gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument  -mmacosx-version-min=10.7   -I. -I./ -I/Applications/Postgres.app/Contents/Versions/9.5/include/postgresql/server -I/Applications/Postgres.app/Contents/Versions/9.5/include/postgresql/internal -I/Applications/Postgres.app/Contents/Versions/9.5/include/libxml2  -I/Applications/Postgres.app/Contents/Versions/9.5/include  -c -o uri.o uri.c
    uri.c:10:10: fatal error: 'uriparser/Uri.h' file not found
    #include <uriparser/Uri.h>
             ^
    1 error generated.
    make: *** [uri.o] Error 1

Is it because I need to download the source code and recompile the database? D‑':
Any tutorial on how to do that?

Thanks!

**Comment by natoinet** [comment]
Sorry, that was just because uriparser was not installed. Doing the following resolved my issue:
    brew install uriparser

**Comment by jakob** [comment]
Thanks for the update! I'll close this issue for now, you can reopen it any time if you run into further trouble.
