### ISSUE TITLE
free client for beginning

### ISSUE THREAD

**Issue by Tomorax** [PostgresApp/PostgresApp#327]
Hello!
Not that I just started using the PostgresApp, I'd like a recommendation about a good Postgres client for use on iPhone our iPad.

**Comment by dijit** [comment]
I think this is out of scope for the PostgresApp maintainers, they supply a bundled server to use on macOS and the associated command line client.

iOS and GUI clients are not the goal of this project.

If you want a list of GUI clients that are available the official [PostgreSQL Wiki] has some

[PostgreSQL Wiki]: https://wiki.postgresql.org/wiki/Community_Guide_to_PostgreSQL_GUI_Tools
