### ISSUE TITLE
Tool request - pg_isready

### ISSUE THREAD

**Issue by mikesir87** [PostgresApp/PostgresApp#328]
Fantastic tool!  Would there be any possibility to have the pg_isready tool included within the app?

**Comment by jakob** [comment]
Sure! Looks like the script that copies the binaries didn't include `pg_isready`. I'm changing the script to just copy `pg*`, so `pg_isready` should be included in the next build.

In the mean time, I'm attaching a copy of the binary. Just unzip it and place it in the right directory:

```bash
mv pg_isready /Applications/Postgres.app/Contents/Versions/9.5/bin/pg_isready
```

[pg_isready.zip](https://github.com/PostgresApp/PostgresApp/files/310142/pg_isready.zip)
