### ISSUE TITLE
Initial run of Postgres.app 9.5.3 fails on El Capitan

### ISSUE THREAD

**Issue by numinasthmatic** [PostgresApp/PostgresApp#329]
OS X 10.11.5

initdb gives:
creating directory Users/pbw/Library/Application Support/Postgres/var-9.5 ... ok
creating subdirectories ... ok
selecting default max_connections ... 10
selecting default shared_buffers ... 400kB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in Users/pbw/Library/Application Support/Postgres/var-9.5/base/1 ... FATAL:  invalid value for parameter "port": ""

Same result with 9.5.2

**Comment by jakob** [comment]
Could it be that you have PGPORT set in your environment? Type `export` in Terminal to see your environment variables.

**Comment by jakob** [comment]
Please try again with the latest version of Postgres.app. If it fails again, please re-open this issue.
