### ISSUE TITLE
Installing multiple versions on one machine

### ISSUE THREAD

**Issue by eagle-r** [PostgresApp/PostgresApp#330]
As a developer I need different projects to run with different versions of Postgres and I'm looking for a way to have multiple versions of Postgres.app to be installed on one machine. They don't have to be able to run at the same time (although that would be nice and would just require a different port for each version).

Looking at the app package, it seems that it should work since the data folders are kept version specific.

I tried renaming the apps to include the version numbers but then got an error message saying that it had to be called Postgres.

**Comment by jakob** [comment]
We are currently working on a completely new version of Postgres.app which allows running multiple versions simultaneously. We hope to release it in autumn.

Right now, you can just switch between multiple versions sequentially. When you open a different version of Postgres.app, it'll offer to rename the app automatically. The old one will also be renamed accordingly.

Hope this helps!

**Comment by eagle-r** [comment]
That's perfect. Thanks for the advice and I'm looking forward to the new version.

**Comment by jakob** [comment]
We've just released Postgres.app 2.0. You can now run multiple servers (with multiple versions of PostgreSQL) at the same time. See the docs for details:
https://postgresapp.com/documentation/all-versions.html
