### ISSUE TITLE
[QUESTION] How to switch to postgresql brew from postgresapp

### ISSUE THREAD

**Issue by es6Test** [PostgresApp/PostgresApp#332]
Hi can someone advise how I can switch from this to brew? I've had a lot of issues.

Is there a sequence of steps I can follow?

Do I need to remove the postgresql user also? I also removed the reference to the app in the path.

**Comment by jakob** [comment]
To switch from Postgres.app to Homebrew, follow these steps:

1. Create a dump of all your databases, using `pg_dump` or `pg_dump_all`.
2. Make sure "Start on Login" is disabled in Postgres.app preferences, then quit Postgres.app
3. Install PostgreSQL using brew
4. Restore your database using psql or pg_restore

Postgres.app doesn't create a `postgresql` user. If you have a user named `postgresql` on your system it's from a different installer.
