### ISSUE TITLE
How to use `psql` stand alone

### ISSUE THREAD

**Issue by doekman** [PostgresApp/PostgresApp#338]
I want to use `psql` stand alone. I put the binary in the `.\bin` folder, and the included libraries (libpq.5.8.dylib, libssl.1.0.0.dylib and libcrypto.1.0.0.dylib) into the `.\lib` folder. Then I used `otool -L` to check the linked libraries, and then I used `install_name_tool` to fix these like this (with the great help of [the courts of chaos](http://thecourtsofchaos.com/2013/09/16/how-to-copy-and-relink-binaries-on-osx/)):

    cd bin
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libpq.5.dylib @executable_path/../lib/libpq.5.dylib psql

    cd ../lib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libpq.5.dylib @executable_path/../lib/libpq.5.dylib -id /usr/lib/libpq.5.dylib libpq.5.8.dylib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libssl.1.0.0.dylib @executable_path/../lib/libssl.1.0.0.dylib libpq.5.8.dylib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libcrypto.1.0.0.dylib @executable_path/../lib/libcrypto.1.0.0.dylib libpq.5.8.dylib

    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libssl.1.0.0.dylib @executable_path/../lib/libssl.1.0.0.dylib -id @executable_path/../lib/libssl.1.0.0.dylib libssl.1.0.0.dylib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libcrypto.1.0.0.dylib @executable_path/../lib/libcrypto.1.0.0.dylib libssl.1.0.0.dylib

    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libcrypto.1.0.0.dylib @executable_path/../lib/libcrypto.1.0.0.dylib -id @executable_path/../lib/libcrypto.1.0.0.dylib libcrypto.1.0.0.dylib

However, it doesn't work, I still get the following error:

    dyld: lazy symbol binding failed: Symbol not found: _PQsslInUse
    ...
    Expected in: /usr/lib/libpq.5.dylib

I'm unsure if the `-id` argument is used correctly. What am I missing here? Help would be greatly appreciated.

**Comment by jakob** [comment]
I think the problem is that the path to your bundled libpq is not correct, so OS X links with the system provided libpq instead (in /usr/lib/libpq.5.dylib). The system-provided libpq doesn't have OpenSSL support, so you get the error.

I think the problem is in the first command, the path should probably be `@executable_path/../lib/libpq.5.8.dylib` instead of `@executable_path/../lib/libpq.5.dylib`

Concerning `-id`, you are using it wrong. The id of a library should be the name you reference it with, in your case `@executable_path/../lib/libpq.5.8.dylib`, not `/usr/lib/libpq.5.dylib`

**Comment by doekman** [comment]
That makes sense. Your remarks plus adding links (which I forgot somehow) make it work now! 

Thanks a lot! I will let you know when I open source the AppleScript library.

For documentation purposes, I now have this:

    cd bin
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libpq.5.dylib @executable_path/../lib/libpq.5.8.dylib psql

    cd ../lib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libpq.5.dylib @executable_path/../lib/libpq.5.dylib -id @executable_path/../lib/libpq.5.8.dylib libpq.5.8.dylib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libssl.1.0.0.dylib @executable_path/../lib/libssl.1.0.0.dylib libpq.5.8.dylib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libcrypto.1.0.0.dylib @executable_path/../lib/libcrypto.1.0.0.dylib libpq.5.8.dylib
    ln -sf libpq.5.8.dylib libpq.5.dylib
    ln -sf libpq.5.8.dylib libpq.dylib

    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libssl.1.0.0.dylib @executable_path/../lib/libssl.1.0.0.dylib -id @executable_path/../lib/libssl.1.0.0.dylib libssl.1.0.0.dylib
    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libcrypto.1.0.0.dylib @executable_path/../lib/libcrypto.1.0.0.dylib libssl.1.0.0.dylib
    ln -sf libssl.1.0.0.dylib libssl.dylib

    install_name_tool -change /Applications/Postgres.app/Contents/Versions/9.5/lib/libcrypto.1.0.0.dylib @executable_path/../lib/libcrypto.1.0.0.dylib -id @executable_path/../lib/libcrypto.1.0.0.dylib libcrypto.1.0.0.dylib
    ln -sf libcrypto.1.0.0.dylib libcrypto.dylib

**Comment by jakob** [comment]
Awesome, glad you got it working!

BTW, those links shouldn't be necessary. Just point towards `@executable_path/../lib/libpq.5.8.dylib` instead of `@executable_path/../lib/libpq.5.dylib`

**Comment by vitaly-zdanevich** [comment]
Any way to automate installing of psql only? AppleScript?
