### ISSUE TITLE
PostgresApp 9.6.0.0 on macOS Sierra 10.12 always asks to copy to Applications folder

### ISSUE THREAD

**Issue by awwx** [PostgresApp/PostgresApp#348]
Following the "Quick Installation Guide", after Postgres.app is moved by hand into the /Applications folder, on launch it always displays the message that the app needs to be in the Applications folder and asks if it copy itself there... but even if "Copy" is clicked, it continues to ask on each launch.

Maybe this is because of recent [Gatekeeper changes](https://9to5mac.com/2016/06/15/macos-sierra-gatekeeper-changes/):

> The second change is invisible to users, but limits the damage that can be done by a rogue app. Although unsigned apps will still appear to be stored in the Applications folder, macOS 10.12 actually stores them in a randomized location on your drive. This prevents repackaging attacks, where one app pretends to be another one, because the rogue app won’t be able to access the resources belonging to the real one.

A workaround appears to be to run the app from _outside_ the Applications folder (right-click and select "Open", as double-clicking no longer works for unsigned apps), allow it to copy itself, and then it works from that point.

**Comment by jakob** [comment]
What exactly do you mean with "move by hand"? Did you use `mv` in Terminal? When you move a downloaded app with the Finder, App Translocation (Path Randomisation) should be deactivated. Also, when you click "copy", Postgres.app removes the "quarantine" attribute after copying, so app translocation should definitely be disabled after clicking "copy".

I'm not sure what's going on your Mac, but as far as I understand this really shouldn't happen.

What version of macOS are you using?

**Comment by awwx** [comment]
macOS Sierra 10.12

I used "mv".

I just now confirmed that it works correctly moving the downloaded app using Finder.

I recommend that the "Quick Installation Guide" be updated to say to move the downloaded app to /Applications using the Finder.

**Comment by jakob** [comment]
OK, thanks for following up on this.

Instead of updating the Quick Installation Guide, it would probably be even better to just detect that the app is translocated, and show a more relevant error message.

@chrispysoft Can you look into this for Postgres.app 2.0?

**Comment by jakob** [comment]
We've now released Postgres.app 2.0 which shows a more relevant error message.
