### ISSUE TITLE
Configuring Path does not permanently change path

### ISSUE THREAD

**Issue by mooneyme** [PostgresApp/PostgresApp#353]
Using 
export `PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin`
does not permanently change the psql path. 

When opening a new terminal window, and typing  `man psql`, it returns `No manual entry for psql`. For each new terminal session, I need to paste in the path configuration.

What's going on?

**Comment by jakob** [comment]
You need to put that line into your .profile (or .bash_profile) file in your home directory, so it will be executed every time you open a Terminal session

**Comment by muescha** [comment]
see doc here where to put [CLI documentation](http://postgresapp.com/documentation/cli-tools.html)
