### ISSUE TITLE
Static libraries libpgcommon.a and libpgport.a are missing

### ISSUE THREAD

**Issue by pbnjay** [PostgresApp/PostgresApp#358]
Any chance of getting pg_bulkload bundled into this? I could try to set up a build environment but it would likely take me quite a bit longer than you!

https://github.com/ossc-db/pg_bulkload 

It appears to be BSD licensed (listed in meta.json). I'm happy to test or anything necessary.

**Comment by jakob** [comment]
I just tried building it, but failed :(

Unfortunately I'm to busy right now to work on this, but if someone finds out how to build it, we can either bundle it, or add instructions to the docs how to build it yourself. (depending on how many people use this tool -- I don't want to bundle stuff that only very few people use)

**Comment by pbnjay** [comment]
OK I'm guessing you hit the same errors as me - failing to find libpgcommon and libpgport (which appear to be part of libpq but not in the bundle)

**Comment by pbnjay** [comment]
Thanks for trying it out - I was finally able to get it to build, so for the almighty google I'll document it here (and just close this to make things quieter, I don't expect very many people will use this tool on osx).

I built postgres using src/makefile from the repo here as expected. From there, I converted the libs to .dylib manually and copied into the existing release bundle:

    g++ -fpic -shared -Wl,-force_load,libpgport.a -o libpgport.dylib
    g++ -fpic -shared -Wl,-force_load,libpgcommon.a -L`pwd` -lpgport -o libpgcommon.dylib
    install_name_tool -change libpgport.dylib /Applications/Postgres.app/Contents/Versions/9.6/lib/libpgport.dylib libpgcommon.dylib
    cp libpgport.dylib libpgcommon.dylib /Applications/Postgres.app/Contents/Versions/9.6/lib

Then I was able to build pg_bulkload without errors and copy to the bundle bin with the following tweak in order to find the .dylibs above:

    install_name_tool -change libpgport.dylib /Applications/Postgres.app/Contents/Versions/9.6/lib/libpgport.dylib pg_bulkload
    install_name_tool -change libpgcommon.dylib /Applications/Postgres.app/Contents/Versions/9.6/lib/libpgcommon.dylib pg_bulkload

I'm sure there's a better way to do all of this but this was quick and dirty and it appears to be working... Cheers!

PS The above files are pretty small so I'll include them in case someone wants to drop them in:
[pgapp_bulkload.tar.gz](https://github.com/PostgresApp/PostgresApp/files/619605/pgapp_bulkload.tar.gz)

**Comment by pbnjay** [comment]
Really sorry for yet more noise, I forgot the actual extension files in the tarball. I really am done now...

[pgapp_bulkload.tar.gz](https://github.com/PostgresApp/PostgresApp/files/619751/pgapp_bulkload.tar.gz)

**Comment by jakob** [comment]
@pbnjay Thanks for taking the time to document this!

It seems that the underlying issue is that Postgres.app doesn't include libpgport and libpgcommon. If I recall correctly, these libraries contain code that is common to the backend and the frontend. They are probably not installed because they are contained inside libpq.

This issue will probably also bite other people that try to build extensions for Postgres.app, so we should fix this.

Your workaround using g++ is neat, but I'd assume that there is a make target for installing these libraries; I'll see if I find something.

**Comment by jakob** [comment]
OK, I think I found the problem. My build script copies `lib/*.dylib`, but libpgcommon is built as a static library (libpgcommon.a), so it's not copied!

I'll see if I can fix this!

I'm reopening the issue so I don't forget.

**Comment by pbnjay** [comment]
ha... just went and tested just copying the 2 .a files into the bundle and pg_bulkload appears to build perfectly fine and not need the whole .dylib mess. Not sure why I made it so much more complicated but I'm sure I have a terribly obscure reason for it...

**Comment by jakob** [comment]
This is fixed with the most recent releases of Postgres.app (2.0, 9.5.5.1, 9.6.1.1)
