### ISSUE TITLE
Postgres.App clears focus on startup, even with welcome window disabled

### ISSUE THREAD

**Issue by jackcasey** [PostgresApp/PostgresApp#359]
Opening Postgres.app will always make the current window lose focus, without changing the current Application (menu bar). This happens even when opening it programmatically.

Reproduction steps:
1. Have Postgres.app installed
1. Disable "Show Welcome Window" option in Postgress preferences
1. Quit Postgres from the menu bar icon
1. Open Terminal.app and type `open -a Postgres`
1. Observe that the Terminal window is de-focused, but Terminal app is still the current App
1. Observe that keyboard input goes nowhere

This is quite annoying for me at the moment as I'm trying to build a little 'chaos monkey' script to intermittently kill and launch Postgres.app to test and diagnose database connection robustness of our web application.

I tried hacking LSBackgroundOnly into the plist but that doesn't seem to work for some reason. I don't know a lot about macos apps. I've also tried different invocations such as `open -ga Postgres` which apparently are for opening in the background.

**Comment by jakob** [comment]
Hi!

Two suggestions:

1. We are on the verge of releasing a new version of Postgres.app; please try the 2.0 beta (check out the releases section on Github)

2. Instead of starting / quitting Postgres.app, just start / stop the server using [pg_ctl](https://www.postgresql.org/docs/current/static/app-pg-ctl.html)

Hope this helps!

**Comment by jackcasey** [comment]
A colleague also suggested `pg_ctl`, which for some reason I didn't think of. It works perfecetly fine. Thankyou for your comment. I'll close this.
