### ISSUE TITLE
Documentation tweaks

### ISSUE THREAD

**Issue by telemachus** [PostgresApp/PostgresApp#36]
It's great that the app prompts you to "Open Documentation" when you run it, but it would be very helpful to link to [the docs](http://postgresapp.com/documentation) from the [main site](http://postgresapp.com) and in the README here on Github.

Also, as far as I can tell the app defaults to no password and a base user of `$USER`. Based on [an HN thread](http://news.ycombinator.com/item?id=4267540) about PosgresApp, I think it would be a good idea to mention that in the documentation.

One other small thing: On the documentation page, it says that data lives at `~/Library/Containers/com.heroku.Postgres/Data/Library/Application\ Support/Postgres/var`. But for the current version - 1.0 (11) - data seems to be at `~/Library/Application\ Support/Postgres/var`.

Thanks for PostgresApp.

**Comment by es6Test** [comment]
Does this  mean it started (or command worked)? I don't remember seeing any prompt in the install to ask for a password.
psql --list
psql: fe_sendauth: no password supplied
