### ISSUE TITLE
In GUI tools list, please add Postage

### ISSUE THREAD

**Issue by justintocci** [PostgresApp/PostgresApp#365]
In GUI tools list, please add Postage. Postage is a fast alternative to PGAdmin and seeks to be feature competitive with Microsoft SQL Server Management Studio(but for PostgreSQL). 

Postage is available for Linux, Mac and Windows, and is free for personal and commercial use.

https://github.com/workflowproducts/postage/releases/

**Comment by jakob** [comment]
Hey, thanks for sharing your work. I downloaded your app to try it, and I immediately hit a few issues:

- the app doesn't seem to be code signed
- I couldn't connect to the default database from Postgres.app (same name as system user) -- I got an error "empty password" (even though Postgres.app doesn't require passwords by default)
- after connecting to the database 'postgres', I couldn't switch to my user database (didn't show up in the database selection popup menu)

I'm not sure that recommending a product that doesn't work with Postgres.app out of the box in the Postgres.app documentation is a good idea.

**Comment by michaeltocci** [comment]
I downloaded Postgres.app (awesome app BTW!) and installed the latest Postage to try to replicate these issues.

You are correct, Postage is not signed. We talked about getting this done, here is the issue where we discussed it: (workflowproducts/postage#26).

I couldn't replicate the second two issues. Is it possible that there is some kind of configuration I don't have that's causing these issues?

I was able to log in without a password to the system user name.

I was able to switch to the system user database (picture below).
![database list](https://cloud.githubusercontent.com/assets/10438221/21431142/c4ff5a14-c82b-11e6-8890-12df5548f733.png)

I am going to try to replicate this on another computer using a source build.

Could you send us a copy of these items:

- postgres config
- postage.conf
- postage-connections.conf
- macOS version number
- postage build type (Mac Electron or Source)
- postage release number

**Comment by michaeltocci** [comment]
After building from source, we ran into the "no password" issue. We'll get this fixed and report back.

**Comment by josephtocci** [comment]
Michael and I were able to fix the issue by using the master branch with Nunzio's latest change. Thanks for reporting this.

**Comment by justintocci** [comment]
Jakob, thank you for taking the time to report these issues. I shudder to think how many people have run into them and we didn't even know. 

You are the first person to mention code signing. Since you mentioned it we are going to get an Apple developer account today. The next release of Postage will be signed.

This is further evidence that getting people to report issues is a problem for us. If you have any advice we'd welcome it. 

Thank you again.

**Comment by michaeltocci** [comment]
We're still unable to replicate the issue where the database is not in the "Switch Database" list.

I believe the reason I couldn't replicate the "no password" issue was because I had a second Postgres Database running on my computer. Now that I know that, I can replicate "no password" in the Electron version. Next release won't have this issue.

**Comment by nunziotocci** [comment]
I have Apple Code Signing Certificates and they work.
Next week we will have a (code-signed) release.

**Comment by nunziotocci** [comment]
@jakob, I have put out a new release just now. I would appreciate it if you could download it [here](https://github.com/workflowproducts/postage/releases/tag/eV3.1.3), and see if it fixes the problems you experienced.

**Comment by chrispysoft** [comment]
I've tested your new release but I'm not able to connect to the server (nothing happens when I press the Log In button - no errors).

**Comment by nunziotocci** [comment]
@chrispysoft, Did you download the application or did you build from source?

**Comment by chrispysoft** [comment]
I’ve downloaded the application from the link you've provided to @jakob

**Comment by nunziotocci** [comment]
@chrispysoft Can you Open the Dev Tools (View > Toggle Developer Tools) and take a screenshot?

**Comment by chrispysoft** [comment]
Hope this helps. (There are no console messages)

**Comment by nunziotocci** [comment]
What connection do you have highlighted in the login form?
The one that is most likely to work with Postgres.app is the one named "localhost@5432".

**Comment by chrispysoft** [comment]
I've tried all pre-defined connections and also added a custom one - no success and no error

**Comment by nunziotocci** [comment]
Please, send me the output of `ps -ef | grep -i post`

**Comment by nunziotocci** [comment]
I would like to see the Postgres and Postage processes.

**Comment by jakob** [comment]
Hey everyone,

This issue is getting off topic. Bugs in Postage should be discussed in the Postage repository. Every message posted here is sent to all the people watching the Postgres.app repo, and I really don't want to spam them with notifications irrelevant to them.

This issue was originally about adding Postage to the GUI tools list. The goal of this list is to help Postgres.app users find a tool that they can use on their Mac to work with Postgres.app. From this discussion it is clear that Postage is not yet tested enough on macOS to endorse it.

I'm closing this issue now.

Best regards,
Jakob
