### ISSUE TITLE
libjpeg linking problems

### ISSUE THREAD

**Issue by vignesh-sankaran** [PostgresApp/PostgresApp#367]
Trying to read from postgres via a database library in Rust, and get this error:

`dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Applications/Postgres.app/Contents/Versions/9.6/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO`

Tried reinstalling PostgresApp, and tried reinstalling libjpeg via Homebrew but to no avail.

**Comment by jakob** [comment]
This looks like a linker problem. `otool -L /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO` shows that it wants to link with a private Apple JPEG library. Apparently your build system tries to link it with Postgres.app's libJPEG.

I've never used Rust, and I have no idea what build system you are using. I'd suggest to start looking at library search paths -- maybe the ordering is wrong there?

Maybe if you upload a minimum test case that exhibits the problem, someone with experience in Rust could help?
