### ISSUE TITLE
psql: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by fcy** [PostgresApp/PostgresApp#37]
Hello,

I'm trying to run Postgress.app on Moutain Lion (don't know if it matters) but I'm getting this error:

> [~] ➔ psql -h localhost
> psql: could not connect to server: Connection refused
>   Is the server running on host "localhost" (::1) and accepting
>   TCP/IP connections on port 5432?
> could not connect to server: Connection refused
>   Is the server running on host "localhost" (127.0.0.1) and accepting
>   TCP/IP connections on port 5432?
> could not connect to server: Connection refused
>   Is the server running on host "localhost" (fe80::1) and accepting
>   TCP/IP connections on port 5432?

The elephant icon on the menu bar says it is running on port 5432. I've looked into ~/Library/Containers and the directory com.heroku.Postgres isn't there.

Looking in the Console.app I found this just after I open Postgress.app:

> 24/07/12 12:27:45,398 Postgres[26507]: Could not connect the action selectPostgresStatus: to target of class AppDelegate
> 24/07/12 12:27:45,551 Postgres[26507]: 26509 /Applications/Postgres.app/Contents/MacOS/bin/pg_ctl: Status 0

Any ideas how to solve? Any places where I can get more information about the problem, logs?

**Comment by cdanielge** [comment]
A quien pueda interesar. 

```
psql: could not connect to server: Connection refused
Is the server running on host "localhost" (::1) and accepting
TCP/IP connections on port 5432?
could not connect to server: Connection refused
Is the server running on host "localhost" (127.0.0.1) and accepting
TCP/IP connections on port 5432?
```

Revisé el log de possgres en : /var/log/postgresql/postgresql-9.4-main.log y decia 

> 2016-03-07 09:15:28 VET [8440-1] FATAL:  data directory "/var/lib/postgresql/9.4/main" has group or world access
> 2016-03-07 09:15:28 VET [8440-2] DETAIL:  Permissions should be u=rwx (0700).

Entonces procedí a darle los permisos como tienen que estar en ese directorio . Deben ser propiedad de postgres

```
# /etc/init.d/postgresql stop 
# chmod 755 /var/lib/postgresql/9.4/ 
# chmod 700 /var/lib/postgresql/9.4/main/ 
# chmod 700 /var/lib/postgresql/9.4/main/* -R
# chown postgres.postgres /var/lib/postgresql/9.4/main
# chown postgres.postgres /var/lib/postgresql/9.4 
# /etc/init.d/postgresql start


```

**Comment by anji7686** [comment]
Remove pid file

`rm /usr/local/var/postgres/postmaster.pid
`

**Comment by seba23571** [comment]
in my case I had the same problem and solve it with pgadmin 4.
I'm using win, but maybe for linux it's the same.
in the pgadmin 4 manager, go to the menu object, then properties.
In the dialog box go to connection, you have to change the port number. and ready.

**Comment by hammadyasir** [comment]
sir I am facing the same problem, kindly give me the solution, when i want to connect Postgresql with AWS then I am facing time session error

**Comment by giridhar2000** [comment]
> in my case I had the same problem and solve it with pgadmin 4.
> I'm using win, but maybe for linux it's the same.
> in the pgadmin 4 manager, go to the menu object, then properties.
> In the dialog box go to connection, you have to change the port number. and ready.
thanks

**Comment by Chitra122499** [comment]
> 
> 
> > in my case I had the same problem and solve it with pgadmin 4.
> > I'm using win, but maybe for linux it's the same.
> > in the pgadmin 4 manager, go to the menu object, then properties.
> > In the dialog box go to connection, you have to change the port number. and ready.
> > thanks

i am also using win but the above procedure is not working

**Comment by bhagwandassoni1953** [comment]
root@localhost:/# psql -h localhost -p 5432 -U postgres                          psql: could not connect to server: Connection refused                                    Is the server running on host "localhost" (127.0.0.1) and accepting              TCP/IP connections on port 5432?

**Comment by bhagwandassoni1953** [comment]
🖕.

**Comment by tbussmann** [comment]
most of the comments in this issue seem to refer to PostgreSQL connection problems in general and / or are about other distributions of PostgreSQL. The ones at the beginning are outdated. I'm going to lock this thread. If you have issues connecting to a server that is provided by PostgresApp, please open a new issue.
