### ISSUE TITLE
The latest version always opens on boot

### ISSUE THREAD

**Issue by eddiejaoude** [PostgresApp/PostgresApp#372]
How to disable on boot?

**Comment by jakob** [comment]
1. Open Postgres.app
2. Menu "Postgres" -> "Preferences"
3. Uncheck "Automatically Start Postgres on Login"

**Comment by eddiejaoude** [comment]
Yes that was the case for the previous version. But now there is not that option?

<img width="838" alt="screenshot 2017-01-18 08 24 47" src="https://cloud.githubusercontent.com/assets/624760/22056414/ea5ccb3e-dd57-11e6-98ca-f53a8d61deb5.png">

**Comment by jakob** [comment]
Sorry, I wasn't clear enough. I mean the other Postgres menu:
<img width="768" alt="screen shot 2017-01-18 at 09 38 10" src="https://cloud.githubusercontent.com/assets/198305/22056767/052e587e-dd62-11e6-94d1-4740ede3e2ce.png">

Maybe we should add the "Preferences.." and "Check for updates" commands to the elephant menu. They are not very discoverable.

**Comment by eddiejaoude** [comment]
Ah got it! Thanks!

> Maybe we should add the "Preferences.." and "Check for updates" commands to the elephant menu. 

Might be a good idea 👍
