### ISSUE TITLE
restoring backups that use the \connect -reuse-previous option is not working

### ISSUE THREAD

**Issue by csavory** [PostgresApp/PostgresApp#374]
According to this release notes Postgres added this reuse-previous in 9.2.18.
https://www.postgresql.org/docs/9.3/static/release-9-2-18.html

Our backups with RDS started including that option in the scripts.  

When I try to restore one of these backups with the \i command I get the following error.

```
edb-loadtest=# \i /Users/csavory/Downloads/demo-backup.sql                                                                                                                             SET
SET
SET
SET
SET
SET
DROP DATABASE
CREATE DATABASE
ALTER DATABASE
psql:/Users/csavory/Downloads/demo-backup.sql:27: \connect: invalid connection option "-reuse-previous"
```

Here are some details for that backup:
```
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.3.14
-- Dumped by pg_dump version 9.4.10
-- Started on 2017-01-24 17:02:42 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

DROP DATABASE "edb-demo";
--
-- TOC entry 3768 (class 1262 OID 112548)
-- Name: edb-demo; Type: DATABASE; Schema: -; Owner: rdspostgres
--

CREATE DATABASE "edb-demo" WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8';


ALTER DATABASE "edb-demo" OWNER TO rdspostgres;

\connect -reuse-previous=on "dbname='edb-demo'"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

```

I am currently using this version of Postgres.app

![image](https://cloud.githubusercontent.com/assets/2187083/22259729/0d35f864-e22c-11e6-903c-2450852f492b.png)

**Comment by jakob** [comment]
1. You are using a very outdated version of PostgreSQL. Please download 9.4.10 from this page: https://postgresapp.com/documentation/all-versions.html

2. Make sure that you are actually using the version of psql supplied by Postgres.app! Type `which psql` to see what binary you are running. It should be `/Applications/Postgres.app/Contents/Versions/latest/bin/psql` or `/Applications/Postgres.app/Contents/Versions/9.4/bin/psql`. See here for setting up your $PATH: https://postgresapp.com/documentation/cli-tools.html

3. Check what version of psql you are using with `psql --version`

**Comment by csavory** [comment]
Thanks for the infor @jakob.  I thought Postgres.app was auto updating so I didn't realize I was out of date.  

After upgrading to 2.0.1 I am not getting this error anymore.
