### ISSUE TITLE
pg_dump - postgres server version mismatch

### ISSUE THREAD

**Issue by CVB-PGSQL** [PostgresApp/PostgresApp#379]
Installed version 9.6 of the PostgresApp on MacOS Sierra.  All goes fine with creation, querying etc. but when I attempt to run pg_dump I get an abort message saying the there is a server - pg_dump version mismatch with server version reported as 9.6.1 and pg_dump as version 9.5.5.

I searched through the Postgres/Contents/Versions directories (9.5, 9.6 and latest) and the version of pg_dump was exactly the same in all of them (i.e., 9.5.5).  I then checked for updates and there was one, so had it installed.  This changed the version of pg_dump to 9.5.6 in all Versions directories.

Any way to fix this version mismatch?

Clive.

**Comment by jakob** [comment]
(turned out to be a typo in a shell command)
