### ISSUE TITLE
Getting Errors and Malware Using Latest Version of postgres.app

### ISSUE THREAD

**Issue by lightbe** [PostgresApp/PostgresApp#380]
A few days ago I decided to use the latest version of the app and create databases using my sql backup. I installed it and got it working fine. About an hour ago I started getting errors saying that a relation was not defined. I assumed it was a coding error in my Rails app. Then I started getting Avast malware notifications.

![postgres app avast malware](https://cloud.githubusercontent.com/assets/1304976/23191978/6bcddda6-f866-11e6-9ccd-01a970c1eb1d.jpg)

I had read that these could be ignored but decided not to take a chance and remove postgres.app and reinstall the same version. As soon as I tried to start the app I continued getting these alerts from Avast. I never got it working.

I got the screen with the initialize screen.

![postgres app initialize](https://cloud.githubusercontent.com/assets/1304976/23192030/b12e6e74-f866-11e6-8164-4f8ab3c8105a.jpg)

I got an error when I clicked the initialize button.

![postgres app initialize error](https://cloud.githubusercontent.com/assets/1304976/23192041/bd9adcf6-f866-11e6-88fd-1b36f4c80b2a.jpg)

When I clicked the Open Server Log button nothing happened.

I've used postgres.app for 2-3 years and this is the first time I have had any problems with it. For now I will use the previous version.

UPDATE: I just tried the old 9.6.2 app and the 9.5 one. I get similar errors and Avast messages on the pg_xlog file. My concern is that it's only flagging files with the malware from postgres.app. I cannot quit the app at all. It just makes a noise like I'm trying to do an illegal action with Avast messages continuing to post.

**Comment by jakob** [comment]
Presumably VBS:Malware-gen is some generic pattern to match visual basic viruses. It looks like that match pattern is identifying postgres data files as containing viruses.

I am almost 100% sure that this is a false positive.

Unfortunately, we can't offer support for Anti virus products. Please contact Avast customer support.

**Comment by lightbe** [comment]
If that's the case it happened with the last virus definition update for Avast. I hope that's the case. I will try another virus scan program and reinstall postgres.app. I really love the app. I have it on my development and production servers.
