### ISSUE TITLE
What configuration tweaks are made compared to the default config?

### ISSUE THREAD

**Issue by brandonros** [PostgresApp/PostgresApp#381]
I'm getting 5s query times on a Linux box that doesn't use Postgres.app, and 100ms query times with the Mac app.

What tweaks do you guys make in the configs that might cause this?

Hardware is comparable, data is the same, query is the same.

**Comment by jakob** [comment]
We leave most settings on default.

I recommend to compare the output of EXPLAIN for the query on both machines.

Could be that statistics aren't up to date, which causes the query planner to choose a non-optimal strategy. ANALYZE should fix that.

Or maybe you have an index on the Mac that's missing on Linux.

If the EXPLAIN output is the same, hardware config might make the difference. Many DB queries are IO bound, so if the data fits in RAM on one machine but not on the other you'd see things like this. Also hard drive vs. SSD, or busy disk in a VM vs mostly idle disk on your Mac.

There are so many possibilities....

**Comment by jakob** [comment]
To answer your actual question, you can determine the build settings for Postgres.app with the shell command `pg_config`:

> CONFIGURE = '--prefix=/Applications/Postgres.app/Contents/Versions/9.6' '--with-includes=/Applications/Postgres.app/Contents/Versions/9.6/include' '--with-libraries=/Applications/Postgres.app/Contents/Versions/9.6/lib' '--enable-thread-safety' '--with-openssl' '--with-gssapi' '--with-bonjour' '--with-libxml' '--with-libxslt' '--with-perl' '--with-python' '--with-readline' '--with-uuid=e2fs' '--enable-tap-tests' 'CFLAGS= -mmacosx-version-min=10.7'

Databases are created with the following options (see `initDatabaseSync()` in [Server.swift](https://github.com/PostgresApp/PostgresApp/blob/master/Postgres/Server.swift)):

    initdb -D path/to/data/directory -U postgres --encoding=UTF-8 --locale=en_US.UTF-8

**Comment by jakob** [comment]
A difference between PostgreSQL on macOS and Linux is that macOS doesn't support any collations for UTF-8. So if your query includes a lot of string comparisons etc, macOS will probably be a bit faster,

**Comment by jakob** [comment]
(sorry, pressed wrong button by accident)
