### ISSUE TITLE
Unable to access psql cli after installing postgres app

### ISSUE THREAD

**Issue by alvinkatojr** [PostgresApp/PostgresApp#383]
![screen shot 2017-03-04 at 08 15 26](https://cloud.githubusercontent.com/assets/519988/23576299/d61359da-00b2-11e7-9194-4965099ff3b8.png)
![screen shot 2017-03-04 at 08 15 42](https://cloud.githubusercontent.com/assets/519988/23576300/d6144020-00b2-11e7-887f-49f093949423.png)

So after successfully installing postgres app, commandline tools are not working. Even the command `psql` is not accessible. This is the second time running into this issue after my upgrade to Sierra, last time this happened I went back to using homebrew. 

Prior to version 2 and with the older versions of postgresapp I'd never run into this issue before. Please help, thanks!

**Comment by jakob** [comment]
It looks like you haven't configured your $PATH correctly. Type `echo $PATH` to confirm.

I'm not familiar with zsh. The config file looks like a bash config file. Maybe that's the problem?

Adding a file name `/etc/paths.d/postgresapp` with the contents `/Applications/Postgres.app/Contents/Versions/latest/bin` should also work with zsh.

**Comment by alvinkatojr** [comment]
Zsh and Bash config files have minor difference if any. Previous versions of postgresapp worked fine with the $PATH settings so its not a zsh issue.

Also it might help to be more direct and clear with the set up steps for this new version, the older version had explicit directions for setting path, and editing either bash or zsh files. With version 2 its more like guess work for noobs and thats frustrating. 

I have attached screenshots of the new edits to my $PATH and the result of running `echo $PATH`. Please point out where I've missed it. Thanks!

![screen shot 2017-03-04 at 17 56 48](https://cloud.githubusercontent.com/assets/519988/23579717/4ea5a848-0104-11e7-8fbb-ee3b69fa1771.png)
![screen shot 2017-03-04 at 17 57 04](https://cloud.githubusercontent.com/assets/519988/23579718/4ea85c46-0104-11e7-9829-082f8eede6b0.png)

**Comment by cappert** [comment]
hello,
the exact commands to add postgresapp binaries to your paths are documented on https://postgresapp.com/ :
``` 
sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp
```
You don't need to add anything to your zsh configuration files, running those commands add them to your PATH via other means.

**Comment by alvinkatojr** [comment]
Hello @cappert thanks, but I've done that over and over and it still does n't work. See the attached screenshot. Something is wrong somewhere because this is the 2nd time am installing postgresapp v2 with a fresh install of Sierra and its doing the same thing.
![screen shot 2017-03-04 at 17 57 04](https://cloud.githubusercontent.com/assets/519988/23583527/24251686-0158-11e7-919a-37e22a81fc81.png)

**Comment by cappert** [comment]
what gives `ls /Applications/Postgres.app/Contents/Versions/latest/bin` ?

**Comment by alvinkatojr** [comment]
Here's the list of binary contents.

![screen shot 2017-03-05 at 10 14 42](https://cloud.githubusercontent.com/assets/519988/23585318/9efa5518-018c-11e7-8404-c06006e6c1d4.png)

**Comment by cappert** [comment]
have you modified /etc/profile at all?
mine looks like this:
```
# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
	[ -r /etc/bashrc ] && . /etc/bashrc
fi
```
`path_helper` is the command populating the PATH using `paths.d`.

Looking back at your first picture, I see you set the path for go and mongo, but neither of them are present in your actual PATH, did you remove these statements? What file were you editing?

I can't reproduce your issue with Sierra, zsh, and Postgres 2.0.2, using either `export` in my .zshrc or using `/etc/paths.d`.

**Comment by alvinkatojr** [comment]
Hi @cappert. No I have n't, it looks exactly like yours:
![screen shot 2017-03-05 at 21 23 22](https://cloud.githubusercontent.com/assets/519988/23590059/2f37acae-01ea-11e7-838c-25fa5a83f4f3.png)

About the mongo/go paths, my zsh file is usually saved on gist and it has a lot of aliases and path settings, those paths are from my previous install when I had both mongo and go installed, I don't know but I had forgotten to comment them out. I'll do that now. 

Ah that's sad, I guess I'll have to resume to using homebrew's postgres then :(

**Comment by jakob** [comment]
@alvinkatojr It sounds like you somehow messed up your zsh configuration files. You have two possibilities:

1) Format your hard drive and start from a fresh install of macOS. Then you can use the instructions from the Postgres.app homepage, and they will work.

2) Read the zsh documentation and try to find out what is going on. You can start zsh with the `-x` flag for debugging. Use a command like the following to see what scripts are executed when you login, and why the $PATH isn't what you expect:
`login -f $USER zsh -x`

3) Also, remember that changes to configuration files only take effect when you restart your shell (close terminal window, and open a new one)

In any case, it doesn't seem like this is an issue with Postgres.app or our documentation. We can't include instructions for using the shell in our documentation -- that's a prerequisite if you want to use command line tools. You really need to consult the zsh documentation if you have problems setting up your environment.

**Comment by TroutNemesis** [comment]
I've never used Zsh before. But I'm experiencing the same problem.

**Comment by jakob** [comment]
@TroutNemesis Please open a new issue, and describe your problem in detail.

**Comment by alvinkatojr** [comment]
@jakob while I understand where you are coming from, I don't think this is a zsh issue given that most of my output matches what @cappert had on his terminal. 

Nevertheless I've resorted to the homebrew installation for now. I do hope though that this issue does n't crop up again because v1 of postgresapp was a breeze to work with but I honestly can't say the same for v2.
