### ISSUE TITLE
Binaries not found (Mac)

### ISSUE THREAD

**Issue by songproducer** [PostgresApp/PostgresApp#388]
Just downloaded PostgreSQL 9.3 to replace old version.

Getting the error messge:
Binaries not found

When I click Start button I get:

The binaries for this PostgreSQL server were not found
Create a new Server and try again

How can I fix this please?

**Comment by songproducer** [comment]
Solved by deleting app support postgresql folder, clicking the icon and removing the old server.

**Comment by infomofo** [comment]
can you clarify this more? I am running into the same issue and want to know specifically what folder you had to delete.  Did you lose data?

**Comment by jakob** [comment]
If you run into the "Binaries not found" error, you need to make sure you have the right binaries for your data directory. They must be the same version. The standard download has binaries for 9.5 and 9.6.

You can get binaries for older versions here: 
http://postgresapp.com/documentation/all-versions.html
(See the section mix & match)

**Comment by jakob** [comment]
Also, see this page for updating instructions:
https://postgresapp.com/documentation/update.html

**Comment by aubergene** [comment]
I'm getting this error. I did a clean install of OSX Sierra and restored my data but not apps. I get this error when trying to start Postgres app, so I think perhaps I have an old copy of data which I don't need. What's the location I would need to delete?

Postgres app Version 2.0.3 (21)
PostgreSQL 9.3
OSx 10.12.5

**Comment by songproducer** [comment]
The folder I deleted would have been either /Library/Application Support/Postgresql or Users/username/Library/Application Support/Postgresql

**Comment by axelson** [comment]
The https://postgresapp.com/documentation/update.html and https://postgresapp.com/documentation/migrating-data.html pages are missing a crucial step if you are trying to upgrade from something a pre 9.5 database.

So PostgresApp 2 has this concept of multiple databases, and it ships with the **binaries** for 9.5 and 9.6, so if you are currently running 9.4 and you upgrade to PostgresApp 2 you will get this "Binaries not found" error. However, you are not getting this error for the entire PostgresApp 2 application, just for your existing 9.4 server instance. So if you click on the panel icon in the bottom left:
<img width="94" alt="screenshot 2017-07-19 15 51 14" src="https://user-images.githubusercontent.com/9973/28396918-1ef95a70-6c9a-11e7-9788-082894f92e50.png">

You can create a new server running the latest version of postgres and then you can finish following the instructions on https://postgresapp.com/documentation/migrating-data.html

**Comment by knussear** [comment]
I have this same problem. New install, "binaries not found"

**Comment by jakob** [comment]
@knussear Open the sidebar (using the button in the bottom left), then click the plus button, and create a new server with version 11
