### ISSUE TITLE
Binaries for latest legacy versions?

### ISSUE THREAD

**Issue by ottob** [PostgresApp/PostgresApp#391]
The download-links for legacy versions from the homepage does not work: https://github.com/PostgresApp/PostgresApp/releases/download/9.6.3/Postgres-9.6.3.zip and
https://github.com/PostgresApp/PostgresApp/releases/download/9.5.7/Postgres-9.5.7.zip gives 404.

Only the source is available at https://github.com/PostgresApp/PostgresApp/releases/tag/9.6.3

Have you stopped building the legacy binaries? Or are they still building :)

**Comment by jakob** [comment]
Oops, it looks like I forgot to click the "publish" button on Github. It should work now!
