### ISSUE TITLE
Auto start on login not working

### ISSUE THREAD

**Issue by MtnBiker** [PostgresApp/PostgresApp#396]
Postgres 2.0.3. "Automatically start Postgres on Login checked."  √ 

And "Open Databases with iTerm." is selected. However I have no idea what that means. I use iTerm for CLI access. But "open database"? I open them with pgAdmin or access via Rails.

Thanks for an otherwise great app.

**Comment by jakob** [comment]
The popup lets you choose what happens when you double click a database icon in Postgres.app

We should probably improve that label.
