### ISSUE TITLE
How to configure Postgresapp to be available on network at static IP address

### ISSUE THREAD

**Issue by adw1011** [PostgresApp/PostgresApp#397]
I recently uninstalled the Enterprise Version of PG and installed this version.  I completely uninstalled the Enterprise version and started the server as 'localhost'.  The machine has a static IP and I used to be able to access my PG database across my network using the IP address, now I am getting a cannot connect to server on port 5432 message although I can still connect as localhost.

**Comment by jakob** [comment]
By default, PostgreSQL only listens on localhost. To make it listen on all interfaces, change listen address to * in postgresql.conf, then restart the server.

You will also need to update the pg_hba file to allow connections from the network

You can find the config files in the data directory.

**Comment by adw1011** [comment]
Jakob, thanks for your help and your quick post.
