### ISSUE TITLE
Open Postgress.app, Initialize Server, CreateDatabase, all from commandLine ?

### ISSUE THREAD

**Issue by patchthecode** [PostgresApp/PostgresApp#398]
How do i Open Postgress.app, Initialize Server, CreateDatabase, all from commandLine ?

**Comment by jakob** [comment]
You can use the [initdb](https://www.postgresql.org/docs/current/static/app-initdb.html) command to initialize a database directory, then use [pg_ctl](https://www.postgresql.org/docs/current/static/app-pg-ctl.html) to start the the server, and then use [createdb](https://www.postgresql.org/docs/current/static/app-createdb.html) to create a new database.

If you want the new server to show up in Postgres.app, you'll need to use the defaults command to update the `com.postgresapp.Postgres2` domain, specifically editing the `Servers` array to add your new server.
