### ISSUE TITLE
Deceptive site ahead when trying to download from https://postgresapp.com/

### ISSUE THREAD

**Issue by forgethisname** [PostgresApp/PostgresApp#400]
I'm getting this browser warning when clicking on the download button on the website (both in Chrome Version 59.0.3071.115 (Official Build) (64-bit) and Safari Version 10.1.1 (12603.2.4)
This seems to be a new error - we downloaded yesterday and didn't get it.

Can you advise?

Thanks
Matthew.
![screen shot 2017-07-25 at 11 56 53](https://user-images.githubusercontent.com/644804/28569299-24fc9572-7131-11e7-897b-1d96d11b2386.png)
![screen shot 2017-07-25 at 12 00 45](https://user-images.githubusercontent.com/644804/28569307-2ace01b6-7131-11e7-8152-6586fbacd28c.png)

**Comment by jakob** [comment]
Thanks for the report! According to (this article)[https://www.bleepingcomputer.com/news/security/some-github-downloads-blocked-in-chrome-and-firefox-due-to-safe-browsing-warning/] it was a glitch in Google's safe browsing service. Binary downloads from Github were incorrectly blocked. Looks like they've fixed it already.

**Comment by forgethisname** [comment]
Thanks for the update Jakob
