### ISSUE TITLE
FATAL:  could not create lock file "/var-9.6/pgsql_socket/.s.PGSQL.5432.lock": No such file or directory

### ISSUE THREAD

**Issue by amorimlucas** [PostgresApp/PostgresApp#401]
Hey, I'm getting this error when I try to start the Postgres.app server. I don't think it's a permissions issue because the directory has full permissions, and there are no existing locked files already because the directory is empty. What could be causing this?

**Comment by jakob** [comment]
Is that the literal error message or did you edit it?

The way it is now, it looks like your data directory is misconfigured. The default data directory for Postgres.app should be `/Users/USERNAME/Library/Application Support/Postgres/var-9.6`. Looks like it is set to `/var-9.6` on your Mac.

Please also note that using the tilde as a shortcut for your home directory does not work in PostgreSQL config files.

**Comment by amorimlucas** [comment]
Changing the config file to point to the full path fixed it, thanks!
