### ISSUE TITLE
change listener port has no effect

### ISSUE THREAD

**Issue by ukr15** [PostgresApp/PostgresApp#402]
Hi there, i want to use my postres to listen on port 5433, but changing port in
postgresql.conf to
`port = 5433			# (change requires restart)`
has no effect after restart.

`ps -aef| fgrep Postgres/var` shows, that Postgres is started with default port
` 0:00.13 /Applications/Postgres.app/Contents/Versions/9.6/bin/postgres -D /Users/foo/Library/Application Support/Postgres/var-9.6 -p 5432`

**Comment by chrispysoft** [comment]
Postgres.app starts the server with the port number specified in the server settings. This means, that changing the port in the config file has no effect.
![screen shot 2017-08-24 at 15 43 05](https://user-images.githubusercontent.com/18659749/29669323-5707e39a-88e3-11e7-820b-c74af31221e7.png)
So you have two options:
- change the port in the server settings (simplest solution)
- start the server from the command line, e.g.: `./pg_ctl start -D <varPath> -w -l <logPath> -o -p5433`
