### ISSUE TITLE
Postgres 10 support?

### ISSUE THREAD

**Issue by huhlig** [PostgresApp/PostgresApp#406]
Feature Request for Postgres 10 support on release.

**Comment by jakob** [comment]
We'll support PostgreSQL 10 on release. We were a bit lazy with the beta builds, but we'll have PostgreSQL 10 support on release day.

**Comment by jakob** [comment]
I just made a build of PostgreSQL 10rc1: https://github.com/PostgresApp/PostgresApp/releases/tag/10rc1

See the section Mix & Match on [this page](https://postgresapp.com/documentation/all-versions.html) for instructions how to use these binaries with Postrges.app 2

**Comment by joaodlf** [comment]
The day has come! :) (Thanks for the awesome work on PostgresApp - I'm eager to see a working version for 10!)
