### ISSUE TITLE
enhancement - make is easier to run  database on different directory

### ISSUE THREAD

**Issue by johndpope** [PostgresApp/PostgresApp#411]
eg. docker -> 
<img width="377" alt="screen shot 2017-10-07 at 10 27 12 pm" src="https://user-images.githubusercontent.com/289994/31313347-b4c0c61c-abae-11e7-825a-f7b5686396ac.png">
you can simply move images.

**Comment by chrispysoft** [comment]
You can "move" images by deleting the server from the list (press button "-") and creating a new one (press button "+"). Set the data directory to your specific path and make sure that the server version matches the version of your data directory! (NB: Deleting a server from the list doesn't affect the files on your disk)
