### ISSUE TITLE
unexpected pageaddr with 9.6 in High Sierra

### ISSUE THREAD

**Issue by CodeMeister** [PostgresApp/PostgresApp#413]
Starting the 9.6 server in High Sierra gives an 'unexpected pageaddr' fault.   Both 9.5 and 10.0 work fine.

Log entry:
```
LOG:  database system was interrupted; last known up at 2017-10-13 00:53:31 BST
FATAL:  the database system is starting up
LOG:  unexpected pageaddr 25/2BB0A000 in log segment 000000010000002500000055, offset 11575296
LOG:  invalid primary checkpoint record
LOG:  unexpected pageaddr 25/2BB06000 in log segment 000000010000002500000055, offset 11558912
LOG:  invalid secondary checkpoint record
PANIC:  could not locate a valid checkpoint record
LOG:  startup process (PID 18703) was terminated by signal 6: Abort trap
LOG:  aborting startup due to startup process failure
LOG:  database system is shut down
```

The database files were restored from a backup ... but work on the macOS Sierra version with no problem.

Any ideas?

**Comment by jakob** [comment]
It looks like you tried to restore a backup that was created while the server was running. [According to the docs](https://www.postgresql.org/docs/current/static/backup-file.html), this requires a consistent snapshot of the file system. It looks like whatever you used for backup did not make a consistent snapshot, and you now have a corrupted data directory.

If possible, try to restore from a dump (use pg_dump or pg_dumpall).

**Comment by CodeMeister** [comment]
Many thanks for the help :-)
