### ISSUE TITLE
PostgreSQL 9.6

### ISSUE THREAD

**Issue by hotzen** [PostgresApp/PostgresApp#422]
Hello,
is there a plan to release a new version supporting PostgreSQL 9.6?
https://www.postgresql.org/docs/9.6/static/release-9-6.html

Regards,
Kai

**Comment by jakob** [comment]
The current version of Postges.app includes PostgreSQL 9.6.6. To create a server running 9.6, please open the sidebar and click the "+" button to add a new server.

Does that answer your question?

**Comment by hotzen** [comment]
wow sorry, wasn't aware of that.
