### ISSUE TITLE
Does Postgres.app provide a command to invoke itself in Terminal?

### ISSUE THREAD

**Issue by adamaiken89** [PostgresApp/PostgresApp#424]
I am running a `Procfile-Based Application` and am using `Postgresql` for development. I am thinking if `Postgres.app` can be invoked through command so that I can run everything as I run `Procfile`.

Thank you.

**Comment by jakob** [comment]
You can just use `pg_ctl start -D /path/to/datadir` to start the postgres server from the command line. See the docs: https://www.postgresql.org/docs/current/static/app-pg-ctl.html

Make sure you use the absolute path to the data dir.

Also, if you have multiple PostgreSQL installs, make sure that you are using the right version of pg_ctl (`which pg_ctl` is useful here)

**Comment by Aiken00** [comment]
Thank you very much for the reply. Does `Postgres.app` provide a path helper to the data directory? It would be great if such path can be Postgres.app dependent but not machine dependent.

**Comment by Aiken00** [comment]
Also the default data directory in official site might not be usually correct now.
The data directory path can be ` ~/Library/Application Support/Postgres/var-10` but not just  `~/Library/Application Support/Postgres/var-9.6`.

https://postgresapp.com/documentation/install.html
