### ISSUE TITLE
Menu lingers after use

### ISSUE THREAD

**Issue by jayhale** [PostgresApp/PostgresApp#427]
Didn't see this one in the open issues. For the past several versions of Postgres.app, the menu lingers in a semi-rendered way after use:

<img width="252" alt="screen shot 2017-12-14 at 9 22 32 am" src="https://user-images.githubusercontent.com/31579448/34002731-a1865616-e0b0-11e7-8c60-6f7327e00038.png">

Postgres.app version: Version 2.1.1 (40)
OSX version: 10.13.1 (17B1003)

Minor but annoying issue.  Cheers!

**Comment by chrispysoft** [comment]
We have already tried to fix this - it seems to be a bug in macOS 10.13 😕
