### ISSUE TITLE
9.5, 9.6 Missing

### ISSUE THREAD

**Issue by diek** [PostgresApp/PostgresApp#429]
The website says, "The current version requires macOS 10.10 or later and comes with the latest PostgreSQL versions (10.1, 9.6.6, and 9.5.10)". I am using Mac 10.13.2, only PostgreSQL 10 is available, and I cannot  see any way to add 9.5, and 9.6. How can I add 9.5 and 9.6?

**Comment by jakob** [comment]
Open the sidebar + add a new server!

**Comment by diek** [comment]
Thanks
