### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by badbye** [PostgresApp/PostgresApp#431]
The operation can’t be completed because one or more required items can’t be found.
(Error code -43)

![image](https://user-images.githubusercontent.com/3295865/34712502-f5245fa4-f55d-11e7-974a-a182669f739a.png)

macOS Version: 10.13.2 (17C88)

**Comment by chrispysoft** [comment]
This error means that some files are missing or corrupted. Please delete and re-download the .dmg-file and try again.
