### ISSUE TITLE
update to postgres >= 10 - how to?

### ISSUE THREAD

**Issue by lboc80** [PostgresApp/PostgresApp#447]
I'm using Postgres.app 2.1.3, my postgresql version is 9.8.
How can I upgrade that to at least v. 10?

Tried thorugh the 'check for updates' menu but it does not work.

I'm on OS X 10.13.4

Thanks

**Comment by jakob** [comment]
Postgres.app includes PostgreSQL 9.5, 9.6 and 10.

PostgreSQL 10 is the latest version. There is no PostgreSQL 9.8.

Postgres.app does not automatically upgrade your server. You need to create a new server (using the sidebar) with the version you want, and then migrate your data (using pg_dump or similar).
