### ISSUE TITLE
Allow hiding the window but still running the app

### ISSUE THREAD

**Issue by nikitavoloboev** [PostgresApp/PostgresApp#455]
Please allow to hide the window but still have Postgres app running in the background. In typical macOS apps, pressing red button:
![2018-07-16 at 11 10](https://user-images.githubusercontent.com/6391776/42750817-e7c7e64a-88e8-11e8-9689-410b64d86f5c.png)

Will close the window but not quit the app. In this case however it quits the app entirely. Is it possible to hide the window but still have the app running?

**Comment by jakob** [comment]
The main app is just a "control center". The PostgreSQL server is a separate process and keeps running in the background, even when the app is closed.

The menu bar app is also a separate helper app, so you can start / stop servers without the main app running.

The reason that we split it into multiple apps is that most people want to have PostgreSQL servers running in the background, and don't want the app to always appear in the dock.

**Comment by nikitavoloboev** [comment]
Thank you @jace
