### ISSUE TITLE
Upgrading Postgres via upgrading PostgresApp?

### ISSUE THREAD

**Issue by oyeanuj** [PostgresApp/PostgresApp#458]
Hi @jakob, firstly, I think the PostgresApp v2 looks great! :)

I was however unclear if I should expect the Postgres version that my existing DB is using by upgrading PostgresApp? Based on the docs, that was my expectation, but my DB is still on 9.6.

If that is true, do you know what might be wrong? If upgrading app doesn't upgrade the existing DB, then what is the method that you recommend to upgrade the DB while sticking to the app (over Homebrew)?

Thank you!

**Comment by jakob** [comment]
Postgres.app does not migrate your data from 9.6 to 10 automatically. Automatic updates only do bugfix updates.

If you want to migrate your server, please do this:

1) make sure that your version 9.6 server is running
2) use pg_dump_all to dump your database
3 ) stop the old server
4) create a new server with PostgreSQL 10 (open the sidebar in Postgres.app)
5) use psql to load the dump you created earlier 

Also, see the docs here: https://postgresapp.com/documentation/migrating-data.html

**Comment by oyeanuj** [comment]
@jakob Thank you!
