### ISSUE TITLE
What is the default password ?

### ISSUE THREAD

**Issue by paulgureghian** [PostgresApp/PostgresApp#459]
During the install on my mac  I was not prompted to create one. I m trying to configure a $PATH to use the command line tools. 

sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp

**Comment by jakob** [comment]
The password prompt you see after executing the above command is for your computer login password. The `sudo` command requires your password.

Postgres.app does not set up a password for the PostgreSQL server. No password is required when connecting from your own computer, and connections from other computers are disabled.
