### ISSUE TITLE
Add instructions for installing pgloader given Postgres.app

### ISSUE THREAD

**Issue by jungblud** [PostgresApp/PostgresApp#460]
The instructions (very well written!) on the Postgres.app site point out that existing PostgreSQL instance installed with Homebrew should be removed, since that is the purpose of Postgres.app after all.

However, when installing pgloader via Homebrew, it reinstalls PostgreSQL as a dependency.

What is the proper way to install pgloader given the change in location of PostgreSQL with Postgres.app i.e. without Homebrew?

**Comment by jakob** [comment]
If you know what you are doing, you can have multiple PostgreSQL installations on your Mac.

The only problem that people kept running into was that they tried to start Postgres.app when a different PostgreSQL server was already running on the same port. This is really confusing, and what most people want is just one PostgreSQL installation.

My recommendation is not to worry about the additional PostgreSQL binaries -- as long as you don't try to start two servers on the same port you shouldn't have any issues.

You can configure your $PATH to choose which version of psql / pg_dump etc. to use.

**Comment by jungblud** [comment]
It may be unnecessary, but I found a link that gives the solution. Here is content for your site. If you think it valuable I'll add a pull request:

NOTE: Installing *pgloader* with homebrew will attempt to install PostgreSQL as a dependency. To install pgloader using homebrew without postres as a dependency, see [this issue](https://github.com/dimitri/pgloader/issues/588) on the [pgloader Github repository](https://github.com/dimitri/pgloader).

I find this to be valuable as most need pgloader along with PostgreSQL and don't want an extra installation hanging around.

**Comment by jakob** [comment]
I'm not sure what page this would fit on. We don't really have any docs for third party tools like pgloader. But maybe that would be useful. Any suggestions?

**Comment by jungblud** [comment]
Just created a pull request. It was the first place I searched when I was looking for information around how to install pgloader in a tidy fashion in the context of using PostgresApp. I'm not a fan of extra installs laying around. Seemed to be a good spot for your user base. Totally your call, of course. Thanks for the great tools!

**Comment by jakob** [comment]
I found your pull request: https://github.com/dimitri/pgloader/pull/819

That's a different project, so I don't have anything to say on that :)

Anyway, this sounds like a good idea. Thanks a lot!

**Comment by chris** [comment]
Note, while it wouldn't be building from source, you can get a working `osm2pgsql` with Postgresapp by installing with Homebrew, and telling it to ignore dependencies. e.g. I'm using Postgresapp to ensure I use version 10 of Postgres (whereas Brew would install v12), but I installed osm2pgsql (and it works fine) with:
```
brew install osm2pgsql --ignore-dependencies
```

Before you run that, you may want to check any other dependencies it needs (I had them already), by doing:
```
brew info osm2pgsql
```
As long as Postgres is the only one that's unchecked, and you have your Postgresapp CLI configured, it should then work.
