### ISSUE TITLE
Can We Get This On Linux? [Request]

### ISSUE THREAD

**Issue by chrisidakwo** [PostgresApp/PostgresApp#462]
Recently, I've been working much more with Linux systems and really do miss this software. What will it take to get it on Linux? The Ubuntu distro, precisely.

**Comment by jakob** [comment]
I guess a team of two or three full time developers might be able to port it in a year or two. Not sure who would pay for them, though?

We have no plans to expand to other platforms. We occasionally get requests, but we're already struggling to support a single platform -- I'm not sure how we could expand to other platforms without neglecting the Mac version.

**Comment by jakob** [comment]
Oops, I just figured out that this is about Postgres.app. In my reply above I thought that this request was about Postico.

Porting Postgres.app to Linux should be doable. But what exactly are you looking for? Ubuntu comes with apt-get, and it's pretty easy to install different versions of PostgreSQL on Ubuntu.

Which specific features of Postgres.app are you missing on Ubuntu?

**Comment by alexanderadam** [comment]
Oh, may I ask why this issue was closed?
Was it closed by accident or does PostgresApp have Linux support now? :thinking:

**Comment by jakob** [comment]
Sorry, I didn't know someone was watching this issue.

I was just going through old issues and closed issues that have been resolved or that are no longer relevant.

We don't have any plans for working on a Linux version of Postgres.app, I don't know of anybody else who would work on a Linux version, and there is no interesting dicsussion in this issue, so I closed it.

**Comment by alexanderadam** [comment]
Ah, but it is technically still an _unsolved_ issue, isn't it?
And if I understand this correctly, you would also accept a PR in general, right?
So there's no real disadvantage of leaving this issue open, or am I missing something?
