### ISSUE TITLE
Add support for postgis with mvt support

### ISSUE THREAD

**Issue by gerbsen** [PostgresApp/PostgresApp#463]
The new PostGIS version supports the [MVT format](https://www.mapbox.com/vector-tiles/specification/) but you need to compile PostGIS with `libprotobuf-c`. Could this be added?

(I'm currently trying to install this with `brew` but somehow this is not picked up the install)

**Comment by mhkeller** [comment]
fyi duplicate of https://github.com/PostgresApp/PostgresApp/issues/412

**Comment by jakob** [comment]
There's a beta with support for MVT out now! See #412 for details.

Closing this since it is a duplicate.
