### ISSUE TITLE
pg_upgrade done, but new cluster not showing in sidebar?

### ISSUE THREAD

**Issue by wellsoliver** [PostgresApp/PostgresApp#464]
Using version 10, followed the instructions [here](https://postgresapp.com/documentation/migrating-data.html) -- the new v10 cluster is created, but it's not showing in the GUI app's sidebar for starting. Any ideas? This was all done from the command line.

**Comment by jakob** [comment]
Did you create the new cluster with Postgres.app or from the command line?

If you created the cluster manually, you can just add it with the "+" button below the sidebar, and provide the path of the data directory. Postgres.app will only initialize a new cluster if the data directory is empty -- if you provide an existing data directory, it'll show up in the sidebar.

**Comment by wellsoliver** [comment]
lol, that was easy: just plus'ed it anyway even though yes I created it manually. It added just fine.
