### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by mhkeller** [PostgresApp/PostgresApp#467]
The documentation provides [great walkthroughs](https://postgresapp.com/documentation/remove.html) on how to remove other installs of postgres but I don't see anything on how to uninstall this app. Because of the lack of libprotobuf-c support at the moment (https://github.com/PostgresApp/PostgresApp/issues/412), I need to install using brew but I'm a little worried about messing up my install. 

What's the safest way to remove this app and migrate to homebrew?

**Comment by mhkeller** [comment]
Thanks! Do I have to do anything for the command line tools?

**Comment by jakob** [comment]
Oh right, if you followed the instructions from the website, there will be a file in `/etc/paths.d`. You can remove it. It won't have any effect if you deleted Postgres.app, but you might as well clean up the clutter :)

**Comment by mhkeller** [comment]
Thanks. I'm currently exploring some other workarounds for #412 like running it in docker before I go the uninstall route since it's otherwise such a great way to use postgres.

**Comment by jakob** [comment]
If you know what you are doing, there's no problem with running multiple versions of PostgreSQL on your Mac. (For example, we use docker images and Postgres.app side by side for testing Postico)

All you need to make sure is that the servers are running on different ports, and that you are using the correct version of tools like pg_dump (there can be some gotchas even though they are usually compatible)

**Comment by mhkeller** [comment]
Thanks for all the info! Feel free to close this issue.
