### ISSUE TITLE
hello. I am trying to setup the postgres sql but its givinf me error of server startup failed. Can someone please help me on this issue. Thanks

### ISSUE THREAD

**Issue by zohaibejaz** [PostgresApp/PostgresApp#468]
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv4 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  could not bind IPv6 socket: Address already in use
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
WARNING:  could not create listen socket for "localhost"
FATAL:  could not create any TCP/IP sockets
LOG:  database system is shut down

**Comment by jakob** [comment]
There might already be another PostgreSQL server running on your Mac. Try uninstalling other PostgreSQL installations: https://postgresapp.com/documentation/remove.html

**Comment by zohaibejaz** [comment]
Thanks a lot. i wasted 3 hours yesterday. but now i figured that that out because of your help. Appreciated a lot.
