### ISSUE TITLE
Support placing the app in ~/Applications

### ISSUE THREAD

**Issue by csuhta** [PostgresApp/PostgresApp#469]
~/Applications is an officially blessed place to put .app bundles for your specific macOS account. If you create ~/Applications, macOS will automatically give it a special icon and permissions.

Users in restricted environments may not be able to put applications in /Applications (especially if they are using them for development work). 

Is there a specific reason that Postgres.app can't work here?

<img width="420" alt="dncaocyxrf" src="https://user-images.githubusercontent.com/769083/46051823-3aca4100-c109-11e8-98ee-b2d236fa21f7.png">

**Comment by jakob** [comment]
Yes. All the dynamic libraries included with Postgres.app are linked using absolute paths. This is necessary to make sure that other stuff compiled against Postgres.app provided libraries (such as the pg ruby gem, or psycopg, etc) works as expected.

We could use relative paths for the dylibs (using @rpath), but then you'd need to use custom CFLAGS when compiling stuff, which is really really hard to get right, and doesn't work well with extension managers like ruby gems, pip, etc.
