### ISSUE TITLE
Postgresql 11 requires 10.12 

### ISSUE THREAD

**Issue by marcvanolmen** [PostgresApp/PostgresApp#472]
hi,

I just looked at the make for PostgreSQL and I notice it requires min 10.12 but releases tab in this GitHub project  is saying ```Postgres.app requires macOS 10.10 or later.```. I notice that configure file for PostgreSQL is asking for clock_gettime which macOS only added in 10.12 is that the reason? is it possible to change that?

thanks

marc

**Comment by jakob** [comment]
We're planning to raise the system requirements for Postgres.app to macOS 10.12 as soon as PostgreSQL 11 is released. Besides PostgreSQL itself, I also failed to build libgdal on 10.11 and the latest version of ICU.

I'll continue to provide older versions of PostgreSQL for earlier versions of macOS, but if you want Postgres.app with PostgreSQL 11 you'll need to upgrade to a newer version of macOS.

Do homebrew or MacPorts support PostgreSQL 11 on macOS 10.10?

**Comment by marcvanolmen** [comment]
Jakob I haven't tried, I'm building postgresql for use in my own app and always was using your scripts as a source, so I was just surprised that Postregsql went from 10.7 to 10.12, big leap... I don't think there is a quick workaround .

**Comment by marcvanolmen** [comment]
Today I looked at the binaries you can download from postgresql enterprisedb is: https://www.enterprisedb.com/download-postgresql-binaries for postgresql 11
and it seems they support older version of macOS 

```
otool -l ./pgsql/bin/psql
...
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      sdk 10.9
Load command 10
...
```

currently the only way to do this I think would be install a macOS 10.9 computer and compile on that platform, because the usual setting the environment variables: 

```
export MACOSX_DEPLOYMENT_TARGET=10.9
export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk
export CPU_ARCH=x86_64
This doesn't seems to work in Xcode 9.4
```

**Comment by jakob** [comment]
I don't know how EnterpriseDB did it. Building on old versions of macOS is generally the most reliable way to avoid compatibility issues. But you can build on newer versions of macOS, you just need to copy the SDK from an old version of Xcode.

Anyway, the reason why I decided to raise the requirement is that 4 packages were having issues (libgdal, ICU, PostgreSQL itself, and plv8). I just didn't have enough time to figure out how build all that for older OS...
