### ISSUE TITLE
Trouble with installation

### ISSUE THREAD

**Issue by manieshablakey** [PostgresApp/PostgresApp#474]
Hi,

I've had various issues installing postgres. Getting the error message below but not sure how to proceed. Can you please help? Thanks.

<img width="630" alt="screen shot 2018-10-25 at 6 08 14 pm" src="https://user-images.githubusercontent.com/40118442/47493236-a89a8300-d803-11e8-925c-d455666fb4c5.png">
<img width="630" alt="screen shot 2018-10-25 at 6 08 14 pm" src="https://user-images.githubusercontent.com/40118442/47493278-c5cf5180-d803-11e8-9c41-d9d07fe29845.png">

**Comment by jakob** [comment]
From the docs: (https://postgresapp.com/documentation/troubleshooting.html)

> #### Could not translate host name "localhost", service "5432" to address: nodename nor servname provided, or not known
> Usually this error is caused by broken `/etc/hosts` file.
> The problem could be a missing `localhost` entry, syntax errors or incorrect whitespace.
> 
> For reference, here is what this file should look like by default on macOS:
> 
	##
	# Host Database
	#
	# localhost is used to configure the loopback interface
	# when the system is booting.  Do not change this entry.
	##
	127.0.0.1	localhost
	255.255.255.255	broadcasthost
	::1             localhost

**Comment by manieshablakey** [comment]
Hi- sorry, but what does that mean? I'm fairly new to programming. How would be missing localhost entry occur?
Or how do I figure out if its one of the other errors? Thanks.

**Comment by jakob** [comment]
You've probably edited your `/etc/hosts` file.

Type `cat /etc/hosts` in Terminal to see the contents of the file.

If it doesn't look like the file above, it might be broken.

You can edit the file with a Text Editor.

**Comment by manieshablakey** [comment]
Hi- just typed that in but it doesn't bring up anything... Any advise on how to proceed? Thanks.

<img width="303" alt="screen shot 2018-10-25 at 6 34 38 pm" src="https://user-images.githubusercontent.com/40118442/47494630-fd8bc880-d806-11e8-9c3d-c94a4ab7e885.png">

**Comment by jakob** [comment]
Looks like the file is empty.

You can edit the file like this:

1. Type `sudo nano /etc/hosts` in Terminal
2. Paste the following text:
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
```
3. Press ctrl-O, then enter to save your changes
4. Press ctrl-X to exit
5. Now type `cat /etc/hosts` again to make sure that the hosts file is now fixed

**Comment by manieshablakey** [comment]
It worked- thank you. Much appreciated!
