### ISSUE TITLE
Switching from Homebrew to Postgres.app, and can't connect

### ISSUE THREAD

**Issue by mdespuits** [PostgresApp/PostgresApp#48]
I just recently switched from my Homebrew installation (which was a bit of a pain to manage) to PostgresApp. For some reason, it seems to be trying to connect to homebrew's binary. 

```
$ psql
psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

and if I try and specify the host:

```
$ psql -h localhost
psql: could not connect to server: Connection refused
    Is the server running on host "localhost" (::1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?
could not connect to server: Connection refused
    Is the server running on host "localhost" (fe80::1) and accepting
    TCP/IP connections on port 5432?
```

And yes, it is attempting to use the right binary.

```
$ which psql
/Applications/Postgres.app/Contents/MacOS/bin/psql
```

I really need this to work, so any help would be greatly appreciated!

**Comment by ashrocket** [comment]
_Update Postgres App's config._  You most likely have something in basic which is telling `psql` to use sockets.
Edit `~/Library/Application\ Support/Postgres/var-9.5/postgresql.conf `  
or wherever you're Postgres App is getting it's configuration from, and set a valid value for
`unix_socket_directories=`
Then restart Postgres App..
http://iamvery.com/2013/06/17/postgresapp-with-unix-socket.html

**Comment by humancopy** [comment]
This is what helped me (mainly with getting Ruby to connect). Put it in your ```.bashrc``` or ```.bash_profile```.

 ```shell
export PGHOST=localhost
```

**Comment by rhys-vdw** [comment]
Thanks @humancopy! That worked for me.

**Comment by tathspts** [comment]
thanks @humancopy this worked like a charm
