### ISSUE TITLE
Using PGAdmin - Password Trouble

### ISSUE THREAD

**Issue by vindobonensis** [PostgresApp/PostgresApp#480]
Hello! 

I have to apologize right off the bat because I'm a total novice and this is probably a silly question, but I've been trying to find a solution for four and a half hours without success. 

I just downloaded PostgressApp on mac and it's working wonderfully but I literally have zero clue how to run it using commands. So I also downloaded the PgAdmin. However, this one asks me for the password for the user postgres, which I don't have. I tried leaving it blank. I tried modifying the .conf file (setting everything to 'trust') and I tried the ALTER USER postgres WITH PASSWORD command but that also didn't help. I'm also rather confused because the username ought to be my computer username and no postgres, right? 

I looked over the thread from some 9 days ago where someone had similar issues, but I didn't manage to apply much of it to me, because my problem is with a new installation and not with the update of an old one. 

I'm really sorry for bothering you with this issue!

**Comment by chrispysoft** [comment]
Hi!

You mix up the _database user_ (which is indeed "postgres"),
and the _client username_ for the connection to the server (which is the username of your computer);
no password required.

Everything you need to know and alternatives to pgAdmin
can be found on the [Postgres.app](https://postgresapp.com) website.

Don't hesitate to reply or create an issue if you still run into problems!

**Comment by jakob** [comment]
Hi @vindobonensis!

Did you manage to get it running already?

If not, I have a few more tips:

When you open Postgres.app, what does it say? Here's what it should look like if the server is running:
<img width="713" alt="bildschirmfoto 2018-11-19 um 09 07 49" src="https://user-images.githubusercontent.com/198305/48693768-cf699080-ebda-11e8-89f1-f6b6a774bc04.png">

As soon as it is running, you should be able to connect with pgAdmin 4. For the user name, you can use either "postgres" or your system user name (Postgres.app creates two users when initializing the database). By default, the PostgreSQL server should be configured to not require a password and trust connections from localhost.

Here's what the connection settings in pgAdmin 4 should look like:
<img width="531" alt="bildschirmfoto 2018-11-19 um 09 05 47" src="https://user-images.githubusercontent.com/198305/48693920-2c654680-ebdb-11e8-9239-21a09bec1455.png">
<img width="528" alt="bildschirmfoto 2018-11-19 um 09 05 52" src="https://user-images.githubusercontent.com/198305/48693929-31c29100-ebdb-11e8-91f0-78d59492f8f6.png">

If you still get an error stating that the password authentication has failed:
 - check the host name / port is correct
 - check the server log (in Postgres.app, go to Server Settings... -> Log file -> Open). What does it say why the authentication failed?
 - if you have modified pg_hba.conf, make sure to restart the server
 - make sure there is only one PostgreSQL server running on your host. You can do use the following command to find PostgreSQL servers running on your Mac: `ps ax | grep postgres`. Expected output: 
<img width="1105" alt="bildschirmfoto 2018-11-19 um 09 16 23" src="https://user-images.githubusercontent.com/198305/48694135-cc22d480-ebdb-11e8-8bdd-1374b269d2a7.png">

If you find the cause of your issues, please let us know. It would also be great to hear if there's anything we can do to improve our docs, etc.

**Comment by jakob** [comment]
@vindobonensis Did you find the solution to your problem? If so, please let us know!
