### ISSUE TITLE
role USER does not exist

### ISSUE THREAD

**Issue by manieshablakey** [PostgresApp/PostgresApp#481]
Hello,

I've had to install and uninstall postgres several times now due to various issues. I've now installed both postegres.app and psequel. However, when I typed in 'psql' or '\l' on the command line, I kept getting 'FATAL role user does not exist' errors (screenshot attached)
I've looked on stackoverflow and tried numerous options but none have worked for me.
Can you please help? Thanks!

<img width="571" alt="screen shot 2018-11-22 at 11 20 07 am" src="https://user-images.githubusercontent.com/40118442/48879940-f97da700-edc2-11e8-9e80-a899424b3f03.png">

**Comment by jakob** [comment]
OK. First of all, let's make sure that you are running the PostgreSQL server included with Postgres.app. You can do that with the command `ps ax | grep postgres`.

The output should look like this:

```
$ ps ax | grep postgres
81790   ??  S      0:01.44 /Applications/Postgres.app/Contents/Versions/11/bin/postgres -D /Users/jakob/Library/Application Support/Postgres/var-11 -p 5432
81792   ??  Ss     0:00.03 postgres: checkpointer       
81793   ??  Ss     0:00.30 postgres: background writer       
81794   ??  Ss     0:00.26 postgres: walwriter       
81795   ??  Ss     0:01.31 postgres: autovacuum launcher       
81796   ??  Ss     0:04.23 postgres: stats collector       
81797   ??  Ss     0:00.02 postgres: logical replication launcher       
90641 s002  S+     0:00.01 grep postgres
```

From the first line you can see which version of PostgreSQL is running, and if the data directory is what you expect.

Secondly, it could be that Postgres.app failed to create a user with your name. In that case:

1. Connect to PostgreSQL with the user `postgres` like this: `psql -U postgres`
2. Then list all databases with the command `\l` (backslash-ell)
3. If no database with your name exists, type `create database maniesha;` (don't forget the semicolon)
4. Then list users with the command `\du`. If no user with your name exists, create a user with the command `create user maniesha superuser;`. If a user exists, but it's not a superuser, you can change that with the command `alter user maniesha superuser;`.
5. To get help for other commands in psql, type the command `\?`
6. To exit psql, press Ctrl-D

Hopefully that's enough to get you started. For more info, make sure to review the PostgreSQL documentation. It is very comprehensive:
https://www.postgresql.org/docs/current/index.html

**Comment by manieshablakey** [comment]
Hello,

Apologies for the belated reply and thanks for your clear instructions My name exists as a superuser when I checked on the command line. However, when I used DataGrip to create a database, I receive the fatal role 'Maniesha' does not exist error message (as attached) and it won't let me connect to the database. I'm looking through the documentation for PostgreSQL as well to figure it out better. But why will it not let me connect? Thanks again for your help.

<img width="980" alt="screen shot 2018-11-26 at 2 35 20 pm" src="https://user-images.githubusercontent.com/40118442/48996856-834eac80-f102-11e8-9df0-9a6b8e5dfa88.png">

<img width="466" alt="screen shot 2018-11-26 at 2 30 53 pm" src="https://user-images.githubusercontent.com/40118442/48996682-d6742f80-f101-11e8-9f31-6167817e2f5f.png">

**Comment by jakob** [comment]
Can you try executing `ps ax | grep postgres` at the command line and post the output?

**Comment by manieshablakey** [comment]
Hi- thanks again for your help. I fiddled around with it some more and realized where I went wrong. Should have entered name uppercase...
Really appreciate your quick reply.

**Comment by ramit141195** [comment]
Can you post exactly what did you do? None of the solution is working for my scenario.
