### ISSUE TITLE
How to run older postgres version

### ISSUE THREAD

**Issue by morenoh149** [PostgresApp/PostgresApp#484]
I downloaded the 
https://github.com/PostgresApp/PostgresApp/releases/download/v2.2/Postgres-2.2-9.5-9.6-10-11.dmg bin and installed it. When running the application I don't see how to specify postgres v10. How can I run an older postgres engine version?

**Comment by jakob** [comment]
Click the icon in the bottom left to show the sidebar, then click the + icon to add a new server.


<img width="713" alt="bildschirmfoto 2018-11-28 um 19 15 35" src="https://user-images.githubusercontent.com/198305/49172738-20e3ef00-f342-11e8-8fc9-38ac2411d11e.png">

**Comment by morenoh149** [comment]
very nice now I can run many pg version on different ports or easy turn them on or off 
<img width="621" alt="screen shot 2018-11-28 at 5 43 33 pm" src="https://user-images.githubusercontent.com/587438/49187354-37d01480-f335-11e8-8554-de6aae0153f9.png">
