### ISSUE TITLE
Update to PostgreSQL 11.1

### ISSUE THREAD

**Issue by kanwei** [PostgresApp/PostgresApp#493]
PG 11 has a pretty critical segmentation fault bug with DELETE statements that's fixed in 11.1. Any chance we could get an update? Thank you!

**Comment by jakob** [comment]
PostgreSQL 11.2 will be released tomorrow. Postgres.app will be updated in time.

**Comment by jakob** [comment]
We've just released Postgres.app 2.2.2 with PostgreSQL 10.2

To update, please open Postgres.app, and select "Check for updates" from the Postgres menu.

Sorry for the delay!
