### ISSUE TITLE
after creating my first database, my password to use it is always wrong

### ISSUE THREAD

**Issue by ErikUnique** [PostgresApp/PostgresApp#494]
I have a 2016 Macbook Pro with Mojave 10.14.13

I downloaded PostGresApp 2.2.2 and moved it to my applications directory and started it.

I also ran the terminal command to give myself terminal command line tools, which seemed to work.     

"sudo mkdir -p /etc/paths.d && echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp"

If I open a regular mac terminal and type:  "createdb -U postgres testdb1" then it seems to successfully create the database, because if I type it again, it says "database already exists".

Unfortunately, I cannot get anything else to work.  If I try and use the "psql \l" command in the mac terminal,  it always asks for my password and then it always says my password is wrong, and if I don't type anything for the password then it says "psql: fe_sendauth: no password supplied" and doesn't work.

I also can't get dbVisualizer to connect to the database with or without a password.

As far as I can tell, there is some type of userName and password that is supposed to be associated with the database that is for some reason never getting initialized and I can't figure out how to fix it.  I read somewhere that my administrator username and a blank password should be the default, but that doesn't work. 

I tried playing around with the pg_hba.conf file as other threads have mentioned but couldn't get anything to change.

Also, for some reason it says "Empty data directory" at the top of my postgresApp window and doesn't show any visual representation of the databases.  I only know that the databases exist because if I try to create them again it says the name is already in use.

I've googled and found people that had similar issues but none of their solutions seem to work for me.

<img width="712" alt="screen shot 2019-02-14 at 9 33 01 pm" src="https://user-images.githubusercontent.com/10189819/52836620-2d095e00-30a0-11e9-80d9-9c0fa8fcf9c9.png">

<img width="682" alt="screen shot 2019-02-14 at 9 45 42 pm" src="https://user-images.githubusercontent.com/10189819/52837039-03e9cd00-30a2-11e9-8ab3-2456f61e9764.png">

**Comment by ErikUnique** [comment]
I installed regular postgres and then tried to uninstall it before installing postgresApp, I wonder if some file fragment is left over and messing it up.

**Comment by jakob** [comment]
It sounds like you already have a PostgreSQL server running on your Mac.

You can use this command to check:
```bash
ps ax | grep postgres
```

You may want to uninstall the other PostgreSQL server before running Postgres.app.

Check these page in the docs: [Removing other Installations](https://postgresapp.com/documentation/remove.html) 

(It is of course possible to run multiple installations of PostgreSQL, but it doesn't sound like that's what you want to do)

**Comment by jakob** [comment]
I assume everything works for you now? I'm closing this issue -- feel free to reopen if you need further assistance.
