### ISSUE TITLE
No docs on how to install PostgresApp with PG 9.4

### ISSUE THREAD

**Issue by DaniG2k** [PostgresApp/PostgresApp#495]
I'd like to install PostgresApp to manage multiple PostgreSQL installs on my Mac. I currently require PG 9.4 for work but would like to have 11 for other projects. I see that I can easily create a PG 11 database with PostgresApp but am not able to find any documentation on how to install older versions like 9.4. Is this possible?

**Edit:**
Never mind, saw the docs  👀  Just had trouble finding them.

**Comment by c0ze** [comment]
@DaniG2k I am having trouble finding the docs as well, where are they ?

All I could find was this, which doesnt specify how to init older versions of PG

https://postgresapp.com/documentation/

I have the latest postgres app with 11, 10, 9 included, I want to init a 9.5 PG.

thanks !

**Comment by c0ze** [comment]
allright, it seems you need to expand the left pane on the app, with the icon in the left bottom corner. There you can use the plus button, which will give you a prefs screen where you can configure PG version.

<img width="625" alt="Screen Shot 2019-03-29 at 13 58 18" src="https://user-images.githubusercontent.com/1049148/55210463-e5dbc480-522a-11e9-8e2a-ceaad0202462.png">

**Comment by DaniG2k** [comment]
Yep if you install Postgres.app with PostgreSQL 9.5, 9.6, 10 and 11 support then all you need to do is open the left pane and add a Postgres version from there.

I was trying to install PostgreSQL 9.4 as well as 11, which doesn't come outside the box in the 9.5-11 version that is downloadable from the website. For that, I had to follow these instructions:

<img width="782" alt="Screenshot 2019-03-29 at 12 19 51" src="https://user-images.githubusercontent.com/1641910/55211057-fbe28880-521c-11e9-98d3-7001b5482f35.png">
