### ISSUE TITLE
Postgres 2.2 binaries not found on Mojave

### ISSUE THREAD

**Issue by bobbdelsol** [PostgresApp/PostgresApp#498]
I have Mojave and when installing postgress 2.2, i get binaries not found.  under the app server it shows the location of the old postrgres app.  Must be a config file it's looking at

**Comment by jakob** [comment]
This means that you have a version of Postgres.app that doesn't include the PostgreSQL binaries for your data directory.

You have a few possibilities:

- download a version of Postgres.app that includes the PostgreSQL version of you data directory

- create a new data directory (click the button in the lower left to show the sidebar, then click the plus button)

- migrate your data directory to a newer version (see docs for details)
