### ISSUE TITLE
upgrade documentation

### ISSUE THREAD

**Issue by martinmueller39** [PostgresApp/PostgresApp#501]
I accidentally closed an issue I raised. Here it is again. The Postgres documentation has an elaborate description of pg_upgrade that manages the transfer from one major version to another, e.g. 10 to 11.

Is there a postgres.app friendly version of doing this. Specifically, I have 10.5. installed via postgres.app 2.1.  There is an automatic upgrade feature, but it's unclear whether that applies to postgres.app or the database or both. I think it's just the first. It would be useful to have clear documentation within the postgres.app environment of how to go from one major version to the next.

**Comment by jakob** [comment]
Yes, we should probably improve the docs to make it more clear. The automatic update funtion only updates the PostgreSQL binaries, it does not update your data directory.

To upgrade from version 10 to version 11:
1) Use pg_dumpall to create a dump of your database
2) Download a new version of Postgres.app with PostgreSQL 11
3) Restore the dump

**Comment by martinmueller39** [comment]
Forgive me for asking another naïve set of questions: Can  I 1)  install Postgres 11 with the postgres.app without affecting the current application in any way, 2) use  pg_dumpall to export the current database, 3) import pg_dumpall into Postgres11, 4), check whether the new application works, 5) delete Postgres 10 If #4 works.

Yes would be a long enough answer, unless I missed something

**Comment by jakob** [comment]
Looks like I never replied to this issue. Sorry!

Yes, that is possible. You just need to download a version of Postgres.app that includes both the old and new version.
