### ISSUE TITLE
Add specific version of Postgis for 10.6

### ISSUE THREAD

**Issue by dominijk** [PostgresApp/PostgresApp#502]
I have a db created with a homebrew version of postgres. This used Postgres 10.6 with Postgis 2.5 when I open in Postgres.app (having removed homebrew versions) I hit the error

`PostgreSQL said: could not access file "$libdir/postgis-2.5": No such file or directory` is there a way to run 10.6 with Postgis 2.5? 

Something like this https://info.crunchydata.com/blog/upgrading-postgis-on-centos-7 

EDIT:  Using Postgres version 10.7 that comes with the app this comes with Postgis 2.4.6.  When I run

`ALTER EXTENSION postgis UPDATE;`

I get 

`ERROR:  extension "postgis" has no update path from version "2.4.6" to version "2.5.1"`

**Comment by jakob** [comment]
Hi, sorry for the late response. Unfortunately we don't support different combinations of PostgreSQL / PostGIS versions.

If you want to migrate from Homebrew to Postgres.app (or vice versa), the only way we support that is with a dump/restore.

Reusing the same data directory is not something I would recommend (it's easy to make data directories that are incompatible in hard to detect ways, eg. index collations, so it's something that you should only do if you really know what you are doing)
