### ISSUE TITLE
Empty string not accepted as "no password"

### ISSUE THREAD

**Issue by ejeklint** [PostgresApp/PostgresApp#505]
If I create a connection with

```swift
let password = ""
```

and use it in my connection, PostgresAPP will take it for a real password and error is thrown. I think this wrong, "" should count as "no password". :)

**Comment by jakob** [comment]
I'm not sure how this is related to Postgres.app. Could you explain in more detail what software you are using and what you are trying to do?

**Comment by jakob** [comment]
I'm closing this issue for now. Feel free to reopen if you have more information to add!
