### ISSUE TITLE
Contrib module in PostgresApp?

### ISSUE THREAD

**Issue by pankajkgarg** [PostgresApp/PostgresApp#51]
I installed PostgreSQL from PostgresApp, but when I am trying to open PgAdmin, its complaining about the missing postgresql-contrib modules.  Are they included in PostgresApp, or do they need to be installed some other way. I have tried everything so far, but couldn't get the contrib module installed. And homebrew was of no help whatsoever.

**Comment by skwaugh** [comment]
Any change to this?

**Comment by jakob** [comment]
We have been building PostgreSQL with most contrib extensions for years, are you looking for a specific extension?
