### ISSUE TITLE
Automatic Update to 2.2.4 removes old versions

### ISSUE THREAD

**Issue by sprestel** [PostgresApp/PostgresApp#510]
I used the app with old (version 9) Postgres servers. The automatic download & install to 2.2.4 removed my old servers.

**Comment by sprestel** [comment]
I had to download the version with servers of version 9 manually after that.

**Comment by jakob** [comment]
@sprestel Sorry about that -- this was a bug in Postgres.app 2.2.3 (it checked the wrong Sparkle feed). I've added a note in the changelist displayed by sparkle -- I hope that people read those notes.

Apart from that I'm not sure what to do.

**Comment by robababa** [comment]
Had this same problem upgrading 2.2.3 to 2.2.5.  @jakob, are you saying that this has been fixed for versions after 2.2.3?

**Comment by tbussmann** [comment]
@robababa as far as I can see, this issue affects updates originating in version 2.2.3 with PostgreSQL 9.5-9.6-10-11 by offering an update to the latest version with only 11. From 2.2.4 onwards the right feed is checked again. So please update manually once.
