### ISSUE TITLE
Fatal database "xxx" does not exist?

### ISSUE THREAD

**Issue by Kishorekonnect** [PostgresApp/PostgresApp#511]
I am trying to create a connection whenever my server is restarted(locally). But I get the below error when I am trying to login for the first time,

org.postgresql.util.PSQLException: FATAL: database "config_ka" does not exist

And below is the code where I am trying to create a new connection,

     public Jdbc_con_mysql() {		
	  initializeConnectionPool();
	 }

       private void initializeConnectionPool()
	 {
	  while(!checkIfConnectionPoolIsFull())
	  {
		   Connection con = createNewConnectionForPool();
		   availableConnections.add(con);
		   connectionstatus.put(con, new Date());
	  }
	  wait_time = get_wait_time(availableConnections.get(0));
	 }

         private Connection createNewConnectionForPool()
	 {
	  Configuration_mysql config = Configuration_mysql.getInstance();
	  try {
	       Class.forName(config.DB_DRIVER);
	   
	   Connection connection = (Connection) DriverManager.getConnection(
			   config.DB_URL, config.DB_USER_NAME, config.DB_PASSWORD);
	   connection.setSchema(config.DB_SCHEMA);
	   
	   return connection;
	  } catch (ClassNotFoundException e) {
		  logger.error(e);
	  
	  } catch (SQLException e) {
		  logger.error(e);
	   
	  }
	  return null;
	 }

And "config_ka" is my schema name but I wonder why it is showing it as Database. My database and schemas are there in my DB. Please avoid the variable declarations containing SQL and so on because I have just migrated from MySQL to Postgres. Please suggest a solution and Thanks in advance.

I have gone through the solutions in the below issue but no use,
(https://github.com/PostgresApp/PostgresApp/issues/139)

**Comment by jakob** [comment]
I'm not familiar with java, but from glancing at your code, the most likely problem is that `config.DB_URL` is wrong. PostgreSQL connection URLs usually look like this:

`postgresql://HOST:PORT/DATABASE?param=value&param2=value2`

For Postgres.app on localhost, you can usually just use
`postgresql://localhost`

or I could also use
`postgresql://localhost/jakob` (where `jakob` is my system user name, and Postgres.app automatically created a database with the same name)

**Comment by Kishorekonnect** [comment]
What happens if I have my DB URL like this, **jdbc:postgresql://HOST:PORT** and the value I pass in config.DB_URL is same as above and then config.DB_USER_NAME contains my username and config.DB_PASSWORD contains the desired password  for that DB.

**Comment by jakob** [comment]
The url `jdbc:postgresql://HOST:PORT` does not specify a database, so the default is to use the same as the user name. I'd recommend trying to add the name of your database (`jdbc:postgresql://HOST:PORT/DATABASE`).

You might also want to review the JDBC driver docs for PostgreSQL:
https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by Kishorekonnect** [comment]
After adding database name to my DB_URL, it is showing the same error message by including the database name in error message. My error message is like,
**org.postgresql.util.PSQLException: FATAL: database "databasename/schemaname" does not exist**.

**Comment by jakob** [comment]
Then maybe the `setSchema()` call is wrong?

If that's not it, I'm afraid that I can't offer any further assistance. I use neither Java nor JDBC, so this is really not my speciality.

Please make sure you read the PostgreSQL docs that I linked to. Additionally, the Java documentation for JDBC / DriverManager (eg here: https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html) is probably also highly relevant.

If after reading the docs you still can't figure it out, my recommendation would be to ask someone familiar with Java / JDBC for assistance.

Please do let us know if you find a way to resolve your issue!

**Comment by Kishorekonnect** [comment]
Thanks for your suggestions. I will try to find the solution from the documentation you have suggested and once I find a solution, I will post it in this issue and close this one.
