### ISSUE TITLE
c++ dylib not found in Excel macos when -L to Postgresql libraries

### ISSUE THREAD

**Issue by fincerec** [PostgresApp/PostgresApp#512]

**Comment by fincerec** [comment]
I am compiling a Postgresql query in C in a .dylib to be called from VBA 7.1 in Excel for Mac V16.26. I copy the .dylib in folder /Users⁩/[user]/Library⁩/Containers⁩/com.microsoft.Excel⁩/Data⁩ and VBA report 

> Error detected
> Error: File not found: [file].dylib

I compile the .dylib with:

> $ clang++ -dynamiclib -std=c++11 [filename].c -I$(pg_config --includedir) -L$(pg_config --libdir) -lpq -o [filename].dylib

VBA calls all C and C++ functions I compile in .dylib's without problems, it only reports not finding the file when linking to Postgresql libraries.

**Comment by jakob** [comment]
Can you include the exact error message that you are seeing? Is it a linking problem, or something else?

For debugging linking problems, the command `otool -L` is very helpful (eg. `otool -L name-of-your.dylib`), so you can make sure all the library paths are correct.

**Comment by jakob** [comment]
Oops, it looks like you did include the error message. Sorry.

I'm not familiar with VBA, so I'm not sure why it would not find the file if you link against libpq. It sounds odd.

**Comment by fincerec** [comment]
otool -L [filename].dylib returns:

```
[filename].dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/libpq/lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.11.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```
Which seems to report no problems. Is there any other way to check the integrity of a .dylib file?

**Comment by jakob** [comment]
The first line shows that the dylib does not have an absolute path. I don't know how your dylib is linked / loaded, but this may be the cause of the issue. You can change the path of the dylib using `install_name_tool` like this:

```sh
install_name_tool -id /Users⁩/[user]/Library⁩/Containers⁩/com.microsoft.Excel⁩/Data⁩/[filename].dylib [filename].dylib
```

However, this alone is probably not enough, you probably also need to change the paths in other libraries that link with `[filename].dylib`, or recompile them so they automatically get the correct path from `[filename].dylib`.

**Comment by fincerec** [comment]
Thank you for your reply. I compiled the dylib by running:

> `clang++ -dynamiclib libTest.c -I$(pg_config --includedir) -L$(pg_config --libdir) -lpq -o libTest.dylib`

... as instructed in [https://postgresapp.com](https://postgresapp.com) under C, "How to connect". I compiled again and ran:

`install_name_tool -id /Users⁩/[user]/Library⁩/Containers⁩/com.microsoft.Excel⁩/Data⁩/libTest.dylib libTest.dylib`

... tested and got the same error:

<img width="421" alt="Screen Shot 2019-07-08 at 11 50 29 AM" src="https://user-images.githubusercontent.com/52426996/60819819-a6503d00-a176-11e9-8f24-34ecb90a17f5.png">

The most curious thing is that the same the dylib runs without problems in my other Mac computer - running the same version of Excel for Mac and VBA - but fails to run in the other Mac computer. 

Is there a way to confirm the path the dylib is using?

**Comment by jakob** [comment]
You can check in Activity monitor. Click on the app that uses the dylib, click on the "i" icon, then go to the section "Open Files and Ports" and you should see the paths of all dylibs that are loaded.

**Comment by jakob** [comment]
I googled a bit. Maybe you need to provide a full path in your VBA code?

https://answers.microsoft.com/en-us/msoffice/forum/all/libcdylib-not-found-in-mac-excel-2016-vba-code/91bba8a5-6179-445f-b097-fd9ea34971f6

**Comment by fincerec** [comment]
I am attaching what Activity Monitor reports for Microsoft Excel, it looks like it is looking at /Users/dopazoma/Library/Containers/com.microsoft.Excel/Data ... 

[Activity Monitor.txt](https://github.com/PostgresApp/PostgresApp/files/3369031/Activity.Monitor.txt)

As per the full path, tried that also using forward slash and colons, did not work either.

**Comment by fincerec** [comment]
I just ran the sub below:

```
Sub Sample()
    
    mydir = "/Users/dopazoma/Library/Containers/com.microsoft.Excel/Data/"

    strfile = Dir(mydir)

    Do While Len(strfile) > 0
        If Right(strfile, 5) = "dylib" Then
            Debug.Print strfile
        End If
        strfile = Dir
    Loop
    
End Sub
```

In the same file I'm trying to call the dylib and it prints out libTest.dylib, so the VBA returns the file in the directory.

**Comment by fincerec** [comment]
... and last, if I compile without linking to Postgresql in the .dylib, that is:

`clang++ -dynamiclib libTest.c -o libTest.dylib`

... Excel for Mac reports no problem and the function works like a charm. So it looks like linking to Postgresql libraries in the compilation of the .dylib makes it not visible for Excel for Mac when declared in:

`Private Declare PtrSafe Function TestF Lib "libTest.dylib" Alias "_Z6test_fPc" (ByVal Str As String) As Double`.

**Comment by jakob** [comment]
It sounds like the "file not found" message is misleading. Maybe there is a different problem.

Did you check `pg_config --includedir` and `pg_config --libdir` if there's anything funny there?

Maybe there's a problem with the architecture? The results of `lipo -info libTest.dylib`  and `lipo -info /usr/local/opt/libpq/lib/libpq.5.dylib` would be interesting.

**Comment by fincerec** [comment]
`pg_confir --includedir` and `pg_confir --libdir` look ok:

```
dopazoma$ pg_config --libdir
/usr/local/Cellar/libpq/11.3/lib
dopazoma$ pg_config --includedir
/usr/local/Cellar/libpq/11.3/include
```

When I run `lipo -info libTest.dylib` and `lipo -info /usr/local/opt/libpq/lib/libpq.5.dylib` I get the following output:

```
dopazoma$ lipo -info libTest.dylib
Non-fat file: libTest.dylib is architecture: x86_64
dopazoma$ lipo -info /usr/local/opt/libpq/lib/libpq.5.dylib
Non-fat file: /usr/local/opt/libpq/lib/libpq.5.dylib is architecture: x86_64
```

**Comment by jakob** [comment]
Did you really compile that all on the same machine, or did you change some stuff in the mean time?

The pg_config output looks like paths from homebrew, but the libpq.dylib path looks like it's from MacPorts (neither of which has anything to do with Postgres.app, by the way). Why would `libTest.dylib` end up linked to `/usr/local/opt/libpq/lib/libpq.5.dylib` if you compile with `-I /usr/local/Cellar/libpq/11.3/lib`?

I assume the lipo output is from the libTest that doesn't work. So what about the file that does work? Is that also a 64bit binary? Maybe Excel is still a 32bit binary and can't load 64bit dylibs.

**Comment by fincerec** [comment]
I compiled in the computer that reports the error, ran the macro and get the error again. Copied the .dylib [the same compiled in the first computer] to the second Mac computer and ran without problems. I just checked and file libpq.5.dylib does not exist in the computer that works, when I run `$ lipo -info /usr/local/opt/libpq/lib/libpq.5.dylib` it says '(No such file or directory)'. Directory /usr/local/opt/libpq/ does not exit in the computer that runs.

Is the libpq library I downloaded from Homebrew creating the problem? Should I uninstall the home-brew library and stick to the postgres.app version?

**Comment by jakob** [comment]
> Is the libpq library I downloaded from Homebrew creating the problem? Should I uninstall the home-brew library and stick to the postgres.app version?

I don't know. I just thought that it was odd that compiling with `-I/usr/local/Cellar/libpq/11.3/lib` would result in a binary linked with `/usr/local/opt/libpq/lib/libpq.5.dylib`.

If you don't use the homebrew installation, removing it would probably be a good idea, but I don't know why it would cause issues like this.

**Comment by fincerec** [comment]
> I don't know. I just thought that it was odd that compiling with -I/usr/local/Cellar/libpq/11.3/lib would result in a binary linked with /usr/local/opt/libpq/lib/libpq.5.dylib.

What should the binary be linked to when compiling with` /usr/local/Cellar/libpq/11.3/lib`?

**Comment by fincerec** [comment]
In an additional note, I symlink'd  `ln -s /usr/local/Cellar/libpq/11.3/bin/psql /usr/local/bin/psql` and that's why the binary gets linked to `/usr/local/opt/libpq/lib/libpq.5.dylib`.

**Comment by fincerec** [comment]
After brew uninstall postgresql, and brew uninstall libpq, 

`PATH="/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH"` 

solved my problem.
