### ISSUE TITLE
security alert

### ISSUE THREAD

**Issue by JaerenTredway** [PostgresApp/PostgresApp#513]
hi, I am getting this alert popup repeatedly: "Auto-update not configured. For security reasons, you need to code sign your application or sign your updates with a EdDSA key. See https://sparkle-project.org/documentation/ for more information." I ran 'find /Applications -name Sparkle.framework' in the terminal and it identified postgres.app as the only app I have that uses sparkle.

**Comment by jakob** [comment]
- Which version of Postgres.app do you have installed?

- which version of macOS are you on?
