### ISSUE TITLE
PostgresApp in different languages

### ISSUE THREAD

**Issue by posenato** [PostgresApp/PostgresApp#514]
Hi,
is it possible to have the app with different locales?
In some applications, I need to have all server messages in Italian.

Currently, with Version 2.3beta2 (57), even if I set LC_MESSAGES variable to 'it_IT.UTF-8',
all messages are in English.

Thnaks.

**Comment by jakob** [comment]
Unfortunately Postgres.app is not built with `--enable-nls`, so it does not support error messages in other languages.

**Comment by posenato** [comment]
> Unfortunately Postgres.app is not built with `--enable-nls`, so it does not support error messages in other languages.

Do you think that it is not possible to ask such a feature?

**Comment by jakob** [comment]
It's the first time that someone has requested this feature, so I'm not sure how popular this request is.

Postgres.app is already very big, and this would probably make the download size even larger, but I would need to check how much of a difference it makes.

Also, this might cause problems if we add it in a minor update, so even if we add it, we should probably only add it do version 12 (this is still in Beta, so people hopefully don't rely on it yet)

**Comment by posenato** [comment]
> It's the first time that someone has requested this feature, so I'm not sure how popular this request is.
> 
> Postgres.app is already very big, and this would probably make the download size even larger, but I would need to check how much of a difference it makes.
> 
> Also, this might cause problems if we add it in a minor update, so even if we add it, we should probably only add it do version 12 (this is still in Beta, so people hopefully don't rely on it yet)

I understand.  💯
