### ISSUE TITLE
Postgres.app with PostgreSQL 9.5, 9.6 and 10 (download page not found)

### ISSUE THREAD

**Issue by dmen600** [PostgresApp/PostgresApp#515]
The postgres.app download at the top of the "Releases for older mac's" section does not goes to a page not found git message.

**Comment by cappert** [comment]
https://github.com/PostgresApp/PostgresApp/blob/bd3fedb3f96433480609dc29614f6f4ec7cd3e0c/docs/_config.yml#L68

```diff
- https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.4/Postgres-2.1.7.dmg
+ https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.4/Postgres-2.1.8.dmg
```

**Comment by tbussmann** [comment]
thanks, fixed
