### ISSUE TITLE
server start causes kernel panic

### ISSUE THREAD

**Issue by ludwig-schmidt** [PostgresApp/PostgresApp#516]
Since two days the app is crashing my mac. Whenever i start the server my screen instantly turns black and shows this message: https://support.apple.com/library/content/dam/edam/applecare/images/en_US/osx/panic.png

After restart i get a crash report which doesn't really tell me anything about the problem (`panic(cpu 2 caller 0xffffff8015adb92d): Kernel trap at`..). 

Sometimes (not very often though) the server starts and the crash happens 30–60 seconds later. I tested this for a while now and it is clearly related to starting the postgresql server.

I already uninstalled the app and removed all related files (that i know of), restarted my mac (obviously) and deleted all databases and the database user.

Any help?

EDIT: 
I'm using version 2.2.4-11

**Comment by jakob** [comment]
It's pretty unlikely that PostgreSQL itself is causing kernel panics. My first guess would be that you either have a hardware problem, or that some 3rd party kernel extension is causing the problem.

- If you installed extra RAM, try removing one module at a time.

- Try running [Apple Diagnostics](https://support.apple.com/en-us/HT202731)

- Try turning off / uninstalling any software that loads a kernel extension, eg. firewall apps, virtualisation software etc.

**Comment by jakob** [comment]
Also:

> Since two days the app is crashing my mac.

Did Postgres.app work for you before? Did you install any new software on your Mac two days ago that could be causing this problem together with Postgres.app?

**Comment by ludwig-schmidt** [comment]
> It's pretty unlikely that PostgreSQL itself is causing kernel panics. My first guess would be that you either have a hardware problem, or that some 3rd party kernel extension is causing the problem.
You are right - the issue was caused by a faulty update of my firewall ("Little Snitch"). Updating seems to resolve it. 
Thank you very much!

**Comment by jakob** [comment]
Thanks for the followup, I'm glad you found the cause!
