### ISSUE TITLE
10.6

### ISSUE THREAD

**Issue by ruckus** [PostgresApp/PostgresApp#519]
For legacy reasons I need to run `10.6` (really I just need access to `pg_dump` to extract a 10.6 database from Amazon RDS). I see a legacy download for 10.5 and 10.7 but not 10.6.

Is it possible to get ahold of a 10.6 release?

Thanks.

**Comment by tbussmann** [comment]
To avoid confusion - are you talking about OS X 10.6 or PostgreSQL 10.6 if you refer to `10.6`? All current releases require OS X 10.7 at least, so I assume you're referring to the PostgreSQL version. If I read the history correctly, the Nov 2018 updates (which included version 10.6) have not been released by PostgresApp.
However, the client tools (like `pg_dump`) are fully backward compatible, even across major versions. You should consider to update at least to the latest minor version which is 10.10 as of writing.

**Comment by ruckus** [comment]
My apologies for the confusion. Yes I was referring to Postgres 10.6.

> However, the client tools (like pg_dump) are fully backward compatible, even across major versions. You should consider to update at least to the latest minor version which is 10.10 as of writing.

Agreed, and I thought this was the case. I tried Postgres.app 10.9 and tried to do a pg_dump against an Amazon RDS instance running Postgres 10.6 and RDS gave me a version-mismatch error and refused to do the dump.

Normally you're correct in that pg_dump is backwards-compatible but it seems like RDS has a non-standard version of PG running and they are enforcing these versions. :(

**Comment by tbussmann** [comment]
Oh, that's a pity. I was not aware of the specifics of the Amazon implementation. I'm wondering how the server is actually able to detect the version of the client at all.

**Comment by jakob** [comment]
@tbussmann Yes, I think I forgot to build the November 2018 releases. I'm sorry about this.

@ruckus In any case this sounds odd. AFAIK pg_dump does not send it's version to the server, so I am not sure how RDS would reject it based on the version number.

pg_dump verifies the version locally, and a version mismatch error should occur only if:
1) The major version of the server is less than 8
2) The major version of the server is newer than the major version of pg_dump

Could you try executing `SHOW server_version_num` on the RDS server? pg_dump 10.9 should support versions from 80000 to 100099 (see [pg_dump.c](https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dump.c#L732)

Can you also try to call `pg_dump -V` from the command line to make sure you are using the correct version of pg_dump?

Can you provide any further details (eg. the command line options for pg_dump that you are using, and the full text of the error message)?

**Comment by ruckus** [comment]
Hi @jakob thanks for the help.

`/Applications/Postgres-225.app` is a download of Postgres.app v2.2.5

> Could you try executing SHOW server_version_num on the RDS server? pg_dump 10.9 should support versions from 80000 to 100099 (see pg_dump.c

I'm having trouble running `psql` and getting the `dyld: lazy symbol binding failed: Symbol not found: _PQsetErrorContextVisibility` error; so I cannot run `SHOW version`, but the RDS console says *Engine Version: 10.6*

> Can you also try to call pg_dump -V from the command line to make sure you are using the correct version of pg_dump?

```bash
$ "/Applications/Postgres-225.app/Contents/Versions/10/bin/pg_dump" -V
pg_dump (PostgreSQL) 10.10
```

> Can you provide any further details (eg. the command line options for pg_dump that you are using, and the full text of the error message)?

```bash
$ "/Applications/Postgres-225.app/Contents/Versions/10/bin/pg_dump" -Fc --host=.... -U ..snip.. -W licensebot
pg_dump: server version: 10.6; pg_dump version: 10.10
pg_dump: aborting because of server version mismatch
```

Crazy eh?

**Comment by jakob** [comment]
Postgres.app doesn't work when it is renamed.

All the binaries inside Postgres.app contain absolute paths to the other libraries. So if you run `pg_dump` from `/Applications/Postgres-225.app/Contents/Versions/10/bin/pg_dump` it'll look for libpq in `/Applications/Postgres.app/Contents/Versions/10/lib/libpq.5.dylib`. I wonder why it runs at all. It could be that it's loading an incorrect version of libpq from somewhere, which causes the weird behavior.

If you really want to use a pg_dump from a renamed Postgres.app, you would need to use `install_name_tool` to change the dynamic library load paths (of the binary you want to run and all the libararies loaded by it). But it's probably easier if you find a way to do it without renaming Postgres.app

**Comment by ruckus** [comment]
> I wonder why it runs at all. It could be that it's loading an incorrect version of libpq from somewhere, which causes the weird behavior.

Ah gotcha. Well, its "working" because there *is* a `/Applications/Postgres.app` which is my 9. series. I juggle multiple projects with different Postgres versions, the main project still on 9.4. So when I need to switch versions (projects) I physically rename `Postgres.app` to `Postgres9.app` and then change `Postgres10.app` back to `Postgres.app` and I just cycle thru this process as needed.

But ultimately there is always a `Postgres.app`.

This sounds like this boils down to me having a jacked workflow.

Thanks for the help.

**Comment by jakob** [comment]
@ruckus You can create a version of Postgres.app with all the versions of PostgreSQL that you need by just putting the folders from the /Contents/Versions together in one app -- it's explained at the bottom of the [Downloads page](https://postgresapp.com/downloads.html).

(But I don't know how long that is going to continue to work, since it breaks the code signature -- currently macOS only verifies it at first launch, but that may change)

**Comment by ruckus** [comment]
Oh thats super cool! Thanks for your help!

**Comment by ruckus** [comment]
I was able to connect via psql and run the version command:

```
psql (10.10, server 10.6)

licensebot=> show server_version_num;
 server_version_num
--------------------
 100006
(1 row)
```

**Comment by ruckus** [comment]
This did boil down to not having the `Postgres.app` version be 10.x at time of running `pg_dump`. Thanks again for the insight. I was able to do perform the pg_dump.
