### ISSUE TITLE
latest download package - no Pg 11, but 9.4

### ISSUE THREAD

**Issue by tomazbracic** [PostgresApp/PostgresApp#523]
In latest package that I wanted to download today - https://github.com/PostgresApp/PostgresApp/releases/download/v2.2.5/Postgres-2.2.5-11.dmg

When I start the app, it suggests Postgresql 9.4, with error code, that there is no binaries.
I wanted version 11. 

It might be my problem, but setup was clean.

**Comment by jakob** [comment]
You probably already have a PostgreSQL 9.4 data directory on your Mac, which is not compatible with PostgreSQL 11.

Just open the sidebar, and add a new server/data directory with PostgreSQL 11.
