### ISSUE TITLE
Restarting Postgres

### ISSUE THREAD

**Issue by luismieryteran** [PostgresApp/PostgresApp#524]
Hi there,

I changed the value of shared_buffers on the postgresql.conf file and as I understand it, I need to restart postgres. However, the command suggested for this purpose 'pg_ctl', is not available on my terminal window. Hints, anyone?

**Comment by jakob** [comment]
If you use Postgres.app, you can just click on the elephant icon in the menu bar and use the "Stop" / "Start" buttons to restart the PostgreSQL server.

**Comment by luismieryteran** [comment]
Got it! I did not think that that would be sufficient. Thanks, jakob!
