### ISSUE TITLE
Database Does Not Exist

### ISSUE THREAD

**Issue by brianlbradley** [PostgresApp/PostgresApp#525]
First I get :server does not support SSL connections.  Then I change it to sslmode:require. I get database "myname" does not exist. I set the $Path in the instructions.

**Comment by brianlbradley** [comment]
I created the db which I thought already exists. (polar-tor-7891) Then i get error relation "users" does not exist.  I then try and create the table users and get "users" already exist.  Going round in circles.

**Comment by jakob** [comment]
It would be helpful if you could add some more details to your question. As it stands I have no idea what software you are using. 

Also, please not that this is not a general PostgreSQL support forum. Is your problem related to [Postgres.app](https://postgresapp.com)?
