### ISSUE TITLE
Bundled version of postgis for pg12 not compiled with json-c 

### ISSUE THREAD

**Issue by chooban** [PostgresApp/PostgresApp#526]
Apologies if this is the wrong repository to file it with, so feel free to point me elsewhere if required!

I've installed the latest app to trial upgrading an app to pg12 and I'm getting an error related to postgis. If I attempt to use one of the postgis functions, I get this:

> You need JSON-C for ST_GeomFromGeoJSON

There's a helpful page on [the postgis site](https://postgis.net/docs/ST_GeomFromGeoJSON.html) to explain the issue. Is this something I should be dealing with myself after initializing my database, or should it be part of the pg database straight away. The same function works OOTB with a clean pg11 install.

**Comment by jakob** [comment]
Thanks for reporting this. It seems that I inadvertently built PostGIS without json-c. There was a change in the ./configure script, and I didn't see the error message.

I'll try to upload a new build of Postgres.app with json-c tomorrow.

**Comment by jakob** [comment]
Sorry for the delay. Everything ended up taking longer than expected.

You can download the new version of Postgres.app here: https://github.com/PostgresApp/PostgresApp/releases/tag/v2.3.1

(I'll update the download links on the website, and the sparkle files shortly)

**Comment by chooban** [comment]
> Sorry for the delay. Everything ended up taking longer than expected.
> 
No problem, that's software dev in a nutshell! ;)
