### ISSUE TITLE
2.2.5 is not seeing 2.3.2 as potential upgrade. 

### ISSUE THREAD

**Issue by ShereKahn** [PostgresApp/PostgresApp#536]
I am running 2.2.5 w/ postgresql 11 and I wanted to update to the latest 12 app release. 

When I do a "check for upgrade" I have a dialog box appearing that is telling me that "Postgres 2.2.5 is currently the newest version available."

As well, I was wondering if the check-for update would automatically migrate the databases ? 

Thanks

**Comment by jakob** [comment]
Thanks for the bug report. It looks like I forgot to push the updated appcasts for older versions of PostgreSQL. I really need to automate this completely, I always forget some step.

If you check for updates now, you should see an update to PostgreSQL 11.6

Note that Postgres.app will not automatically update across major versions (eg. to PostgreSQL 12). If you want to upgrade to PostgreSQL 12, you need to install a new version of Postgres.app and migrate your data manually.

If you want to start using PG 12, you have two options:

- Download a version of Postgres.app that supports multiple versions. Then you can run multiple servers with multiple versions of PostgreSQL at the same time (just open the sidebar in Postgres.app and click the + button to add a new server)

- If you just want to upgrade your server to from PostgreSQL 11 to 12, you need to do this:
   1. use pg_dump to export your data (with PG 11)
   2. quit Postgres.app, and replace the app with the new version
   3. Create a new PostgreSQL 12 server and initialize it (using the sidebar, see above)
   4. load the dump you created in step 1

Instructions are here:
https://postgresapp.com/documentation/migrating-data.html

**Comment by ShereKahn** [comment]
Hello Jakob, 

Thanks for the quick turnaround. Indeed I am seeing the 2.3.5 version now. 

As for the migration, it seems that one needs to reset the app as explained in the Installation & uninstallation page. Maybe it might be good to add a link back to that page on the migration guide. 

Thanks !
