### ISSUE TITLE
pgrouting with postgresApp

### ISSUE THREAD

**Issue by dkalisch** [PostgresApp/PostgresApp#54]
Does someone know how I can use / install pgrouting with postgresApp?
Thanks for your help!

**Comment by mtaptich** [comment]
bump

**Comment by mtaptich** [comment]
Okay. I haven't fully tested its functionality, but I could possibly have a work around if your are getting 'undefined symbols while linking' errors. 

This issue was resolved by changing the filepath in /pgrouting/build/CMakeCache.txt: 
<pre><code>POSTGRESQL_EXECUTABLE:FILEPATH=/Applications/postgres.app/Contents/Versions/9.4/bin/postgres</code></pre>

I am also getting two warnings:
<pre><code>src/tsp/src/tsp2.c:57:5: warning: implicit declaration of function 'get_typlenbyvalalign' is invalid in C99
      [-Wimplicit-function-declaration]
    get_typlenbyvalalign(i_eltype, &i_typlen, &i_typbyval, &i_typalign);
    ^
src/tsp/src/tsplib.c:115:16: warning: implicit declaration of function 'Rand' is invalid in C99
      [-Wimplicit-function-declaration]
        last = Rand ();
               ^</code></pre>

Since I am trying to learn pgRouting, I will confirm the work around once I run my first test. Please, feel free to add to my post if you have more experience with this. Cheers!

**Comment by dkalisch** [comment]
An alternative is to use the grouting from http://www.kyngchaos.com/software/postgres (make sure that the Version of postgres matches the one grouting is build for!)
Then you only have to do the following 3 adjustments:

Before you install the pgrouting package set the path of the Postgres.app to the expected path. `ln -s /Applications/Postgres.app/Contents/Versions/9.3/ /usr/local/pgsql-9.3`

After installing, create a symbolic link to the installed grouting extension: `ln -s /Applications/Postgres.app/Contents/Versions/9.3/share/extension/pgrouting* /Applications/Postgres.app/Contents/Versions/9.3/share/postgresql/extension`

And last but not least, in `/Applications/Postgres.app/Contents/Versions/9.3/share/extension/pgrouting--2.0.0.sql`change `$libdir/`to `/Applications/Postgres.app/Contents/Versions/9.3/lib/` (adjust 9.3 with the correct version!)

After that you can install posts and grouting with

```
CREATE EXTENSION postgis;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION pgrouting;
```
and verify that everything works fine:

```
SELECT postgis_full_version();
POSTGIS="2.1.3 r12547" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.0, released 2013/04/24" LIBXML="2.9.1" LIBJSON="UNKNOWN" TOPOLOGY RASTER


SELECT * FROM pgr_version();
 version |       tag       | build |  hash   | branch | boost  
---------+-----------------+-------+---------+--------+--------
 2.0.0   | pgrouting-2.0.0 | 0     | f26831f | master | 1.54.0
(1 row)
```

Happy routing :-)

**Comment by dassouki** [comment]
@dkalisch , I'm on osx 10.10.2 and although I followed your instructions, I'm having an issue: I can't find `/Applications/Postgres.app/Contents/Versions/9.3/share/extension/pgrouting*`, however, I can find pgrouting in `/usr/local/pgsql-9.3/share/extension/` . Any suggestions or comments?

**Comment by dkalisch** [comment]
@dassouki: That means that you didn't set the symbolic link:

`ln -s /Applications/Postgres.app/Contents/Versions/9.3/share/extension/pgrouting* /Applications/Postgres.app/Contents/Versions/9.3/share/postgresql/extension`

**Comment by ctimmins** [comment]
The wrong (but works) way:

I have another installation of postgres
```
ll $(which postgres)
$: /usr/local/bin/postgres -> usr/local/Cellar/postgresql/9.5.2/bin/postgres
```

`brew install pgrouting`.  Should be located in `/usr/local/Cellar/pgrouting/2.1.0_1/share/postgresql/extension`

if you start the postgress.app and run `ps aux | grep postgres` you can see the process running that looks like `/Applications/Postgres.app/Contentents/yada/yada -D <some config directory>`.  Now kill it.


run `postgres -D <some config directory from above>`  
now go into the psql shell  and `create extension pgrouting`
should work and you should be all set to use it from postgres.app next time you run the server

**Comment by RP-3** [comment]
@ctimmins Lifesaver!
Might be useful for everyone else, make sure your postgres.app and alternative installation are of the same minor version. 

Some commands that might be useful if juggling homebrew's postgres and postgres.app:
`brew list services`
`brew switch <some other version of postgres>`
`brew search postgresql`

**Comment by Fivelfivel** [comment]
@ctimmins 
just confirming this worked for me too. thanks!!

**Comment by timkofu** [comment]
Would it be possible to include pgrouting in Postgres.app?

**Comment by tbussmann** [comment]
@timkofu: inclusion of pgrouting is currently tracked in #288 - the issue with that is a dependency that we did not yet figure out how we want to deal with. You can however fulfil that dependency by other means (e.g. `homebrew`) and build pgrouting yourself against PostgresApp. An (not fully up to date) set of instructions can be found [here](https://github.com/PostgresApp/PostgresApp/issues/288#issuecomment-466085316). I'll try to compose a list of contributed instructions on how to build various extension against PostgresApp and look into the boost issue for `pgrouting` / `postgis_sfcgal` when I find some spare time but I cannot promise when that will happen.

**Comment by timkofu** [comment]
Building it manually worked. Thank You.
