### ISSUE TITLE
Could not open database in terminal

### ISSUE THREAD

**Issue by ismailgithub** [PostgresApp/PostgresApp#540]
I have installed PostgresApp and when i open postgres database from UI, it says "Terminal" not found. Please select a different database client in the preferences.

I have UnInstalled and Installed several times. 

Can anyone help me out to resolve the Issue?

Thank you in advance!

<img width="601" alt="Screenshot 2019-12-12 at 10 51 39 PM" src="https://user-images.githubusercontent.com/8132426/70734298-fe94f780-1d31-11ea-930c-d10e2d218f64.png">

**Comment by jakob** [comment]
Did you move or rename Terminal.app?

**Comment by ismailgithub** [comment]
No. I didn't.

**Comment by jakob** [comment]
Oh, I just realised that this looks like an old version of the error message. Which version of Postgres.app are you using, and what version of macOS are you on? Can you update to a newer version?

**Comment by ismailgithub** [comment]
Hi, My macOS version is 10.15.2. The PostgreSQL 10 is the version. (Postgres-2.1.5.dmg).

**Comment by ismailgithub** [comment]
Hi, I have updated from 2.1.5 to Postgres 2.3.2. Now it works!

Thank you for your response in timely manner...
