### ISSUE TITLE
Version 2.3 (61) doesn't allow update check?

### ISSUE THREAD

**Issue by wellsoliver** [PostgresApp/PostgresApp#541]
'Check for updates' is greyed out in the menu, and there's a newer version available (v2.3.3, with PG 12.1). Any reason I can't do this?

**Comment by jakob** [comment]
What version of macOS are you on?

**Comment by jakob** [comment]
@wellsoliver are you still experiencing the 'Check for updates' issue in Postgres.app?

**Comment by wellsoliver** [comment]
Sorry meant to follow up here, but no, I had to reinstall Catalina (barf) and since putting Postgres app back, it's been fine.

**Comment by jakob** [comment]
OK, thanks for the update. I'm closing this issue, then. If someone can reproduce it, please feel free to re-open!
