### ISSUE TITLE
Mac OS 10.13.6 High Sierra 2.3.3c keeps trying to run 9.4.5 server

### ISSUE THREAD

**Issue by brentreeves** [PostgresApp/PostgresApp#543]
Postgres 2.3.3c (66) (v12)  says "Binaries not found"

"Server Settings" somehow stays set to Library/Application Support/Postgres/var-9.4
even though "Show Package Contents" shows 
Contents/Versions/12/bin/postgres, postmaster et.al.

followed advice to uninstall old postgres installations. Also had one in /usr/local/php5/bin/

Now, "which postmaster" -> /Applications/Postgres.app/Contents/Versions/latest/bin/postmaster

postmaster --version
postgres (PostgreSQL) 12.1

which psql -> /Applications/Postgres.app/Contents/Versions/latest/bin/psql
psql -> psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

How to tell Postgres 66 to look in its own Contents/Versions/12/bin for binaries instead of Library/Application Support/Postgres/var-9.4 ?

**Comment by brentreeves** [comment]
![binaries-not-found](https://user-images.githubusercontent.com/4706156/71538477-55353080-28f1-11ea-8fdd-7345151c2fdd.png)

**Comment by tomitrescak** [comment]
How did you solve it? Mine is trying to run version 10 at all times
