### ISSUE TITLE
Support Homebrew

### ISSUE THREAD

**Issue by nferrara100** [PostgresApp/PostgresApp#545]
It would be awesome if something like this were possible: `brew cask install postgressapp`

I understand you don't want to create a whole CLI interface, but this one command would be very useful so we can automate our machine installs. Thank you!

**Comment by mhanberg** [comment]
@nferrara100 It is already on homebrew cask, try `brew cask install postgres`.

**Comment by rockchalkwushock** [comment]
Just want to drop this here as the API has changed for `homebrew` (I'm running `3.0.8`, not sure as of when it changed):

```shell
brew install homebrew/cask/postgres
```

**Comment by jaklan** [comment]
FYI: the cask name has changed, now it's:
`brew install --cask postgres-unofficial`

**Comment by Downchuck** [comment]
Reminder to those hitting this page that the cask version includes the full bundle - it does not presently support selecting a specific postgres version.
