### ISSUE TITLE
[HELP] Connection refused

### ISSUE THREAD

**Issue by srk1710** [PostgresApp/PostgresApp#546]
Hi guys,
Im working with postgres.app on my Mac and when I try a connection by PDO or pg_connect I always got the same error: 
"Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432"
I tried everything........ pls some help ;(

**Comment by jakob** [comment]
It sounds like the server isn't running.

Open Postgres.app, and click the start button to start the server.

Does it show up as running?

If not, there could be an issue with the firewall.

**Comment by jakob** [comment]
> If not, there could be an issue with the firewall.

Oops, I meant to say if it shows up as running, and you still get the same error, the issue could be that there is a firewall that prevents access.
