### ISSUE TITLE
Could not initialize database cluster.

### ISSUE THREAD

**Issue by cjspark** [PostgresApp/PostgresApp#547]
At first I try to install the Enterprised DB version. But then I found I did it wrongly. So I uninstalled the old one and try to install the postgresapp. Then I faced a problem, it keeps remind me the port 5432 has been used. I checked the methods you guys told on the internet and tried but it did not work. So I found the files related the postgres and try to restart the whole installation. Then it show me this problem. I am really confused about this problem and can not figure it out. Wanna help, thank you.

**Comment by jakob** [comment]
It sounds like there is already a PostgreSQL server running on your Mac.

Step 1: Remove all other PostgreSQL installations. See the docs here: https://postgresapp.com/documentation/remove.html

Step 2: Restart your Mac. Deleting PostgreSQL installations does not necessarily stop them if they are already running. Restart your Mac to make sure that no PostgreSQL server is running any more.

Step 3: Open Activity Monitor, select "All Processes" from the "View" menu, then search for "postgres". If you find no results, you're good.

Step 4: Now double click Postgres.app, and start a server or initialize a new one.
