### ISSUE TITLE
ogr seems to be missing Postgres driver

### ISSUE THREAD

**Issue by savv** [PostgresApp/PostgresApp#548]
When I run this command:
ogr2ogr -f "PostgreSQL" PG:"dbname=mydb" myshapes.kml -nln all_shapes -append

I get:
ERROR 1: Unable to find driver `PostgreSQL'.

Running `ogrinfo --formats` only returns:
  PGDUMP -vector- (w+v): PostgreSQL SQL dump

And this is missing:
PostgreSQL -vector- (rw+): PostgreSQL/PostGIS

I've checked that I'm using your bundle:
```
$ which ogrinfo
/Applications/Postgres.app/Contents/Versions/12/bin/ogrinfo
```

This works if I use the ogr2ogr provided by miniconda.

I suppose the PostgresApp should support postgres :-) Thank you for all the great work, this is a great bundle.
-Chris

**Comment by jakob** [comment]
Looks like I broke something when building PostgreSQL 12, since it works with PostgreSQL 11.

```bash
$ /Applications/Postgres.app/Contents/Versions/11/bin/ogrinfo --formats | grep -i postgres
  PostgreSQL -vector- (rw+): PostgreSQL/PostGIS
  PGDUMP -vector- (w+v): PostgreSQL SQL dump

$ /Applications/Postgres.app/Contents/Versions/12/bin/ogrinfo --formats | grep -i postgres
  PGDUMP -vector- (w+v): PostgreSQL SQL dump
```

I don't have time to dig deeper right now, but it would be interesting if all our builds of PostgreSQL 12 are affected, or just some of them. I tested Postgres.app 2.3.3d (67).

**Comment by tbussmann** [comment]
I did some dissecting. Beta3 was still good, but the first final build of pg12 did make the change. Comparing the tags v2.2.5 and v2.3 I can see that we updated GDAL from 2.3.3 to 3.0.1 with that. Further investigation shows that the the `--with-pg` configure option has changed it's syntax from 2.4.x to 3.0.x slightly, causing the omission of that driver. I did check the remaining options are still correct and could verify the issue appears to be fixed by that.

**Comment by tbussmann** [comment]
unfortunately, the fix https://github.com/PostgresApp/PostgresApp/commit/f8146133f46c30388105dda2304cb1e8abfd230a did only work 'by chance' as pkg-config in the GDAL autoconfig finds a system / Xcode supplied `libpq` v9.3.7 using `/usr/lib/pkgconfig/libpq.pc`. The build should nevertheless link to our own version as the proper `-I` and `-L` flags are supplied for other features already.

**Comment by jakob** [comment]
@tbussmann Thanks for all your help! I just saw that the build I started earlier today failed, but you already fixed it :)

So I started a new build, with the fixes you pushed and a new version of plv8. If everything works I'll release it tomorrow!

**Comment by jakob** [comment]
I just released Postgres.app 2.3.3e, which includes the fix from @tbussmann. GDAL is now linked with libpq again!

**Comment by lukemckinstry** [comment]
I believe I am seeing this issue currently. Using GDAL 3.10.1 installed from the conda-forge gdal package `PostgreSQL -vector- (rw+): PostgreSQL/PostGIS` is missing, but when using it installed from the conda-forge libgdal package it is available.

If this is not the right place to report this issue, I would appreciate if someone could direct me to the right place. Thanks!

**Comment by tbussmann** [comment]
@lukemckinstry : As far as I understand your comment, this has nothing to do with Postgres.app, but with packages provided by conda-forge. So this is not the right place to ask. From a quick look at their repo, it seems they've split the GDAL postgres driver into a separate package in https://github.com/conda-forge/gdal-feedstock/commit/9c1149a1f292fc74c65cd13c739581f25f30cb46, you'll probably need to install it separately now. You should find more information and help in their repository.
