### ISSUE TITLE
When I run 'psql' I get a WARNING error

### ISSUE THREAD

**Issue by Brodersen** [PostgresApp/PostgresApp#555]
When I run 'psql' in the Terminal, i get the following Warning:
psql (9.4.22, server 12.1)
WARNING: psql major version 9.4, server major version 12.
         Some psql features might not work.
Type "help" for help.

How do I remove this warning?

**Comment by tbussmann** [comment]
You are obviously running a different version of `psql`, likely not even the one PostgresApp provides (at least 9.4.22 is not the latest of the 9.4 branch). You can check which `psql` you are starting with `which psql` on the shell. If you like to alter your PATH to point to the latest version PostgresApp provides, please have a look to the documentation: [Configure your `$PATH`](https://postgresapp.com/documentation/cli-tools.html)
