### ISSUE TITLE
Msfconsole issue

### ISSUE THREAD

**Issue by Minhajul788** [PostgresApp/PostgresApp#556]
Whenever I open the msfconsole always facing the same issue WARNING: No database support: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?
What is this anyone can resolve this issue 
![Screenshot_20200207_004343_com termux](https://user-images.githubusercontent.com/60433952/73970590-6be49380-4943-11ea-8374-25aeceee7d00.jpg)

**Comment by jakob** [comment]
I don't think this is related to Postgres.app
