### ISSUE TITLE
initialize failed

### ISSUE THREAD

**Issue by liangmark** [PostgresApp/PostgresApp#558]
when i click the initialize button, i get the error(left:my mac info, right:the error info)
![Snip20200210_7](https://user-images.githubusercontent.com/12019458/74133734-2ca89200-4c24-11ea-9a01-b1c75f49e2ce.png)

please help me, thank you very much!

**Comment by jakob** [comment]
This is an odd error. Is it possible that some software on your Mac has been using up a lot of resources?

Unfortunately I have no idea which software would use a lot of semaphores.

The first thing I'd try would be to restart your Mac. If buggy software leaked kernel resources, that would fix it (at least temporarily).

**Comment by liangmark** [comment]
ok i will restart my Mac and try again, thank you.

**Comment by liangmark** [comment]
it's initialized successful after i restarted my Mac. thank you very much!
