### ISSUE TITLE
PostgreSQL 9.6.16

### ISSUE THREAD

**Issue by DaniG2k** [PostgresApp/PostgresApp#560]
I realize it's a legacy version but would it be possible to install PostgreSQL 9.6.16 using Postgres.app? I am not seeing it listed in the legacy downloads.

Thanks in advance

**Comment by jakob** [comment]
You can download it from here: https://github.com/PostgresApp/PostgresApp/releases/tag/v2.3.3e

It's also still the latest version available from https://postgresapp.com/downloads.html, since I had some issues with notarization, so I haven't released the February updates yet.
