### ISSUE TITLE
12.2 build?

### ISSUE THREAD

**Issue by wellsoliver** [PostgresApp/PostgresApp#563]
Just wondering if there might be a 12.2 PG update soon?

**Comment by donileo** [comment]
Same here.

**Comment by jakob** [comment]
I'm sorry for not publishing 12.2. I initially had some problems with notarization, fixed them, but then I never got around to actually making the final builds and releasing them.

12.3 is scheduled to be released on Thursday next week, I'll do my best to release 12.3 in time.

**Comment by jakob** [comment]
New build with PostgreSQL 12.3 is out! Sorry for skipping 12.2.

**Comment by wellsoliver** [comment]
all good, great! your work remains essential, appreciate it.
