### ISSUE TITLE
Does not start at login

### ISSUE THREAD

**Issue by ozum** [PostgresApp/PostgresApp#567]
Hi,

PostgresApp does not start automatically even "Automatically start Postgres on Login" is selected.

MacOS: 10.14.6
PostgresApp: 2.3.3e(68)

![image](https://user-images.githubusercontent.com/1497060/80789370-76a27380-8b94-11ea-82aa-0cc60df94648.png)
![image](https://user-images.githubusercontent.com/1497060/80789380-7e621800-8b94-11ea-8474-89bb3e7b0933.png)

Are there any places I should look in MacOS, which could prevent it starting, or some logs to post here for further investigation?

Edit: I checked/unchecked those options and restart MacOS. I even completely uninstall PostgresApp and installed from scratch.

Edit 2: I could not see PostgresApp in MacOS User Login Items. Is it supposed to be here?

![image](https://user-images.githubusercontent.com/1497060/80789621-22e45a00-8b95-11ea-8d2e-4acc987ffd89.png)

Many thanks,

**Comment by jakob** [comment]
Hi!

Postgres.app doesn't add a login item. We had trouble getting macOS to launch login items reliably.

We use a _Launch Agent_ instead. When you check the "Automatically start Postgres on Login" box, Postgres.app writes a file to the following path:
`~/Library/LaunchAgents/com.postgresapp.Postgres2LoginHelper.plist`.

Postgres2LoginHelper does two things:

1) It starts every server that has the "Automatically start server" checkbox checked.

<img width="713" alt="Screen Shot 2020-05-01 at 11 53 49" src="https://user-images.githubusercontent.com/198305/80797598-845ef580-8ba2-11ea-87b0-f6e72870f5e1.png">

2) It starts the "PostgresMenuHelper" if "Show Postgres in menu bar" is checked

<img width="713" alt="Screen Shot 2020-05-01 at 11 52 48" src="https://user-images.githubusercontent.com/198305/80797532-5f6a8280-8ba2-11ea-9f86-46bfc0181631.png">

If you don't check any of these boxes, then Postgres2LoginHelper doesn't actually do anything.

**Comment by ozum** [comment]
Thanks @jakob. I have all 3 checkboxes checked. However PostgresApp does not start on login and its icon does not show on menu bar. (I have to start manually.)

`~/Library/LaunchAgents/com.postgresapp.Postgres2LoginHelper.plist` has following content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.postgresapp.Postgres2LoginHelper</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Postgres.app/Contents/Library/LoginItems/PostgresLoginHelper.app/Contents/MacOS/PostgresLoginHelper</string>
	</array>
	<key>KeepAlive</key>
	<false/>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

**Comment by jakob** [comment]
OK, this is odd. Can you try the following two things:

1) Log out from your account, then log in again, then manually run the helper from the command line by typing `/Applications/Postgres.app/Contents/Library/LoginItems/PostgresLoginHelper.app/Contents/MacOS/PostgresLoginHelper`

2) Create an example launch agent file like the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>com.example.say-hello</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/bin/say</string>
		<string>hello</string>
	</array>
	<key>KeepAlive</key>
	<false/>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```

Save this file to `~/Library/LaunchAgents/com.example.say-hello.plist`, then log out, and log in again. If it works, your computer should now say "Hello" after logging in.

**Comment by ozum** [comment]
@jakob

1. I logout-login. App didn't start. I executed the command you posted;
* App starts and icon show up in menu bar
* On console I got error: `Failed to start server PostgreSQL 12 because Could not start PostgreSQL server.`
* However when I click icon on menu bar, I see that PostgreSQL 12 is running.

2. After login, computer said "Hello".

**Comment by ozum** [comment]
Additional info about executing command `/Applications/Postgres.app/Contents/Library/LoginItems/PostgresLoginHelper.app/Contents/MacOS/PostgresLoginHelper` by hand;

## When I logout and then login
* PostgresApp didn't start
* There is `postgres` in Activity Monitor, so PostgreSQL server is running.
* I executed command.
  * App started and icon showed up in menu bar.
  * Because PostgreSQL is already running, on console I got error: Failed to start server PostgreSQL 12 because Could not start PostgreSQL server.
  * When I clicked icon on menu bar, I saw that PostgreSQL 12 is running.

## When I restart MacOS
* PostgresApp didn't start
* There is **NOT** `postgres` in Activity Monitor, so PostgreSQL server is **NOT** running.
* I executed command.
  * App started and icon showed up in menu bar.
  * No error on console.
  * When I clicked icon on menu bar, I saw that PostgreSQL 12 is running.

**Comment by jakob** [comment]
I've just reviewed the [source code of the login helper](https://github.com/PostgresApp/PostgresApp/blob/master/PostgresLoginHelper/main.swift), and found that we check the location of the app bundle at startup. I don't remember for certain why that check is there, but if for some reason launchd decides to [translocate the app](https://lapcatsoftware.com/articles/app-translocation.html), that would fail. It would also explain why starting the helper from bash directly works, because bash doesn't translocate processes, but launchd does.

Did you by any chance install Postgres.app by moving it with the Terminal instead of with the Finder? If that is the case, use the Finder to move the app to a different folder (eg. your desktop), and then back to /Applications

You could also try removing the quarantine attribute. You can check with `xattr -l /Applications/Postgres.app` if it's there, and remove it with `xattr -d com.apple.quarantine /Applications/Postgres.app`

That should hopefully fix the error. If that's not it, I'm really stumped.

If that is the cause of the problem, we should probably think about if we find a way to prevent it from happening.

**Comment by ozum** [comment]
Unfortunately, they didn't help. If you have any fast idea which needs further data, let me know, I'll provide.

Otherwise, do not invest time for this, I can live with manual starting.

**Comment by ozum** [comment]
SOLVED. My particular case was not related to PostgresApp. A utility program called "Clean My Mac", disabled Postgres Agent. I don't know how this prevention survived 3-4 complete uninstall and reinstall of PostgresApp. It works as expected now.

Sorry for taking your time for this.

**Comment by jakob** [comment]
Thank you very much for posting the solution, I'm very glad you figured it out!

**Comment by ozum** [comment]
Ref for future users:

There are so called "cleaner", "uninstaller" etc. apps for MacOS. If you have problems with automatic start and verified options mentioned here, please check your cleaner app's login/startup/launchd section.
