### ISSUE TITLE
could not accept SSL connection: unsupported protocol

### ISSUE THREAD

**Issue by kapaspeter** [PostgresApp/PostgresApp#569]
I've installed the Postgresql 9.5.21 on Ubuntu 20.04. 
I've used the following postgresql repository for installation:
echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list
 wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

The problem is that in can't connect to Postgresql server from PgAdmin3 via SSL authentification.

The following Postgresql server error appear:
[unknown]@[unknown] LOG:  could not accept SSL connection: unsupported protocol
postgres@postgres FATAL:  no pg_hba.conf entry for host "CLIENT_IP", user "postgres", database "postgres", SSL off

The same configuration is working from Ubuntu 18.04 and Ubuntu 16.04

Should I install some additional Ubuntu library for this?
How can I test this issue?

**Comment by jakob** [comment]
We're not a PostgreSQL helpdesk. See https://www.postgresql.org/support/ if you are looking for PostgreSQL support.
