### ISSUE TITLE
My SQL shell show me error

### ISSUE THREAD

**Issue by sunilbhola** [PostgresApp/PostgresApp#570]
My pgAdmin4 working well but my SQL Shell in showing me this ("psql: error: could not connect to server: fe_sendauth: no password supplied"). I am using window 10, 64 bit. friends, please help I am fad up to see
![error](https://user-images.githubusercontent.com/61968995/81274902-904d2a80-906e-11ea-871f-1cf4250c4d82.png)
 this error.

**Comment by jakob** [comment]
We don't offer PostgreSQL support (unless it is directly related to Postgres.app).

Please see https://www.postgresql.org/support/ for general PostgreSQL support options.
