### ISSUE TITLE
Selecting the server version - Only server version 12 is available.

### ISSUE THREAD

**Issue by tomjmul** [PostgresApp/PostgresApp#574]
I downloaded "Postgres.app with all currently supported PostgreSQL versions" v2.3.5, with a view to running against a 9.6 server version. I see absolutely no option to select any server version other than 12 and I see no documentation at all about selecting which server version to run against. What am I missing here?

**Comment by cappert** [comment]
Click the **+** to create a new server
![Click to add server](https://user-images.githubusercontent.com/71031/82349121-0308bf00-99fa-11ea-8de5-e3aa4312f439.png)


then you should have different versions in this dropdown:
![Server dropbown](https://user-images.githubusercontent.com/71031/82349172-14ea6200-99fa-11ea-92af-678d720e5704.png)

**Comment by tomjmul** [comment]
Thanks very much for taking the the time for me @cappert....I thought I was going insane there for a while! 😄 

So directly after installation, I had to find the reveal side-bar button in order to find the plus button. It might be an idea to just have the sidebar open by default? It's not exactly a hugely complex screen with space at an absolute premium.

**Comment by tbussmann** [comment]
We discussed this several times before, the idea is to keep the UI as simple as possible for the majority of users only interested in running a single instance. But as this issue has been confusing people in the past several times (see #388, #422, #429, #484, #523) we should finally improve this. There ideas for this discussed in the open cases https://github.com/PostgresApp/PostgresApp/issues/445#issuecomment-385428585 and https://github.com/PostgresApp/PostgresApp/issues/399#issuecomment-316660460

Beside improvements to documentation, esp. on upgrades, my proposal for the App's behaviour would be:
*  On first run(*) create a new server-entry with latest version if either
    * no server / data directory is existing at all
    * no server exists with the latest version _(not sure about this one - alternatively the next)_
    * all configured servers require binaries that are not provided by the installed package
* On each start of the application create a new server-entry with latest version if
    * no server is existing at all *(existing behaviour)*
* On each start of the application, automatically open the sidebar if either
    * multiple servers are already configured *(existing behaviour)*
    * the only configured server is not initialised and the installed package has multiple binary versions available
    * the only configured server requires binaries that are not provided by the installed package

(*): we currently can only detect the first run in total, not per release, IIRC. At this, potentially existing data dirs are scanned and server-entries for them created.

Does this sound useful or is it to complicated? The simpler proposal from https://github.com/PostgresApp/PostgresApp/issues/399#issuecomment-316660460 I would read as:
* Always start with expanded sidebar
* On each start create a server with latest version if no such exists

To me this defeats the concept of an expandable sidebar in general and may annoy people intentionally running an older version.

**Comment by cappert** [comment]
I think you need to start tracking and surfacing the versions in the UI, without falling into the slippery slope of upgrading users' data for them, which I think is too difficult and error prone.

I made a very quick mockup. 
![Quick mockup PG versions](https://user-images.githubusercontent.com/71031/82390068-f6a65580-9a3d-11ea-9734-1c1a83a22f5b.png)

Some thoughts unrelated to the mockup:
I think the closed drawer pattern is too "old-school" and most apps start with a sidebar launch with it open by default (from the top of my head- Slack, VSCode, Garageband, Whatsapp), following web UI trends. If there's only one server it's just empty space.
There's the risk of confusion between creative a server and creating a database though.

One other problem is that the error message "The binaries for the PostgreSQL server were not found" is too generic and cryptic.

Maybe you need to show somewhere what are the capabilities of the installed Postgres.app, now that you have different flavors (12, 12+11+10, etc.). I feel it's a big source of confusion.

**Comment by steveholzer** [comment]
> Beside improvements to documentation, esp. on upgrades, my proposal for the App's behaviour would be:

I am writing this today as I find that the docs do not address this simple how to. 
Finding this issue solved my problem of how to create a 9.6 server. Please consider your comments to improve docs. A section on this would save much efforts from users and tickets for your team.

**Comment by mikong** [comment]
When I select the drawer, and create a new server, I only see Version 12 in the dropdown. Even the screenshot in the response (https://github.com/PostgresApp/PostgresApp/issues/574#issuecomment-630914602) seems to only have 12 in the dropdown. How do we install additional binaries, e.g. 14?

I've thought about using brew but there are some discussions that suggest that may not work well with PostgresApp.

When I check for updates, I have the latest version, v2.5.6. The issue is I don't have the binaries installed in my machine. The Binaries directory (/Applications/Postgres.app/Contents/Versions) only contains 12.

**Comment by mikong** [comment]
To solve my issue, I downloaded "Postgres.app with PostgreSQL 14" from https://postgresapp.com/downloads.html. Then, instead of overwriting the whole Postgres app in Applications, I just used "Show Package Contents" on the mounted dmg and copied Contents/Versions/14 folder to my /Applications/Postgres.app/Contents/Versions/ folder. When I checked the drawer and create a new server, I can now see both 12 and 14 in the dropdown.

**Comment by jakob** [comment]
@mikong That works, but you will need to re-download PostgreSQL 14 every time you update Postgres.app. It's also breaks the code signature, so make sure to open the app at least once before copying the "14" folder into the app.

The easiest solution is to just download "Postgres.app with all currently supported versions" from the downloads page. It needs a bit more disk space, but it will just work.
