### ISSUE TITLE
postgres keeps eating up my macbook disk space

### ISSUE THREAD

**Issue by bluemonk482** [PostgresApp/PostgresApp#577]
I have installed postgre app and followed [here](https://github.com/MIT-LCP/mimic-code/tree/master/buildmimic/postgres) to create a local postgresql database. However when I noticed how much disk space it would occupy, I immediately ctrl-c-ed the process. But my macbook disk space still gets eaten up bits by bits. I then deleted the app and removed the /Library/ApplicationSupport/Postgres directory which is occupying 12GB.

However the disk space didn't free up much, and I still find the disk space gets eaten up bits by bits, though much much slower now. What is going on here? Ok I think (hope!) it has stopped eating up my disk space now, but where can i find the problem and how can i free up all the space? Thanks!

**Comment by bluemonk482** [comment]
Disk space all of sudden freed up now. Rather Odd. Why the latency?

I shall close this issue now, but I really would like to hear what yall think?

**Comment by jakob** [comment]
In my experience, APFS is generally very slow to make disk space available after deleting files, so the latency is probably not related to Postgres.app.
