### ISSUE TITLE
Add another PostgreSQL version

### ISSUE THREAD

**Issue by dowi** [PostgresApp/PostgresApp#579]
Hi,
Ho can I add newer versions of PostgreSQL ?
When clicking the + button I can see I can start a new server of only 9.5, 9.6 and 10 from previous projects I worked on.
I want to add PostgreSQL version 11 - How can I do that?
(I have updated Postgres.App to the newest 2.3.5 (74) version)

Thanks!

**Comment by cappert** [comment]
quick fix:
go to https://postgresapp.com/downloads.html
and download the release named **Postgres.app with all currently supported PostgreSQL versions**.
it's basically the same as **Postgres-2.3.5-9.4-9.5-9.6-10-11-12.dmg** in https://github.com/PostgresApp/PostgresApp/releases/tag/v2.3.5, where you can narrow down the versions further.

Postgres.app has several "channels" to make the downloads smaller, as the users often don't need several different versions and the updates were getting really big.

**Comment by dowi** [comment]
Thanks for the quick response - I have already many DBs in Postgres.App using 9.6 and 10 -> will they be kept during a new install?

**Comment by cappert** [comment]
using this version or any version with **9.6** and **10**, yes.
Postgres.app store all your data in  `~/Library/Application Support/Postgres`, not in the Application bundle, so nothing would be deleted anyway.

**Comment by dowi** [comment]
Thanks it worked!
