### ISSUE TITLE
install doesn't create PostgreSQL user with current username 

### ISSUE THREAD

**Issue by adamgreenhall** [PostgresApp/PostgresApp#58]
When I install the app I don't get a PostgreSQL user with my user name. The app status when first launched is `Could not launch on Port 5432`.

When I run `psql` it gives:
`psql: FATAL:  role "adam" does not exist`

but with `psql -U postgres` I get the normal psql prompt.

I've tried to uninstall-reinstall a few times, without a different result. I removed all existing postgres installations before I added the app. 

What is going on and how do I fix it?

**Comment by es6Test** [comment]
I also have this issue. I try fire psql and get that message and it exists the psql with a FATAL error.

**Comment by jakob** [comment]
@es6test please open a new issue and describe your problem in detail instead of replying to a bunch of old issues

**Comment by es6Test** [comment]
I installed it in a clean mac and it worked thx. I think I had pgEnterprise before that was causing some conflict.
