### ISSUE TITLE
Can the ~/Library/Caches/com.postgresapp.Postgres2/Sparkle/* be purged?

### ISSUE THREAD

**Issue by jevin** [PostgresApp/PostgresApp#580]
Hey everyone,

My ~/Library/Caches/com.postgresapp.Postgres2/Sparkle/ folder is filled with previous Postgres versions. Can I safely empty this folder?

Thanks!

**Comment by cappert** [comment]
Yes.

Hey everyone,

**Comment by jevin** [comment]
Perfect, Thanks!
