### ISSUE TITLE
PostGIS not included

### ISSUE THREAD

**Issue by PeterBange** [PostgresApp/PostgresApp#582]
I first installed postgres/postgis on my MacBook Pro Catalina but ran into problems I could not solve: I could not connect to my databases after 12 days of flawless use of pgAdmin 4. After trouble shooting with de terminal I finally decided to uninstall the EDB installation and try the Postgres.app installation instead. This worked very quick, but although it is stated that PostGIS is included there is no PostGIS enabled database created. I cannot find any documentation on this issue. I tried to add PostGIS in varu=ious ways but no succes. The Postgres.app is very short on this subject, it is not mentioned at all unfortunately. How can I get PostGIS functionality into my Postgres 10 database that is created by the Postgres.app ?

**Comment by tbussmann** [comment]
If you switched from another Postgres distribution and are not experienced with running multiple instances, please make sure to completely [remove the other installation](https://postgresapp.com/documentation/remove.html) to make sure it won't interfere with PostgresApp.
PostgresApp comes with quite a lot of pre-built, bundled extensions but these need to be activated per database. With PostgreSQL 10 we bundle PostGIS 2.4. To use it, connect to your database (within the main window of PostgresApp, double click on the database icon to launch `psql` in Terminal) and run `CREATE EXTENSION postgis;`. If you want to use the topology functions as well, also run `CREATE EXTENSION postgis_topology;`. US geocoding and address functions can be activated as well, but these require some reference data to be loaded for being useful. You can find details in the [documentation of PostGIS 2.4](http://postgis.net/docs/manual-2.4/index.html)

**Comment by PeterBange** [comment]
It worked ! Thx :-)



Vriendelijke groeten, Regards,

Peter Bange

**Comment by tbussmann** [comment]
Thank you for the feedback, glad it worked for you!
