### ISSUE TITLE
Could not initialize database cluster -- could not create semaphores: No space left on device

### ISSUE THREAD

**Issue by RetownPlato** [PostgresApp/PostgresApp#583]
Log:
```
2020-08-06 09:40:47.034 CST [28825] FATAL:  could not create semaphores: No space left on device
2020-08-06 09:40:47.034 CST [28825] DETAIL:  Failed system call was semget(5432001, 17, 03600).
2020-08-06 09:40:47.034 CST [28825] HINT:  This error does *not* mean that you have run out of disk space.  It occurs when either the system limit for the maximum number of semaphore sets (SEMMNI), or the system wide maximum number of semaphores (SEMMNS), would be exceeded.  You need to raise the respective kernel parameter.  Alternatively, reduce PostgreSQL's consumption of semaphores by reducing its max_connections parameter.
	The PostgreSQL documentation contains more information about configuring your system for PostgreSQL.
child process exited with exit code 1
initdb: removing data directory "/Users/allen/Library/Application Support/Postgres/var-12"
```
The logs suggest that "You need to raise the respective kernel parameter.  Alternatively, reduce PostgreSQL's consumption of semaphores by reducing its max_connections parameter." But where and how can I change the parameter?

**Comment by tbussmann** [comment]
We already have two (slightly different) semaphore related issues (#575, #581) which I was so far unable to reproduce. I see, you are from China. This seems so far the only common thing among the issues.

Could you please give some more context to your issue? Which OS version? Does the error happen repeatedly? Does a reboot of the system change the situation? Did you try [other PostgreSQL distributions](https://www.postgresql.org/download/macosx/)?

> But where and how can I change the parameter?

The `max_connections` could be changed like other GUCs, e.g. within `postgresql.conf` of the cluster. But if that happens during `initdb` too many connections will likely not be the problem and the conf file not yet existing. 

The kernel parameters can be changed by `sysctl` but this is really not a common task to do and should not be necessary to run PostgresApp. To see the current configuration on your system, could you please run `sysctl -a | grep sem` in a terminal window and show the output?

**Comment by RetownPlato** [comment]
OS: OSX 10.15.4
I have tried install via EDB installer but get install error.
After I reboot the system, it works.
Thanks for your advice.☺️
