### ISSUE TITLE
Feature Request: AgensGraph

### ISSUE THREAD

**Issue by timkofu** [PostgresApp/PostgresApp#585]
Would it be possible to bundle [AgensGraph](https://github.com/bitnine-oss/agensgraph) in your next release?

**Comment by jakob** [comment]
I've never heard of AgensGraph before.

From looking at the website, it looks like this is a completely different type of database that just happens to use PostgreSQL under the hood. I'm not sure how bundling AgensGraph would help people who download Postgres.app.

The goal of Postgres.app is to make it easy to use PostgreSQL. We also include a few popular extensions, but we don't plan on bundling every piece of software built on/for PostgreSQL.

Perhaps the people behind AgensGraph could fork Postgres.app to create their own AgensGraph.app?

**Comment by timkofu** [comment]
> but we don't plan on bundling every piece of software built on/for PostgreSQL

It's a request for just this one piece. But I get you, an `AgensGraph.app` would be the way to go, as including it is outside your scope, and would open a door you don't want opened. Closing this.

**Comment by jakob** [comment]
> It's a request for just this one piece (...) and would open a door you don't want opened

People make requests for lots of things to be included. We do include things occasionally when they are useful and used by many PostgreSQL users. Recent additions have been for example wal2json and pldebugger.

But I just don't see how AgensGraph would be useful for PostgreSQL users, it seems like AgensGraph users would be mostly disjunct from other Postgres.app users.

**Comment by jakob** [comment]
Also, if someone wants to fork Postgres.app to create something like AgensGraph.app, please reach out! I would definitely help with that!
