### ISSUE TITLE
Database list is blank

### ISSUE THREAD

**Issue by timmyomahony** [PostgresApp/PostgresApp#588]
I'm running 2.3.5 on MacOS 10.15.6. I've got Postgres 11 installed but notice that none of my databases are showing in the list:

<img width="815" alt="Screenshot 2020-09-11 at 14 17 49" src="https://user-images.githubusercontent.com/615149/92930259-bda14f00-f439-11ea-9e3b-c2cee3dad741.png">

If I login with `psql` I can see them (so they exist). Furthermore if I switch to Postgres 10 I _do_ see all my v10 databases. 

Not sure what's going on?

**Comment by jakob** [comment]
Did you set a password? Postgres.app just tries connecting to the server with the default settings, and if that doesn't work it shows a blank window.

**Comment by timmyomahony** [comment]
Thanks for the reply. That make sense. For anyone else; the reason was that I had deleted my default database corresponding to my system user. When I tried to connect to Postgres (by simply running `psql` on the command line) I was getting:

> psql: error: could not connect to server: FATAL:  database "myname" does not exist

So I just had to create the `myname` default database and every worked again:

```sh
psql -U postgres
> create database myname
```
