### ISSUE TITLE
Checking in on updates

### ISSUE THREAD

**Issue by anthonydb** [PostgresApp/PostgresApp#590]
Hi, I'm the author of Practical SQL from No Starch Press, and in the book I recommend that macOS owners use PostgresApp. I'm working on updating the book and want to make sure that you're planning to upgrade your app to PostgreSQL 13 when it's released. Thanks for creating a great product!

**Comment by jakob** [comment]
Yes, I'm updating Postgres.app for PostgreSQL 13. I'm sorry that I fell a bit behind with the most recent updates and the latest release candidate, but I hope I'll finish building all the images in time for release.

**Comment by jakob** [comment]
Postgres.app with PostgreSQL 13 is now available!

https://postgresapp.com/downloads.html

**Comment by anthonydb** [comment]
Thanks, @jakob!
