### ISSUE TITLE
latest version crashes on startup

### ISSUE THREAD

**Issue by hobbyman** [PostgresApp/PostgresApp#593]
Here is the output from the crash reporter.

Process:               Postgres [54507]
Path:                  /Applications/aLance/Postgres.app/Contents/MacOS/Postgres
Identifier:            com.postgresapp.Postgres2
Version:               2.4 (91)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Postgres [54507]
User ID:               1261573125

Date/Time:             2020-09-25 07:47:28.898 -0500
OS Version:            Mac OS X 10.14.6 (18G5033)
Report Version:        12
Anonymous UUID:        C72B2E58-7689-FBF1-AD1A-748DD327BFE9

Time Awake Since Boot: 130000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /Applications/Postgres.app/Contents/Versions/13/lib/libpq.5.dylib
  Referenced from: /Applications/aLance/Postgres.app/Contents/MacOS/Postgres
  Reason: image not found

Binary Images:
       0x10cbbf000 -        0x10cbedfff +com.postgresapp.Postgres2 (2.4 - 91) <2DE32291-EF3A-3FF1-A1DA-61F14DD7DD29> /Applications/aLance/Postgres.app/Contents/MacOS/Postgres
       0x113e9d000 -        0x113f0770f  dyld (655.1.1) <DF71FC3D-E58F-3D48-9165-3B96FF8BFA22> /usr/lib/dyld

Model: iMac15,1, BootROM 234.0.0.0.0, 4 processors, Intel Core i7, 4 GHz, 32 GB, SMC 2.23f11
Graphics: kHW_AMDRadeonR9M295XItem, AMD Radeon R9 M295X, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453220
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453220
Memory Module: BANK 0/DIMM1, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453220
Memory Module: BANK 1/DIMM1, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453220
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x142), Broadcom BCM43xx 1.0 (7.77.61.3 AirPortDriverBrcmNIC-1305.9)
Bluetooth: Version 6.0.14d8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
Serial ATA Device: APPLE HDD ST3000DM001, 3 TB
USB Device: USB 3.0 Bus
USB Device: My Passport 25E2
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Composite Device
USB Device: Cruzer
Thunderbolt Bus: iMac, Apple Inc., 26.1

**Comment by jakob** [comment]
Postgres.app needs to be directly in your /Applications folder, not in a subfolder.

**Comment by hobbyman** [comment]
It's worked this way in the past.
Has something changed?

**Comment by jakob** [comment]
No, this has been a requirement for a couple of years already. Some very old builds allowed relocating the app bundle, but that caused a lot of issues when other software linked against Postgres.app. This has been discussed previously eg [here](#469)  or [here](#272).

**Comment by IanMayo** [comment]
@jakob - I also suffered from this problem.  Is it worth documenting the requirement for `Postgres.app` to go in the root of `Applications` on the `Downloads` page?

**Comment by jakob** [comment]
I think it's better to not crash (see issue https://github.com/PostgresApp/PostgresApp/issues/639)

**Comment by IanMayo** [comment]
Yes, @jakob - that's a valid long term goal.

In the near term, however, it could avoid making a poor first impression if users knew the installation constraint.

**Comment by jakob** [comment]
It's already mentioned on the home page that you need to move Postgres.app to /Applications

Fixing this really isn't that much effort, I'll see if I can do it tonight.

**Comment by jakob** [comment]
(We came up with a simple way to fix it in the last maintainer meeting, that's why we didn't do it sooner)
