### ISSUE TITLE
"No binaries" after installing the multi-version Postgres.app on OS X

### ISSUE THREAD

**Issue by jackrg** [PostgresApp/PostgresApp#595]
Had an OS X system running Postgres 9.2. Installed multi-version Postgres.app from the dmg and when I ran the app, it displayed the control screen, showed Postgres 9.2 as available, but with the message "no binaries". While that  may have referred to the fact that the multi-version app did not have 9.2 binaries, that wasn't clear. I could not install any of the versions available in the app until I removed the 9.2 version. Then I was able to install and activate 10.0 (I didn't try the others, but I presume it would have worked with those as well).

1) If the "no binaries" message referred to 9.2, then the message should have been worded to make that clear. As it was it looked like it was saying it didn't know where to find any of the binaries.

2) If I needed to remove 9.2 before I installed any of the binaries from the new version, that should have been documented somewhere. I followed the "how to update" instructions, which worked very well except for this issue -- the pgdumpall followed by the restore procedure worked flawlessly.

**Comment by nija** [comment]
Non-obvious via error message or documentation, but the solution is to use the sidebar button to create a new server (of whichever version you want), then click the initialize button on the right to initialize the server. This issue was very helpful: https://github.com/PostgresApp/PostgresApp/issues/399
