### ISSUE TITLE
PostgresApp just got uninstalled suddenly while it was running

### ISSUE THREAD

**Issue by karuppiah7890** [PostgresApp/PostgresApp#599]
I was on my Mac working with Postgres and at some point suddenly my tests threw connection refused errors. After this, I couldn't find the Postgres app in the spotlight but I could see it in the top right macos bar but when I clicked, I could see only some options, the last option to stop the server was not present and the area was blank. After sometime it just vanished from the bar too. I can't remember if I did something (clicking) on the bar.

I just wanted to ask if it's possible that an app bug can cause this? Or else I've suspicions that I could have been hacked, or some other app did something wrong (bug) or something malicious, which again means hacked

**Comment by jakob** [comment]
Yes, it's possible that an app bug causes this. It could also be a macOS bug. Of course it could also be a hacker, but I'm not sure why a hacker would hack your computer and then quit Postgres.app.

Anyway, first step would be to check `~/Library/Logs/DiagnosticReports` for crash reports. If you find something there, attach it to this issue.

Next step would restarting your computer. If you run into the issue again after restarting your computer, please let us know:

- macOS system version
- Postgres.app version
- computer model

Just so we know where to start looking.

**Comment by karuppiah7890** [comment]
I actually already reinstalled the app. Just the app went missing. The data (probably stored in a different place?) was still present - my DB and tables

**Comment by karuppiah7890** [comment]
But I'll try to get all the details regarding this. And hacking - haha. Idk. I can never guess what some humans are upto. Someone could just be practicing with their code or something, for a big plan later. :P

**Comment by karuppiah7890** [comment]
Also, correction in case you misunderstood - Postgres App was not quit. It was uninstalled. Not present in my Applications.

**Comment by karuppiah7890** [comment]
So, my postgress app got uninstalled again. I couldn't find any crash reports. Next time I'll look for it immediately 😅 

My system details:
- macOS system version: 10.15.7 (19H15)
- Postgres.app version: Version 2.4.1 (101)
- computer model: MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by jakob** [comment]
Postgres.app doesn't uninstall itself.

Could it be that you have some kind of security software running on your Mac that automatically uninstalls "forbidden" software?

**Comment by karuppiah7890** [comment]
There is, but I'm not sure if that's what caused it.

**Comment by karuppiah7890** [comment]
I have Sophos software installed

**Comment by jakob** [comment]
That would be my first guess what's happening.

I'd like to apologise, I misunderstood the "uninstall" part when I first replied and thought that Postgres.app just crashed on your Mac. If Postgres.app disappears from `/Applications`, then something must be deleting it. I'm not familiar with Sophos, please ask whoever set up your Mac for help.

**Comment by karuppiah7890** [comment]
I'll close this issue as I never faced the issue again later
