### ISSUE TITLE
PostgresMenuHelper.app is not open Anymore

### ISSUE THREAD

**Issue by elpop** [PostgresApp/PostgresApp#604]
When update to Mac OS Big Sur 11.1, at login time, show the legend:

Th application "PostgresMenuHelper.app" is not open Anymore

And randomly fail to start, need to remove the  postmaster.pid file.
![Screen Shot 2020-12-23 at 10 31 47](https://user-images.githubusercontent.com/101490/103103340-05617600-45e6-11eb-8cfb-adc733798b26.png)

**Comment by howells** [comment]
@elpop I have this issue too - were you able to resolve it?

**Comment by collimarco** [comment]
I have the same issue.

**Comment by ArneMeier** [comment]
Got the same. How do I fix this?

**Comment by MaraudingMastodon** [comment]
Hi, all. I'm seeing that popup about PostgresMenuHelper no longer running, when I cold start my 14" 2021 M1 Pro MacBook Pro. 

MacOS version : 12.0.1 (21A559)

Postgres.app version : Version 2.5.2 (128)

Example output from console.app : 

23:32:02.110800-0600	diagnostics_agent	com.apple.message.domain: com.apple.usage.app_activetime
com.apple.message.__source__: SPI
com.apple.message.signature: PostgresMenuHelper
com.apple.message.signature2: com.postgresapp.Postgres2MenuHelper ||| 2.5.2 (128)
com.apple.message.value: 6
com.apple.message.value2: 0
com.apple.message.value3: 0
com.apple.message.value4: 0
com.apple.message.value5: 0
com.apple.message.value6: 0
com.apple.message.value7: 0
com.apple.message.result: NO
com.apple.message.summarize: YES
SenderMachUUID: 5238C988-6241-35FB-AF33-790C962AE464


From terminal, contents listing : 

➜  ~ ls -l /Applications/Postgres.app/Contents/MacOS
total 1248
-rwxr-xr-x@ 1 cory  admin  638928 Nov 10 12:30 Postgres
drwxr-xr-x@ 3 cory  admin      96 Nov 10 12:27 PostgresMenuHelper.app
➜  ~

**Comment by microhardsmith** [comment]
same problem with my macbook pro  16 2021,macos 12.2.1,when I restart my computer this message came out

**Comment by jakob** [comment]
Reading through @MaraudingMastodon's comment, I wonder if it has something to do with how we start the menu helper.

We use `NSWorkspace.open(_:)` to launch the app:
https://github.com/PostgresApp/PostgresApp/blob/f45c418b8c8e2f93cea4b86680dadb075601bcb1/PostgresLoginHelper/main.swift#L15

It could be that for some reason there's a problem with launchd or the launchd database that causes the error.

We could try using `NSWorkspace.launchApplication(at:options:configuration:)` instead.

**Comment by mwolman** [comment]
I'm having the same issue on macOS Monterey

**Comment by cristiangrojas** [comment]
Having the same issue in Monterey, please tell us how to fix

**Comment by jakob** [comment]
Since we haven't received any more reports, I'm going to assume that this issue was fixed with commit 45b0d06 which was first released in Postgres.app 2.5.7.

I'm closing this issue. If you still experience this issue with Postgres.app 2.5.7 or newer, please let us know!
