### ISSUE TITLE
It keeps reporting "Port in use" when I try to restart Postgres.app

### ISSUE THREAD

**Issue by Zzzzzzzzzzzzzzzzz** [PostgresApp/PostgresApp#611]
It reports "Port in use" error when I stop the server and start again. I can ensure there is no other service listing on 5432. Client tools also report "connection refuse" at that time.
However, Postgres.app can't start again because of this strange messages.

It will work again if I reboot the OS but it is not convenient.
Is there any way to work around it?

**Comment by jakob** [comment]
Can you check the server log? It's possible the server is doing something (eg. waiting for a query to finish, or recovering from unsafe shutdown)

**Comment by Zzzzzzzzzzzzzzzzz** [comment]
I couldn't reprocue it any more. I fixed it by restarting the Mac. Big Sur is not stable enough it might be an OS issue. I will close this issue. thanks @jakob

**Comment by danieldunderfelt** [comment]
I am also having this problem. I wanted to restart the postgres server but the app kept saying that "The port is in use" even though it is absolutely not. The server logs said that the process was done and exited.

I think you have a bug in the "port in use" checker.

**Comment by jakob** [comment]
Thanks for reporting the issue, we've recently figured out what was causing it and fixed it in version 2.5.10.

See issue #676 for details.
