### ISSUE TITLE
initdb is not selecting correct locale 

### ISSUE THREAD

**Issue by bavistock** [PostgresApp/PostgresApp#614]
Hi, my MacBook locale is set to en_GB.UTF-8, but when I create and initialise a new database in the app it is created with the en_US.UTF-8 locale. It does this whichever version of Postgres I try to install. I thought it was supposed to be created using the system locale, am I doing something wrong?

**Comment by jakob** [comment]
The locale is hard coded to `--locale=en_US.UTF-8`. To be honest I don't recall why we did that; presumably to work around some issue.

This are the command that Postgres.app executes:

```bash
/Applications/Postgres.app/Contents/Versions/latest/bin/initdb -D "$DATADIR" -U postgres --encoding=UTF-8 --locale=en_US.UTF-8
/Applications/Postgres.app/Contents/Versions/latest/bin/pg_ctl start -D "$DATADIR" -w -l "$DATADIR"/postgresql.log -o "-p $PORT"
/Applications/Postgres.app/Contents/Versions/latest/bin/createuser -U postgres -p $PORT --superuser $USER
/Applications/Postgres.app/Contents/Versions/latest/bin/createdb -p $PORT $USER
```

($DATADIR is the data directory and $PORT the port you selected, or 5432 by default)

You can call initdb manually if you want to use a different default locale for the cluster. For each database that you create with createdb or "CREATE DATABASE" in the cluster, you can also choose a different locale.

After you manually init a cluster, you can add it in Postgres.app by showing the sidebar and then clicking the "+" button.

Can you let us know why you want to change the locale? If there's a problem with the default behavior, we could change it.

**Comment by bavistock** [comment]
Thanks Jacob, the guys at work wanted to check out what effect the differences between the 2 locales are as we've got some production databases that were inadvertently set to en_US.UTF-8 rather than en_GB.UTF-8. I spun up a cluster with postgres.app and found it was defaulting to en_US.UTF-8. The postgres documentation says initdb will try to establish the locale from locale environment variables  on the platform if the --locale value isn't provided. It will default to the C locale if all else fails.

I've used the manual commands you provided to get things up and running correctly now. However if the code didn't explicitly specify the locale it would work as per postgres documentation and could still be overridden with the commands you gave above if necessary.

Alternatively, I hacked the code in Server.swift:

```
	private func initDatabaseSync() -> ActionStatus {
		let process = Process()
		process.launchPath = binPath.appending("/initdb")
        	let identifier = Locale.current.identifier
		process.arguments = [
			"-D", varPath,
			"-U", "postgres",
			"--encoding=UTF-8",
			"--locale=" + identifier + ".UTF-8"
		] ...
```

Please forgive the poor quality of the hack above as I'm not a developer, but it illustrates the idea.

**Comment by jakob** [comment]
> However if the code didn't explicitly specify the locale it would work as per postgres documentation and could still be overridden with the commands you gave above if necessary.

The problem is that I don't remember why we used an explicit locale instead of using the default. I assume we did that to work around some issue. So I'm afraid that if we change that we'll end up breaking something for someone.

(Also, if you are having problems with locale, it could be that you are running into the issue of the broken collations on macOS. None of the UTF-8 collations are implemented on macOS, they are actually just aliases of the ASCII collation.

For this reason, Postgres.app ships with ICU, and you should use ICU collations if you do any string comparisons. This is also advisable on Linux, since glibc collations can cause versioning issues.)

**Comment by jakob** [comment]
Looks like I hardcoded it to en_US because of this issue: #205

**Comment by bavistock** [comment]
OK, thanks for taking a look and for giving a workaround for me.
