### ISSUE TITLE
Password Block

### ISSUE THREAD

**Issue by Jabaker35** [PostgresApp/PostgresApp#618]
I have done everything I know how to regarding the password but nothing seems to work at all. I have changed it using the prompt commands and still nothing. Every time I type psql in the terminal it keeps asking me for a password. Please help because I really need this for my final project.

**Comment by tbussmann** [comment]
> I have done everything I know how to regarding the password but nothing seems to work at all. 

What exactly are you trying to accomplish at all? 

A freshly setup server created by PostgresApp does contain two superusers named `postgres` and one according your user name. Further there is a database named after your user name. This should allow you to connect to it by simply calling `psql` w/o specifying further options like user and database (`psql` uses defaults to the current user for both). The easiest way to open `psql` (or the client you specified in the preferences) is to double click on a database icon in the PostgresApp GUI.

Technically there is no password set for either of the roles. In your `pg_hba.conf` you can see that there is `trust` authentication on both unix domain sockets and localhost TCP/IP-Sockets. Did you modify the `pg_hba.conf` on your instance? If so, a restart of the server is required to take effect.

If this is not working, I'd suspect you are actually not connecting to the server PostgresApp supplies, but another instance running on your system:

- check that only one postgresql server is running, e.g. by `ps aux | grep postgres`
   - if you are unsure how to manage them, [remove](https://postgresapp.com/documentation/remove.html) other PostgreSQL installations on your system like from homebrew, EBD, ...
- set the path to include the CLI tools of PostgresApp by `sudo mkdir -p /etc/paths.d && echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp` and open a new Terminal window afterwards
- check that the server is actually running and started successfully
- have a look to the server log file (can be found from the 'Server Settings' popup in PostgresApp)
- check that the port in use (default is 5432, can be configured in the 'Server Settings' popup in PostgresApp)

**Comment by Jabaker35** [comment]
I had to do a factory reset on my Mac and was able to get it working again. Thank you for your help.
