### ISSUE TITLE
Error when installing postgis_raster in pg13 on macOS < 10.15

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#635]
When attempting to install the `postgis_raster` extension in a Postgres 13 server running on macOS 10.12, 10.13 or 10.14 an Error is thrown:

```
# CREATE EXTENSION postgis_raster ;
ERROR:  could not load library "/Applications/Postgres.app/Contents/Versions/14/lib/postgresql/postgis_raster-3.so": dlopen(/Applications/Postgres.app/Contents/Versions/14/lib/postgresql/postgis_raster-3.so, 10): Symbol not found: _curl_mime_addpart
  Referenced from: /Applications/Postgres.app/Contents/Versions/14/lib/libgdal.29.dylib
  Expected in: /usr/lib/libcurl.4.dylib
 in /Applications/Postgres.app/Contents/Versions/14/lib/libgdal.29.dylib
```
With older Postgres versions and newer OS versions postgis_raster works.

Digging into it, `postgis` links `libgdal` (both provided by PostgresApp) which in turn uses the system provided `libcurl`. The mentioned symbol  `_curl_mime_addpart` is available from `libcurl` since 7.56.0, macOS 10.12 provides 7.51.0, 10.13 and 10.14 provide 7.54.0, 10.15 comes with 7.64.1. GDAL does have a version detection and fallback code for `curl_mime_addpart` but when built on 10.15 with the 10.15 SDK this does not help, despite our deployment target is set to 10.12. The older Postgres versions are still build on 10.12 or 10.10 respectively so the issue is happening only for Postgres 13.

I see three possible solutions:
* provide and link against our own version of `libcurl`
* build against the 10.12 SDK
* patch GDAL's version check

To not introduce more dependencies and limit the size of the package, I discarded option 1. 
I briefly looked into option 2 - the latest macos10.12 SDK seems to be 10.12.4 `16E185`, can be found and extracted from the download "Command Line Tools (macOS 10.12) for Xcode 8.3.2.dmg". When setting `SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.12.sdk` in the makefile the old libcurl is detected. But building against that old SDK brings it's own problems like being unable to link universal binaries.
So I decided to go with option 3 which is a bit hacky but seems to work well, according to my tests.

**Comment by jakob** [comment]
I just released the new Postgres.app binaries a few hours ago. Should we make new builds? Does this affect the PostgreSQL 14 beta as well?

**Comment by tbussmann** [comment]
Yes, that does affect pg14 as well which was built on macOS 11.5 with the CLT 12.5 containing SDK 11.3 `20E214`. This provides libcurl 7.64.1. 

Unfortunately, I was late with my fixes so they didn't make it in todays round of build. However, there are more changes in the pipeline so an update to our beta build is likely needed anyhow before the release. As there are no field complaints yet, I don't think an update for pg 13 is necessary at this point. I have the hope to be able to harmonise the build-process for pg13 and pg14 at some point, so we can phase out the 10.15 build VM. Maybe the next beta can include a pg13 built with that as well...
