### ISSUE TITLE
Starting Intel-only binaries crashes on Apple Silicon when Rosetta is not installed

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#638]
As reported by @jmanian in https://github.com/PostgresApp/PostgresApp/issues/602#issuecomment-953015169, it seems that Postgres.app crashes when you try to install/start a PG 13 or earlier PostgreSQL server without Rosetta installed.

As a work-around, you can run any app in Rosetta to trigger the Rosetta-Installer.

**Comment by cerniuk** [comment]
It doesn't matter whether or not Rosetta2 is installed or if it's runtime is already loaded, Postgres crashes on launch on M1 silicon on macOS 12.0.1 at launch with:

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /Applications/Postgres.app/Contents/Versions/14/lib/libpq.5.dylib
Referenced from: /Applications/Apps/*/Postgres.app/Contents/MacOS/Postgres
Reason: tried: '/Applications/Postgres.app/Contents/Versions/14/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
(terminated at launch; ignore backtrace)

It is attempting to use a hard pathname for referencing it's internal resources and assuming the app name is Postgres.app and assuming the app is being run from the /Applications on the main drive. Both assumptions are bad.

**Comment by jakob** [comment]
@cerniuk The fact that Postgres.app uses absolute path for dylibs has nothing to do with M1 and the reason for it has been previously discussed in issues #469, #562 and #601 (and possibly others).
