### ISSUE TITLE
Enabling PostGIS extension `address_standardizer` again

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#641]
Due to a change in the configure script of PostGIS, we have inadvertently been building PostGIS without the `address_standardizer` extension since PG 12.

I've attempted to fix the issue in commit 73737040c662d1961c7ab6a38bfe6dcf4b85f2d9

**Comment by jakob** [comment]
Related issues:
- https://github.com/PostgresApp/PostgresApp/issues/529#issuecomment-580863024
- https://github.com/PostgresApp/PostgresApp/issues/337#issuecomment-947163300

**Comment by tbussmann** [comment]
`address_standardizer` is included and apparently working again since v2.5.2 (Nov. 2021 release)
