### ISSUE TITLE
Load up postgres database from old files

### ISSUE THREAD

**Issue by Elf36** [PostgresApp/PostgresApp#645]
I have a 9.1 postgres database but no export how do I export or recreate a new running database from the new files ?

**Comment by jakob** [comment]
You can try if this old version of Postgres.app still works: https://github.com/PostgresApp/PostgresApp/releases/tag/9.1.0.0

Then you could create a dump and load it into a modern version of PostgreSQL.

But the best thing to do would be to use the same PostgreSQL build that you originally used. If some configure settings are different you might run into problems.

As a last ressort you can also build a version of PG 9.1 from source and use that to export the data.

Let me know if you need more help.

**Comment by Elf36** [comment]
thanks the old download works fine, I am having trouble though as I have no logins for the database at all

**Comment by jakob** [comment]
You can change the `pg_hba.conf` file in the data directory to not require passwords when logging in from the local computer by adding the following lines (this is actually the default setting):

```
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
```

**Comment by Elf36** [comment]
Yes I did that but the postage user seems to be not used and I don't know what the others might be - a bit difficult

**Comment by jakob** [comment]
Try either your local user name, or `postgres`. PostgreSQL user names do not need to be the same as the OS user names, and you don't need to have OS user names matching the PostgreSQL user names.

You can also try starting the server in [single user mode](https://www.postgresql.org/docs/10/app-postgres.html) using a command like this

```bash
postgres -D datadir --single postgres
```

and then query the catalog tables with queries like

```sql
select * from pg_database
select * from pg_user
```

**Comment by Elf36** [comment]
Im in…

***@***.*** ~ %  /Applications/Postgres.app/Contents/Versions/9.1/bin/postgres --single -O -D "/Users/rob/Library/Application Support/Postgres/data2/9_1" postgres

PostgreSQL stand-alone backend 9.1.4
backend>

**Comment by jakob** [comment]
You could now create the missing `postgres` superuser:

```sql
CREATE USER postgres SUPERUSER;
```

Then press Ctrl-D to quit, start the server normally, and then use `pg_dumpall -U postgres` to dump the database.

**Comment by Elf36** [comment]
Thanks
thats perfect !
