### ISSUE TITLE
failed: FATAL:  role "jonrivera" does not exist

### ISSUE THREAD

**Issue by jonrrivera** [PostgresApp/PostgresApp#648]

**Comment by jakob** [comment]
By default Postgres.app creates a PostgreSQL user with the same name as your system user name. If that user doesn't exist there are a few possible explanations:

1. You have a PostgreSQL server from another installation method running (eg. from Homebrew or EnterpriseDB)
2. You have Postgres.app running on a different user account on your machine
3. You deleted the jonrivera PostgreSQL user
4. Something went wrong when initializing the server.

Debug steps:

1. Try to connect with `psql -U postgres`
2. If that works, execute `SHOW data_directory;` to see if it's the same value as shown in Postgres.app
3. Execute `ps ax | grep postgres` and look for the full path of the postgres process. It should start with  `/Applications/Postgres.app/....`
