### ISSUE TITLE
pldebugger support broken?

### ISSUE THREAD

**Issue by apeters** [PostgresApp/PostgresApp#671]
It looks like the repo for the pldebugger referenced in the makefiles is no longer available

The make files all reference the pldebugger repo as being here: git://git.postgresql.org/git/pldebugger.git but this no longer resolves to anything.
see: [https://github.com/jasiek/PostgresApp/blob/master/src-12/makefile#L541](https://github.com/jasiek/PostgresApp/blob/master/src-12/makefile#L541)

The repo now appears to be hosted here: https://github.com/EnterpriseDB/pldebugger

**Comment by tbussmann** [comment]
> see: https://github.com/jasiek/PostgresApp/blob/master/src-12/makefile#L541


The link you are referring is pointing to a fork which is way behind this repo. The source for `pldeubgger` was already changed in commit c3af3fd06c53a872da70bbd4b6ae04c456804f91

**Comment by apeters** [comment]
Oh!  So sorry about that!  I should have caught that before creating the ticket.  :(
