### ISSUE TITLE
No shutdown when closing app

### ISSUE THREAD

**Issue by rsalmei** [PostgresApp/PostgresApp#674]
Please, why isn't the database shutting down when closing the app?

At least postgresql.org does say this: 
> [Postgres.app](https://postgresapp.com/) is a simple, native macOS app that runs in the menubar without the need of an installer. Open the app, and you have a PostgreSQL server ready and awaiting new connections. _Close the app, and the server shuts down._

But I'm sure it isn't. I CMD+Q the app, and the db can still be accessed.
Thanks.

**Comment by jakob** [comment]
If you press Cmd-Q, only the GUI app quits and the servers keep running. The elephant icon in the menu bar shows that Postgres.app is still running in the background.

If you click the elephant icon in the menu bar, and select the "Quit" command there, then Postgres.app also shuts down the servers and stops running in the background.

**Comment by rsalmei** [comment]
Never mind, I just figured out it was some weird bug on Bartender...
I've found the elephant icon within its preferences, and as soon as I changed its position back and forth it did appear.
Thanks.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/6652853/179070470-361216b2-22bf-43b5-a7e1-ec2d8557f2bf.png">
