### ISSUE TITLE
Postgress.app Can't Be Launched in /Applications sub-folders

### ISSUE THREAD

**Issue by uurazzle** [PostgresApp/PostgresApp#678]
Hi:

Thanks for your open-source project and contribution.

We distribute many applications in our environment and for organization, we place applications in sub-folders in /Applications like Programming, etc. "/Applications/Programming". It appears Postgress.app can't be launched in /Applications sub-folders and must be installed in "/Applications" to launch and execute properly.

Here is an example dialog when it's placed in a sub-folder...

<img width="372" alt="image" src="https://user-images.githubusercontent.com/6226458/184694854-6d602823-ca06-47f6-9aa5-2f2e7b07548e.png">

It would be great if "Postgress.app" supported non "/Applications" locations like sub-folders or in the users home folder, etc. Would allow greater flexibility in distribution and distribution location.

**Comment by jakob** [comment]
Postgres.app can now be launched from /Applications sub folders. For more details, see #693
