### ISSUE TITLE
It's possible to open multiple Preferences windows

### ISSUE THREAD

**Issue by nk9** [PostgresApp/PostgresApp#680]
Press Cmd-, multiple times and you'll be able to open new copies of the Preferences window even if one is already open.

https://user-images.githubusercontent.com/3646730/191514094-524bd33e-6b13-44ea-a6d5-2345fa511828.mp4

PostgresApp Version 2.5.6 (138)
macOS Monterey 12.6 (21G115)

**Comment by jakob** [comment]
Good catch. I'll have a look and hope to fix this for the next update.

**Comment by jakob** [comment]
That was a very simple fix. Thanks for reporting it. It will be fixed in the next release of Postgres.app (PG 15 will be released on Oct 6, maintenance release for older versions is planned on Nov 10)
