### ISSUE TITLE
Ask user whether to launch Postgres.app automatically on login

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#681]
Currently Postgres.app automatically configures itself to be launched automatically when the user logs in. On macOS Ventura it registers a login item, and on older versions of macOS it creates a launch agent.

While this is probably what 90% of our users want, it can still be surprising for users who just want to try out Postgres.app. On macOS Ventura users might be surprised by the warning on launch ("Postgres has installed a login item"), and on older versions users might be surprised that the elephant on the menu bar persists after reboots.

There are two other options:

1) Register the login item only when the user initializes the first server. Then the dialog appears as a response to user action, so it's not as surprising. If the user unchecks "Start automatically" before initializing the server, we would not register the login item.

2) Explicitly ask the user whether they want to start the server automatically, and only register the login item if necessary.

**Comment by anthonydb** [comment]
Purely as a user and as someone who [teaches SQL](https://nostarch.com/practical-sql-2nd-edition/), one of the things I love the most about Postgres.app is that it "simply works" without requiring a lot of attention from the user -- and many of my users are newbies at tech. I will of course work with whatever decision you make, but I'll just say that the way it works now is very helpful.

**Comment by jakob** [comment]
We've  discussed this issue today, and we decided not to ask the user and just register the login item automatically. The reason is that most people who download Postgres.app want it to run in the background, so that they can use it from other apps. Most people probably just want to install Postgres.app and then never think about it again. Asking whether it should launch automatically would just add unnecessary friction to the most common use case.

The notification in macOS Ventura makes it very clear what is happening, and clicking the notification can disable the login item if they prefer to launch it automatically.

**Comment by andrewtheis** [comment]
@jakob Not sure if it's a bug with Ventura, but even though it's removed from Login Items, it still launches on startup. Is there a way to work around this?

**Comment by jakob** [comment]
@andrewtheis Thanks for bringing this up. I can confirm odd behavior with Ventura. It seems that if you disable the Postgres.app login item, launching Postgres.app will somehow turn it on again. I'll open a new issue. Why does this feature have to be so buggy.......
