### ISSUE TITLE
ip4r

### ISSUE THREAD

**Issue by altitudedashboard** [PostgresApp/PostgresApp#683]
test=# create extension ip4r;
ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/ip4r.control": No such file or directory

**Comment by tbussmann** [comment]
The `ip4r` extension does not come bundled with Postgres.app. But usually you can easily compile and install it yourself, like with many other extensions:

* make sure you have the XCode command line tools installed: `xcode-select --install`
* make sure you have [configured your `$PATH` correctly](https://postgresapp.com/documentation/cli-tools.html) and to have restarted your Terminal afterwards
* make sure to have started Postgres.app at least once before or have it running
* download and extract the source of the extension (`ip4r` seems to be hosted [here on GitHub](https://github.com/RhodiumToad/ip4r))
* `cd` into the directory with the source
* run `make` (in case you get `Unsupported architecture` errors on older macOS, see #660)
* run `make install`
* connect the the database you want to install it
* run the SQL statement to load the extenion: `CREATE EXTENSION ip4r;`

Please note that you need to re-run the steps (up to and including `make install`) everytime you update Postgres.app later.

**Comment by altitudedashboard** [comment]
Thanks! It worked:

```
curl -LJO https://github.com/RhodiumToad/ip4r/archive/refs/tags/2.4.1.tar.gz
tar -xzvf ip4r-2.4.1.tar.gz
cd ip4r-2.4.1
make install
```

**Comment by georgkreimer** [comment]
Perfect! That works also well for pgvector

**Comment by cowlibob** [comment]
Thanks for the instructions, this helped me install h3-pg too.
