### ISSUE TITLE
PostgresApp Only Executes ONLY from "/Applications" not sub-folder or other locations

### ISSUE THREAD

**Issue by uurazzle** [PostgresApp/PostgresApp#684]
Hi:

I appreciate your work on the "PostgresApp" project and sharing it with the community.

One request, is in our environment we distribute a ton of applications and ideally would like to distribute "PostgresApp" to a sub-folder inside "/Applications" like "/Applications/Programming" or if a standard user could download it and install somewhere inside their home folder like "Desktop" or create an "Applications" folder like "/Users/[USERNAME]/Applications".

But, with the current release trying to launch "PostgresApp" from any location but "/Applications" gives the following error:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/6226458/195637090-985f022d-94f1-4c64-b7f8-48b0d5150c76.png">

Having the "PostgresApp" more flexible on its install location would ease and simplify distribution and usage cases like in our environment or in shared environments where users are standard users and NOT admin and can't install applications in "/Applications" etc.

**Comment by jakob** [comment]
Thanks for the feedback. This is a somewhat common request (see eg. #678) and we've been working it. We've solved most of the issues that prevent relocating Postgres.app, but we still not to make some changes to the GUI code to support it.

So it's something that we want to add, but we're not there yet.

**Comment by uurazzle** [comment]
Hi @jakob:

Ok, great it's on your roadmap. Would really make it easier to manage the distribution of the application and if it doesn't require admin access at all would help in an environment where their users aren't admin using the application like from their user folder or external media, etc.

I appreciate your reply.

**Comment by uurazzle** [comment]
Hi @jakob:

So, does this mean a recent release fixed the issue?

**Comment by jakob** [comment]
Postgres.app can now be launched any location folders. It still shows a warning if you do so, but you can continue without moving it to /Applications. For more details, see https://github.com/PostgresApp/PostgresApp/issues/693
