### ISSUE TITLE
Link against SFCGAL to support postgis_ sfcgal extension.

### ISSUE THREAD

**Issue by warpedgeoid** [PostgresApp/PostgresApp#685]
Since PostGIS 2.2, an extension called postgis_sfcgal is available which provides advanced SFCGAL-based geometry processing functions like ST_ApproximateMedialAxis and ST_StraightSkeleton. It does not appear that PostgreSQL bundled with the Postgres app is linked against SFCGAL and the PostGIS extension is not available.

Would it be possible for PostgresApp to eventually ship bundled PostGIS that does support SFCGAL and the postgis_sfcgal extension?

**Comment by tbussmann** [comment]
Thanks for expressing your interest in `postgis_sfcgal`. This is one of the extensions requested multiple times, see #337 and #529. For sure, it is certainly on our whish list for inclusion as it cannot be built easily independently. I hope to find some time for it soon.

**Comment by jakob** [comment]
Thanks to herculean efforts by @tbussmann, Postgres.app 2.6.2 now ships with postgis_sfcgal. Feedback wanted!

**Comment by warpedgeoid** [comment]
Feedback will be given 😁! Stay tuned.
