### ISSUE TITLE
I do have problems with postgresql stack builder

### ISSUE THREAD

**Issue by MORAWA-dev** [PostgresApp/PostgresApp#689]
I meet a lot of problems on installing the extensions, please help if u can
I  can't install  database driver  NQGSQL ,PJGDBC, THE MIGRATION TOOLKIT AND I DONT SEE POSTGIS IN POSGRES V15![Uploading Screenshot 2022-11-03 at 00.17.33.png…](<img width="1680" alt="Screenshot 2022-11-03 at 00 49 48" src="https://user-images.githubusercontent.com/72025891/199624666-89c8c026-b456-445f-901e-60df447173c0.png"><img width="1680" alt="Screenshot 2022-11-03 at 00 49 51" src="https://user-images.githubusercontent.com/72025891/199624704-e03ee335-1802-4430-8a8c-17c9e796ca4f.png">

**Comment by jakob** [comment]
Please contact EnterpriseDB if you have a problem with their installer.

Postgres.app is a different way of installing PostgreSQL and is not related to EnterpriseDB Stack Builder.
