### ISSUE TITLE
Automatically create new server once per major release

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#694]
In the past there has been recurring confusion for users with an existing database, because a new major PostgreSQL version wasn't easily discoverable once included in Postgres.app:
* #690 
* #574
* #399 
* #388 
* #523
* #422

This is mainly the case as a new Server is only created automatically if no existing servers were found at all (on a fresh install). Following on the ideas outlined in https://github.com/PostgresApp/PostgresApp/issues/574#issuecomment-631113763 we should change the behaviour as follows:

* At start of the Application, create a server with the latest available version if no server with that version exists and such a server was not being created before.

This solves the issues after upgrading while still allows to manually delete any unwanted servers without them to reappear automatically on every start. Further, this guides the user in upgrade scenarios to the proper mindset that the new server exists besides the old one and data needs to transferred between them. 

To be able to to this, we need to store information on what server versions already have been created in the past automatically (or include manual creations, too?). Additionally, we should keep the behaviour of unconditionally creating a server on start if no server exists at all.

**Comment by jakob** [comment]
I've already partially implemented this in febdfc9719921423e19254e41ef5bb59dfbac0f8, but I think I broke the last part ("unconditionally creating a server on start if no server exists").

**Comment by jakob** [comment]
I think we can close this. We've implemented the changes and released them in v2.6.
