### ISSUE TITLE
Always display the sidebar

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#695]
Many users have been confused by the fact that the sidebar was not expanded, which renders other available servers and more importantly, the `+` button invisible. The idea was to hide additional complexity for the majority of users that only use a single server (ref https://github.com/PostgresApp/PostgresApp/issues/399#issuecomment-316660460), similar to how Postgres.app 1 was behaving.

Some of the related discussions are:
* #595
* #445
* #399
* #574
* #625 
* #429
* #422
* #388

Over the years, it has become more and more common for users to have multiple servers configured. Implementing #694 will further add to this. In 2021 we changed the default for the sidebar to be expanded in d4f333663e1cf78c7d3e1a09c7bb3d5d46ef699c For the future I propose to remove the collapsible side bar feature all-together:
* always show the expanded side bar
* remove the button to collapse / expand side bar
* remove or ignore the entry in our user defaults domain

This would also solve #668

**Comment by jakob** [comment]
I've implemented this in bfa988df49f779617356542b79dedda961c50d78
