### ISSUE TITLE
Dont work

### ISSUE THREAD

**Issue by eflaten** [PostgresApp/PostgresApp#698]
There is a kind of incompatibility  with my installation. The error message is: "PostgreSQL version not installed".
 I have the latest macos, 13.2,  
The postgres.app is version 2.5.12 (171) 
There is also PostgreSQL 9.6.

Thanks for any help on this :)

**Comment by tbussmann** [comment]
The new installation of Postgres.app seem to have found a data directory of an older installation still on your machine. If you just want to start a fresh PostgreSQL 15 server, make sure to have the side bar expanded (![Bildschirmfoto 2023-01-28 um 23 20 08](https://user-images.githubusercontent.com/6412090/215293691-c93320de-c2ce-4181-8355-93507a97c42d.png)) and then click the ![Bildschirmfoto 2023-01-28 um 23 33 00](https://user-images.githubusercontent.com/6412090/215294116-0dad0eca-a17d-4c23-8bd7-aa5ff118c552.png) icon to create and then initialise a new server instance. We will automate this with the upcoming release, see #694.

Additionally you can optionally delete the data directory (see `Server Settings...` - `Data Directory` - `Show`) of the old 9.6 server and remove it from the list `-`. 

If you instead need to access the data stored in the previous version, you can [download](https://postgresapp.com/downloads.html) a bundle of Postgres.app that contains the necessary binaries for the PostgreSQL version in question - usually the "Postgres.app with all currently supported versions" will do. In you case, Version 9.6 is [deprecated](https://www.postgresql.org/support/versioning/) and unsupported. You can still try the last bundle of PostgresApp that included the version of PostgreSQL in [legacy downloads](https://postgresapp.com/downloads_legacy.html) and should [migrate](https://postgresapp.com/documentation/migrating-data.html) the data as soon as possible to a supported version.

**Comment by tbussmann** [comment]
Were you able to resolve your issue with the advises given, @eflaten? 

Today's releases [v2.6](https://github.com/PostgresApp/PostgresApp/releases/tag/v2.6) should automate the process to generate a server with the latest version if no such was found or created before.

**Comment by eflaten** [comment]
@tbussmann. It worked like you said over. I also upgraded. Thanks :)

**Comment by tbussmann** [comment]
great to hear!
