### ISSUE TITLE
Jakob Egger added items that can run in the background 

### ISSUE THREAD

**Issue by ayajulie** [PostgresApp/PostgresApp#699]
Hey, 

this issue is related to this one which has been #677 closed last year but it doesn't seem like the fix was sufficient I keep getting these notifications every time I turn on my mac. I've toggled off everything that seem related to Postres but I keep running into the issue.
 [](url)
![new_issue](https://user-images.githubusercontent.com/56846288/215828507-ffff6f85-94d3-4be8-b5dd-1b7c7480e9dc.png)

![new_issue_2](https://user-images.githubusercontent.com/56846288/215829922-8b7a6bbb-189d-401f-9697-491d334b3b6b.png)
![new_issue_3](https://user-images.githubusercontent.com/56846288/215829932-c6451af4-05e8-4da7-9674-c8f78860ebde.png)

**Comment by jakob** [comment]
The issue was fixed in Postgres.app 2.5.10. If you have an older version of Postgres.app installed on your Mac, you will still see the warnings.

Can you check which version of Postgres.app you have on your Mac? Just go to your Applications folder, right click on Postgres.app, and click "Get Info".

**Comment by ayajulie** [comment]
I updated to the latest version and I don't get the notifications anymore, thanks again
