### ISSUE TITLE
Postgres.app adds itself back to login items after being disabled

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#701]
> Not sure if it's a bug with Ventura, but even though it's removed from Login Items, it still launches on startup. Is there a way to work around this?

_Originally posted by @andrewtheis in https://github.com/PostgresApp/PostgresApp/issues/681#issuecomment-1424554048_

**Comment by jakob** [comment]
Apple has introduced a new API for login items in macOS Ventura, `SMAppService`. We use this API to register the Postgres Login Helper item.

We try to register this item on every launch by calling `SMAppService.register()`. According to the docs, that should be fine, since trying to re-register an already registered item just returns an error (that we log, but ignore).

For some reason, this seems to re-enable login items after they have been disabled. I'm not sure why this happens, so I have done some investigations:

1. After calling `SMAppService.register()`, the `SMAppService.status` becomes `.enabled`, as expected.
2. After relaunching the app, this status is preserved, and calling `SMAppService.register()` does not return an error (against the documentation, which says it should return `kSMErrorAlreadyRegistered`)
3. After logging out and back in again, this status is preserved, and calling `SMAppService.register()` does not return an error
4. When disabling the login item in system setting, the status turns to `.requiresApproval` and trying to register it fails with error code 1 "Operation not permitted". (not what the docs say, but close enough)
5. When I now log out and log back in again, the status turns into `.statusNotFound`, and trying to register it succeeds without error, and the item is turned on again in system settings!!

The last part seems to be the reason why Postgres.app starts again. If this is actually how macOS behaves, it seems we have to add back the "start on login" checkbox in Postgres.app preferences, because macOS seems to forget the state!

I've done my investigations with a non-notarized app, maybe the behavior is different for notarized apps. It could also be that the problem only occurs when updating Postgres.app, since the docs make some vague mention that items need to be re-registered after changing the binary.

**Comment by jakob** [comment]
Note to self: `sfltool dumpbtm` seems to print currently registered login items and their status.

**Comment by jakob** [comment]
I can no longer reproduce the issue on macOS 13.2.1. It seems this was an Apple bug and they fixed it.

@andrewtheis can you confirm whether the checkbox in System Settings now works as expected?

**Comment by Nezteb** [comment]
Before a reboot, I opened `Postgres.app` and took this screenshot:

<img width="1033" alt="Screenshot 2023-04-05 at 8 27 22 AM" src="https://user-images.githubusercontent.com/3588798/230130654-9d49578c-c855-43df-b9de-f2a0af9e659c.png">

(I forgot to include the `Postgres.app` version info in the screenshot, but it's the latest: 2.6)

After taking screenshot, I "quit" `Postgres.app` from the menu bar. Then I rebooted my machine and took this screenshot:

<img width="1362" alt="Screenshot 2023-04-05 at 8 31 38 AM" src="https://user-images.githubusercontent.com/3588798/230134130-0c1bb592-0a6d-4d0f-bd2f-f6b270a5187f.png">

It also shows up in the menu bar (I forgot to include it in the screenshot though). I did _not_ manually start `Postgres.app`. It also is not in my login items:

<img width="484" alt="Screenshot 2023-04-05 at 8 35 27 AM" src="https://user-images.githubusercontent.com/3588798/230131194-9ff0acff-1450-4e88-a514-501fde5badf2.png">

So I think this is still an issue. 😅

**Comment by Nezteb** [comment]
The area below login items is for background applications though?

> **Allow in the Background**
> Applications add background items to perform tasks when the application isn't open, such as checking for software updates or syncing data. Turning off a background item may prevent these tasks from being completed.

The name and description imply this should have nothing to do with login items and `Postgres.app` starting automatically. Either way, I'll give it a shot for my next reboot!

> It seems this was an Apple bug and they fixed it.

I don't see how this could be an Apple bug? 😅 `Postgres.app` starting automatically with the "allow in the background" checkbox enabled still seems like an issue.

The app:
```
                 UUID: 78691977-A83F-472C-B24A-85258564A722
                 Name: Postgres
       Developer Name: Jakob Egger
      Team Identifier: ZF84SJ5A3G
                 Type: app (0x2)
          Disposition: [disabled, allowed, visible, not notified] (2)
           Identifier: identifier "com.postgresapp.Postgres2" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = ZF84SJ5A3G
                  URL: file:///Applications/Postgres.app/
           Generation: 0
    Bundle Identifier: com.postgresapp.Postgres2
```

The login item:
```
                 UUID: 39B71D2C-1AB1-4979-992D-0837DCCB8B19
                 Name: PostgresLoginHelper
       Developer Name: Jakob Egger
      Team Identifier: ZF84SJ5A3G
                 Type: login item (0x4)
          Disposition: [enabled, disallowed, visible, notified] (9)
           Identifier: identifier "com.postgresapp.Postgres2LoginHelper" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = ZF84SJ5A3G
                  URL: Contents/Library/LoginItems/PostgresLoginHelper.app
           Generation: 2
    Bundle Identifier: com.postgresapp.Postgres2LoginHelper
    Parent Identifier: identifier "com.postgresapp.Postgres2" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = ZF84SJ5A3G
```

The `Disposition` of the login item still includes `enabled` (I don't have `Postgres.app` running right now).

**Comment by jakob** [comment]
> The name and description imply this should have nothing to do with login items

I guess Apple's description is misleading. The section labelled "Allow in the background" allows you to disable login items and launch agents installed by apps. When you leave the toggle on, apps can start processes when logging in; if you turn the toggle off, apps can't start processes on login.

Before macOS 13, every app had it's own setting to control the "launch on login" behavior. In macOS 13, it's now all in one place in System Settings. Unfortunately the label + description is misleading, because apps are free to run background tasks once you open them regardless of whether the toggle is on or off. The toggle only controls which apps can launch stuff on login.

> It seems this was an Apple bug and they fixed it.

>> I don't see how this could be an Apple bug?  

The bug was that the toggle turned itself back on when you log out, log in, and then launch the app. I observed the bug on macOS 13.1. At first I wasn't sure if this is a problem in how we call the API in Postgres.app, but since I can no longer reproduce this after updating macOS to 13.2.1, I assume it was an Apple bug and they fixed it. It's a new API that was introduced in macOS 13, so bugs aren't really surprising.

**Comment by Nezteb** [comment]
Wow that is a misleading description indeed. 🤦‍♂️

Thanks for explaining! I only recently started using macOS13 and didn't realize any of that! I had assumed things worked the same as they did before macOS 13 but with new UI. How silly of me, considering Apple loves to change things for no obvious reason. 😏😂  

Alright, I'll leave that toggle off for `Postgres.app`. I'll also probably audit the other apps I'm allowing to run in the background while I'm at it. 😅
