### ISSUE TITLE
How to use pg_upgrade from 14 to 15 with locale provider change?

### ISSUE THREAD

**Issue by jplock** [PostgresApp/PostgresApp#702]
PostgreSQL 15 is now using `--locale-provider=icu --icu-locale=en-US --data-checksums` when running `initdb`.

When trying to use `pg_upgrade` to upgrade a 14 database, I'm getting:

```
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Creating dump of global objects                             ok
Creating dump of database schemas                           
                                                            ok

locale providers for database "template1" do not match:  old "libc", new "icu"
Failure, exiting
```

Is there a way to change the locale provider of my 14 databases to be `icu`?

```
postgres=# \l
                                                  List of databases
    Name    |  Owner   | Encoding |   Collate   |    Ctype    | ICU Locale | Locale Provider |   Access privileges   
------------+----------+----------+-------------+-------------+------------+-----------------+-----------------------
 jplock     | jplock   | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 postgres   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | 
 template0  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | =c/postgres          +
            |          |          |             |             |            |                 | postgres=CTc/postgres
 template1  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |            | libc            | postgres=CTc/postgres+
            |          |          |             |             |            |                 | =c/postgres
```

**Comment by tbussmann** [comment]
You cannot change the default locale of a database (this includes its provider). This can only be set when creating a database and it must match its template database, if you are not using `template0` as template.

While PostgreSQL introduced the concept of locale providers in version 10, the possibility to define it on a cluster or database default level is new to version 15. 

So no, unfortunately, you cannot change the locale provider of your 14 databases to `icu`. Thus, the default clusters created by Postgres.app cannot be upgraded from 14 to 15 using `pg_upgrade`, you need to use `pg_dumpall`[^1] for this. If you like, you can however create a PostgreSQL 15 cluster in Postgres.app which still uses `libc` locales if you run the `initdb`[^2] by hand. With this, you should be able to use `pg_upgrade`.

[^1]: the easiest would be to start the old 14 server, create a new empty 15 server on a different port (eg. 5415), and initialize it. Then open a terminal and run `pg_dumpall | psql -p 5415`, stop both servers, change the new one to the default port, disable the autostart of the old one and enable it at the new one and start that again. (this expects using the "Postgres.app with all currently supported versions" [bundle](https://postgresapp.com/downloads.html) and the [path](https://postgresapp.com/documentation/cli-tools.html) to be configured correctly)

[^2]: create a server in the UI, but don't click the 'Initialize' button. Then run:
`initdb -D /Users/$USER/Library/Application\ Support/Postgres/var-15 -U postgres --encoding=UTF-8 --locale=en_US.UTF-8 --data-checksums` (alter the path to the data directory to match the one configured in the UI - it doesn't need to exist), start the server in the UI and run `createuser -U postgres --superuser $USER; createdb $USER`. Afterwards, you can safely dismiss the 'Reindexing recommended' warning in the UI.

**Comment by jplock** [comment]
Is it safe to assume, going forward on all major version releases, PostgresApp will use the icu provider?

**Comment by tbussmann** [comment]
That would be the assumption. However, I don't yet know how `pg_upgrade` will deal will collation version changes in the future. Currently, it doesn't care but the new cluster will emit a warning on mismatch.
