### ISSUE TITLE
Require Version of postgres not found

### ISSUE THREAD

**Issue by ghilmanrandhawa** [PostgresApp/PostgresApp#704]
Despite installing various versions of the Postgres app, I consistently encounter an error indicating that the required version of Postgres is not installed when attempting to open the application. Even after confirming that I have installed version 15.1 of Postgres on my Mac, I still face this problem.

<img width="607" alt="Screenshot 2023-03-08 at 12 56 56" src="https://user-images.githubusercontent.com/71902780/223654581-59d55d89-0daa-436d-8d14-4b4a65abe498.png">
<img width="476" alt="Screenshot 2023-03-08 at 13 01 30" src="https://user-images.githubusercontent.com/71902780/223655462-dce5378f-b34a-43df-ad1f-554665a306b3.png">

**Comment by jakob** [comment]
Can you provide us with three bits of information:

1. Open Postgres.app, and from the Postgres menu choose "About Postgres". Which version/build are you using?

2. Click the "Server Settings" button. What does it say under "Binaries"?

3. In Terminal, type the command `which psql`. What does it say?

**Comment by jakob** [comment]
I'm guessing the problem was an incorrect binary directory. Postgres.app version 2.6.1 should automatically fix this.

I'm closing this issue, if you still experience the issue with 2.6.1, please reopen it!
