### ISSUE TITLE
Disable auto start of postgres server 

### ISSUE THREAD

**Issue by sindhubb** [PostgresApp/PostgresApp#705]
Hi, 

I am happy with the auto start of the postgres app but not which postgres server it starts. 
![image](https://user-images.githubusercontent.com/72066862/227202116-9d4e9bcc-e5a8-447d-8d0f-2eee9a29e366.png)
As you can see I have 3 different postgres servers. 

The app however automatically start postgres 14. I do not want this. 

I want to:
1. Configure which server to start with
2. Disable auto start of any postgres server at all, even if the app is running.

**Comment by jakob** [comment]
Please click the "server settings" button for each server, and you can select whether to auto-start it.

Currently, if multiple servers with the same port are set to autostart, a random one will start and the others will fail.

**Comment by sindhubb** [comment]
> 

![image](https://user-images.githubusercontent.com/72066862/227416344-d6dcacbd-b4ba-4e3b-9eb1-9b642239a597.png)

Thank you! I did not notice this before.
