### ISSUE TITLE
Status not updated when switching between servers in the UI

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#710]
If two servers are configured on the same port and one is running, the other shows "Port in use". If the running server is stopped its own status changes to "Not running". When switching to the other server, its status continues to show the no longer valid "Port in use". The same happens if both server are in "Not running" and one gets started. The other should then change to "Port in use".

A wrong status is corrected if the Start / Stop / Initialise buttons of the affected server are pressed. The status should better be updated automatically when switching servers in the side bar. However, if a server is started / stopped using the menu helper, all status information in the App are already updated automatically. 

I have tested this in version 2.6 and verified the issue it also in 2.5.12 so it seems not to be a side-effect of the recent changes made for relocateability.

**Comment by jakob** [comment]
This was fixed in 7c7c0f0006bdf8b2b3257d83e3af079e22affb9f (v2.6.2 and later)
