### ISSUE TITLE
Unable to build universal on Mac (M1Max)

### ISSUE THREAD

**Issue by aready87** [PostgresApp/PostgresApp#711]
**Background:** PostgresApp.dmg have been working well on my Mac M1Max. But I wanted "wal2json" plugin, hence I attempted to build the binary following the Readme.md instructions. (If I understand correctly, wal2json does not come with the downloadable .dmg file, but gets built if you build the binary yourself.)

**Problem:** After downloading the code then going to the src-15 subdirectory in a terminal, I try: "make". Makefile begins downloading and attempts to build. However, I get the following error and the build is terminated: 
```
cd openssl-1.1.1t/build_arm64 && lipo -create ./libcrypto.1.1.dylib ../build_x86_64/libcrypto.1.1.dylib -output ./libcrypto.1.1.dylib
fatal error: /Library/Developer/CommandLineTools/usr/bin/lipo: ./libcrypto.1.1.dylib and ../build_x86_64/libcrypto.1.1.dylib have the same architectures (x86_64) and can't be in the same fat output file
make: *** [/Applications/Postgres.app/Contents/Versions/15/lib/libssl.dylib] Error 1
```

**Attempts:** 
- I installed MacPorts and installed the dependencies using the recommended command: "sudo port -N install autoconf automake pkgconfig libtool docbook-xml-4.5 docbook-xsl-nons fop". Same error.
- I also installed cmake using "sudo port cmake". Same error.
- I tried building src-14. Same error.

Am I attempting to build the binary incorrectly?
Thank you in advance.

**Comment by tbussmann** [comment]
The `wal2json` extension does come bundled with Postgres.App, there should be no need to build anything yourself to use it. Minimal instructions to exercise `wal2json`:

* in `psql` run `ALTER SYSTEM SET wal_level = logical;` then stop and start the Postgres server. 
* back in `psql`:  
```
SELECT pg_create_logical_replication_slot('test_slot', 'wal2json');
SELECT pg_logical_emit_message(false, 'wal2json', 'hello world');
SELECT * FROM pg_logical_slot_get_changes('test_slot', NULL, NULL);
SELECT pg_drop_replication_slot('test_slot');
```
* further examples, like using `pg_recvlogical` can be found at https://github.com/eulerto/wal2json

I have no immediate idea why your attempt to build the universal binary of `openssl` does result in two x86_64 builds in your environment. Unfortunately, the builds tend to vary depending on the installed toolsets and dependencies, so further analysis would be necessary.

**Comment by aready87** [comment]
Thank you for the quick reply! I was confused that only the PostGIS and plv8 (for versions 13 and older) were mentioned on the downloads page. This cleared up my confusion. Thanks again.
