### ISSUE TITLE
Add vector extension support

### ISSUE THREAD

**Issue by courtstarr** [PostgresApp/PostgresApp#716]
I have the latest version of PostresApp running on mac but I get the following error when trying to create the pgvector extension.

```
CREATE EXTENSION vector;

ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/Versions/14/share/postgresql/extension/vector.control": No such file or directory
```

https://github.com/pgvector/pgvector/

**Comment by tbussmann** [comment]
While we cannot include every extension available, we need to find a measure on what is demanded often, so thanks for raising your voice.

Even if an extention is not included in the distrubution of Postgres.app, most extensions can be built and added by the users themself. We wanted to document these steps for quite some time and I planned to provide a list of tested working extensions. If you search the issues, you can find some recipies I gave in the past. Generally, it boils down to the steps I mentioned last time in https://github.com/PostgresApp/PostgresApp/issues/683, which work for pgvector pretty well.

Another option that should work and simplifies the build-process is to install the [pgxnclient](https://pgxn.github.io/pgxnclient/)

Please note that you need to re-run the steps for installing customs extensions every time you update Postgres.app later.

**Comment by laran** [comment]
+1 to add the vector extension. It enables AI-related use-cases.

**Comment by jakob** [comment]
Was mentioned on HN today: https://news.ycombinator.com/item?id=35827436

May be worth including (even though I have no idea what it does 😃)

**Comment by flexchar** [comment]
I've installed successfully. 

Use official instructions + set the path for the postgresapp 
```bash
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin
cd /tmp
git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git
cd pgvector
make
make install
```

May need sudo for the last command AND may need to give permission to modify other apps to Warp (my choice of Terminal app). Permission is given in Settings -> Privacy & Security -> App Management -> Warp turn on the toggle.

**Comment by jakob** [comment]
Postgres.app 2.6.2, released today, now ships with the pgvector extension (PostgreSQL 15 only). Thanks to @tbussmann for adding it.

Since we don't use it personally, we'd love to get some feedback to make sure it works as expected.

**Comment by ankane** [comment]
Hi @tbussmann and @jakob, just tested on ARM and it's working great. Big thanks for adding! Feel free to let me know if anything comes up.

**Comment by courtstarr** [comment]
HUGE THANKS @tbussmann & @jakob. Appreciate your contributions!

**Comment by ammarck** [comment]
Hi, I tried the latest posgres app and I don't have the pgvector installed there. Do I need to do anything?
```
postgres=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description
---------+---------+------------+------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
(1 row)

postgres=# SELECT *
postgres-# FROM pg_extension;
  oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-------+---------+----------+--------------+----------------+------------+-----------+--------------
 13823 | plpgsql |       10 |           11 | f              | 1.0        |           |
(1 row)
```

**Comment by ammarck** [comment]
I ran it and I got this error:
```
postgres=# CREATE EXTENSION vector;
ERROR:  could not access file "$libdir/vector": No such file or directory
```

**Comment by ankane** [comment]
What version of Postgres.app are you on, and what's the output of `SELECT VERSION();`?

**Comment by ammarck** [comment]
![Postgres app version](https://github.com/PostgresApp/PostgresApp/assets/97814052/d6261473-80fb-440e-a210-d642cb8c4114)

```
postgres=# SELECT VERSION();
                                                       version
---------------------------------------------------------------------------------------------------------------------
 PostgreSQL 15.3 on aarch64-apple-darwin21.6.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.102), 64-bit
(1 row)
```

**Comment by ammarck** [comment]
Do I need to re-create the database on the new version to work? I am using a db that I created before

**Comment by ammarck** [comment]
Re-creating a database didn't help

**Comment by jakob** [comment]
That version of Postgres.app definitely ships with the vector extension. There is something fishy going on.

Can you check if the binaries path is correct? (click on server settings in Postgres.app)

**Comment by ammarck** [comment]
Looks right to me:
```
❯ ls /Applications/Postgres.app/Contents/Versions/15/bin
clusterdb         gdal_grid         gdalmanage        invproj           pg_checksums      pg_restore        pgtopo_import
createdb          gdal_rasterize    gdalmdiminfo      nearblack         pg_config         pg_rewind         postgres
createuser        gdal_translate    gdalmdimtranslate ogr2ogr           pg_controldata    pg_test_fsync     postmaster
cs2cs             gdal_viewshed     gdalsrsinfo       ogrinfo           pg_ctl            pg_test_timing    proj
dropdb            gdaladdo          gdaltindex        ogrlineref        pg_dump           pg_upgrade        psql
dropuser          gdalbuildvrt      gdaltransform     ogrtindex         pg_dumpall        pg_verifybackup   raster2pgsql
ecpg              gdaldem           gdalwarp          oid2name          pg_isready        pg_waldump        reindexdb
gdal-config       gdalenhance       geod              pg_amcheck        pg_receivewal     pgbench           shp2pgsql
gdal_contour      gdalinfo          initdb            pg_archivecleanup pg_recvlogical    pgsql2shp         vacuumdb
gdal_create       gdallocationinfo  invgeod           pg_basebackup     pg_resetwal       pgtopo_export     vacuumlo
```

However I don't see `vector` there. Shouldn't it be in this dir?

**Comment by jakob** [comment]
No. Extensions are in `lib/postgresql`, not in `bin`.

I was thinking that you might have multiple copies of Postgres.app on your computer. We recently added support for launching Postgres.app from locations other than /Applications, which is why I asked you to check the "Binaries" path. Please do this:

1) Select the problematic server in the Postgres.app sidebar
2) Click the "Server Settings" button
3) Check the path labelled "Binaries"

If that path isn't correct, that could cause this problem.

**Comment by tbussmann** [comment]
> I ran it and I got this error:
> 
> ```
> postgres=# CREATE EXTENSION vector;
> 
> ERROR:  could not access file "$libdir/vector": No such file or directory
> ```

That error indicates that the extension's control file is present but not its library which means you've got a broken installation somehow.

The information on the 'Binaries' path Jakob asked for, can be found in the UI of Postgres.app: Select the server in question and click on 'Server Settings...'

If it reads '/Applications/Postgres.app/Contents/Versions/15/bin' you have a standard setup. If in that case the file `/Applications/Postgres.app/Contents/Versions/15/lib/postgresql/vector.so` is missing, as the error indicates, you should be able to fix it by re-downloading Postgres.app and replacing the Application bundle. No need to recreate the databases.

But I'm wondering where the file went? Did you previously try to compile pgvector on your own? Sometimes virus scanner are doing strange quarantine things, too - do you happen to have any kind of security software running in the background?

**Comment by ammarck** [comment]
Ok so I uninstalled Postgres App and installed it again (I removed all files as suggested in [Uninstallation](https://postgresapp.com/documentation/install.html). Now it actually works!

I had installed Postgres app last year and only yesterday when I actually updated it. Something maybe got broken when I upgraded or uninstalled/installed. Not sure what.

Thanks all!!!

**Comment by jamonholmgren** [comment]
Also uninstalled postgres app and reinstalled, and it also fixed the issue. For some reason just upgrading it doesn't install pgvector.
