### ISSUE TITLE
Building and installing extensions against Postgres.app no longer works on latest Ventura

### ISSUE THREAD

**Issue by jakob** [PostgresApp/PostgresApp#719]
I've just tried building and installing a simple PostgreSQL extension on macOS Ventura (13.3.1), and the install step now fails.

I get this error:
```
install: /Applications/Postgres.app/Contents/Versions/16/lib/postgresql/[extension-name].dylib: Operation not permitted
```

It even fails when using sudo.

I'm not sure if this always happens, but it seems that macOS is somehow blocking modification of signed apps. I think on my first attempt, macOS showed a notification that something was blocked, but it doesn't any more, and I don't see anything in Security settings. (I might be looking in the wrong place, though)

I can still install the extension manually by copying the file with Finder.

**Comment by jakob** [comment]
I figured out how to do it:

1. Go to System Settings -> Privacy & Security -> App Management
2. Allow Terminal to "update or delete other applications"

**Comment by anthonydb** [comment]
Hi! As an avid follower of Postgres.app, I just wanted to clarify something. This issue doesn't seem to affect my ability to run `CREATE EXTENSION extension` while connected to a Postgres.app database. Is that correct or should I expect to not be able to do that?

I'm on Ventura 13.4 and using Postgres.app 2.6.2.

**Comment by jakob** [comment]
@anthonydb No, this only affects you if you want to compile extensions that are not included with Postgres.app.

The extensions included with Postgres.app work fine!

**Comment by jakob** [comment]
The part that fails is the `make install` step, which is not necessary for the extensions we include with Postgres.app.

`CREATE EXTENSION` works fine and is not affected by this, since it doesn't modify the App itself -- it only installs the extension in the database.
