### ISSUE TITLE
pg_cron extension

### ISSUE THREAD

**Issue by aagranados** [PostgresApp/PostgresApp#728]
Is there any hack to install pg_cron?

Is there a straightforward way of installing pg_cron when using postgres.app without downloading the source code for pg_cron from https://github.com/citusdata/pg_cron, installing a compiler, compiling, troubleshooting errors, and installing?

**Comment by aagranados** [comment]
Manage to install it by following these steps:
https://github.com/PostgresApp/PostgresApp/issues/683#issuecomment-1274754377
Thank you.

**Comment by Pyrolistical** [comment]
Thanks, this worked for me on Apple Silicon.

```sh
git clone https://github.com/citusdata/pg_cron.git
cd pg_cron
# pg_config was already on PATH for me
make
sudo make install
```
If last command failes due to MacOS security, allow it under `System Settings → Privacy & Security → App Management → Toggle on the thing you can ran the command with`. Then re-run `sudo make install`

Restarted postgres server.
Finally, follow these steps https://github.com/citusdata/pg_cron#setting-up-pg_cron

**Comment by crystaldonut** [comment]
Hi there, I was unable to compile on sequoia on Postgres 17 app 

Basically
`pg_iovec.h:110:12: error: comparison of integers of different signs: 'ssize_t' (aka 'long') and 'const size_t' (aka 'const unsigned long') [-Werror,-Wsign-compare] 110 |                 if (part < iov[i].iov_len) | `

Here's the dump
`make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro  -Os -mmacosx-version-min=10.13 -arch arm64 -arch x86_64  -fvisibility=hidden -std=c99 -Wall -Wextra -Werror -Wno-unused-parameter -Wno-implicit-fallthrough -Iinclude -I/Applications/Postgres.app/Contents/Versions/17/include -I. -I./ -I/Applications/Postgres.app/Contents/Versions/17/include/postgresql/server -I/Applications/Postgres.app/Contents/Versions/17/include/postgresql/internal -I/Applications/Postgres.app/Contents/Versions/17/share/icu -I/Applications/Postgres.app/Contents/Versions/17/include/libxml2 -I/Applications/Postgres.app/Contents/Versions/17/include -I/Applications/Postgres.app/Contents/Versions/17/include  -I/Applications/Postgres.app/Contents/Versions/17/include  -c -o src/job_metadata.o src/job_metadata.c
In file included from src/job_metadata.c:22:
In file included from /Applications/Postgres.app/Contents/Versions/17/include/postgresql/server/access/hash.h:26:
In file included from /Applications/Postgres.app/Contents/Versions/17/include/postgresql/server/storage/bufmgr.h:17:
/Applications/Postgres.app/Contents/Versions/17/include/postgresql/server/port/pg_iovec.h:71:12: error: comparison of integers of different signs: 'ssize_t' (aka 'long') and 'const size_t' (aka 'const unsigned long') [-Werror,-Wsign-compare]
   71 |                 if (part < iov[i].iov_len)
      |                     ~~~~ ^ ~~~~~~~~~~~~~~
/Applications/Postgres.app/Contents/Versions/17/include/postgresql/server/port/pg_iovec.h:110:12: error: comparison of integers of different signs: 'ssize_t' (aka 'long') and 'const size_t' (aka 'const unsigned long') [-Werror,-Wsign-compare]
  110 |                 if (part < iov[i].iov_len)
      |                     ~~~~ ^ ~~~~~~~~~~~~~~
2 errors generated.
make: *** [src/job_metadata.o] Error 1`


Mac mini  M2 Pro
OSX 15.0 (24A335)

has anybody seen this?
