### ISSUE TITLE
add pg_idkit extension

### ISSUE THREAD

**Issue by gvkhna** [PostgresApp/PostgresApp#730]
Here’s the extension. Hopefully it’s popular enough to add. We really need modern UUIDs these days. 

https://github.com/VADOSWARE/pg_idkit

https://supabase.com/blog/choosing-a-postgres-primary-key

**Comment by jakob** [comment]
I assume that the main interest is in UUIDv7? All the other IDs are probably pretty niche.

It looks like PostgreSQL 17 will probably support UUIDv7 natively: https://commitfest.postgresql.org/44/4388/

I don't think we should add an extension now that will be mostly obsolete in a year.

It's also pretty easy to implement UUIDv7 generation in a custom function. Here's one that I use:

```sql
CREATE OR REPLACE FUNCTION public.uuid_generate_v7()
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
declare
  unix_ts_ms bytea;
  uuid_bytes bytea;
begin
  unix_ts_ms = substring(int8send(floor(extract(epoch from clock_timestamp()) * 1000)::bigint) from 3);

  -- use random v4 uuid as starting point (which has the same variant we need)
  uuid_bytes = uuid_send(gen_random_uuid());

  -- overlay timestamp
  uuid_bytes = overlay(uuid_bytes placing unix_ts_ms from 1 for 6);

  -- set version 7
  uuid_bytes = set_byte(uuid_bytes, 6, (b'0111' || get_byte(uuid_bytes, 6)::bit(4))::bit(8)::int);

  return encode(uuid_bytes, 'hex')::uuid;
end
$function$
;
```

Granted, a native extension might be faster, but I strongly doubt that UUID generation is a bottle neck for any Postgres.app users.

So for these reasons, I think we should not include this extension with Postgres.app.

**Comment by gvkhna** [comment]
Perfect, agreed, thank you!
