### ISSUE TITLE
Database stop showing up upon default user database deletion

### ISSUE THREAD

**Issue by confusedGustas** [PostgresApp/PostgresApp#732]
After deleting the default <user> database base, which in my case is gustas, every other database stop showing in the Postgres.app. I am still able to create new database, running \l shows the new databases with the template databases.

Thanks in advance.

**Comment by jakob** [comment]
Postgres.app just uses the default parameters to connect to the local PostgreSQL server. This means it uses the local user name and tries to connect to a database with the same name, without a password.

If this user or database does not exist, or requires a password, then Postgres.app can not connect, and can not show the list of databases. The server still works, though.

**Comment by confusedGustas** [comment]
Gotcha! just created a database under the same username and all of the database are showing. Thanks for the information!
