### ISSUE TITLE
Why is the old version still shown even if it is removed?

### ISSUE THREAD

**Issue by ChenZhongPu** [PostgresApp/PostgresApp#733]
I have upgraded from PostgresApp 2.5.12 (PG 14) to PostgresApp 2.6.7 (PG 16), but why is PG 14 still shown in the menu? Of course, PG 14 is removed so it cannot be started.

<img width="218" alt="image" src="https://github.com/PostgresApp/PostgresApp/assets/2310958/32c8b838-389d-48af-aad9-83c13407ed8b">

**Comment by jakob** [comment]
You can use multiple versions of PostgreSQL at the same time.

Postgres.app does not automatically upgrade your existing data directories. It just leaves the old directory in place.

If you want to upgrade or delete it, you have to do that manually.

**Comment by ChenZhongPu** [comment]
> If you want to upgrade or delete it, you have to do that manually.

Yes, I upgraded it manually and the old files have been removed. Now, inside `~/Library/Application Support/Postgres`, there is only one folder `var-16`. Is there any other old data directories?
