### ISSUE TITLE
Instructions to put psql on the PATH don't work, missing `latest` directory

### ISSUE THREAD

**Issue by schneems** [PostgresApp/PostgresApp#735]
Hello. At RubyConf a workshop used postgres and quite a few people used postgres.app (yay!) unfortunately though this command listed in the documentation no longer works:

```
sudo mkdir -p /etc/paths.d &&
echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp
```

The directory ` /Applications/Postgres.app/Contents/Versions/latest` did not exist, and instead was ` /Applications/Postgres.app/Contents/Versions/15` (the only directory inside of the `Versions` folder).

The other problem we ran into is that running that non-working command doesn't give any feedback, it doesn't error or indicate that it didn't work.

There could be a whole host of things that could prevent it from being executable (https://github.com/schneems/which_problem attempts to diagnose path lookup issues). In an ideal world we would maybe ship something like that command and do a full diagnostic output. In a less-than-ideal world we could provide a checksum command to run for the most common failures.

For example adding a check to make sure that the directory exists and was set correctly:

```
if test -d $(cat /etc/paths.d/postgresapp) 
then
  echo "Directory set correctly try running \`which psql\` now"
else
  echo "Operation failed $(cat /etc/paths.d/postgresapp) is not a valid directory"
fi
```

**Comment by tbussmann** [comment]
Thanks for the heads up! I checked the issue you had and found that some of the current builds seem to contain an error, so it's not the instructions that are outdated ;)

The builds containing PostgreSQL 12, 13, 14 and 15 (single version) are missing the symlink, whereas 11, 16 and the all-versions bundle are correct.

On the followup idea of giving an error: we could include a shell script that takes care of setting up the path which would give a better output and could be easier to call. This script also could take care of using a dynamic path in case Postgres.app is not in `/Applications`.

**Comment by jakob** [comment]
Ahhhh... looks like I made a mistake when building the latest releases. Sorry! Thanks for diagnosing the issue so quickly.

I reverted the download links for the broken builds now. I'll make new builds later tonight.

**Comment by schneems** [comment]
Thanks for the fast response!

**Comment by jakob** [comment]
I just released Postgres.app 2.6.8a (only the builds with PostgreSQL 12-15). If you update to the latest version, the "latest" symlink should be back again!
