### ISSUE TITLE
Not seeing template0 in the GUI

### ISSUE THREAD

**Issue by fxn** [PostgresApp/PostgresApp#736]
I just created a new v16 server, hit "Initialize", and there is no `template0`:

![CleanShot 2023-11-16 at 10 13 54@2x](https://github.com/PostgresApp/PostgresApp/assets/3387/32b292a2-45b0-49de-9ad5-0716ca666c12)

Is that expected? The template seems to be there just fine:

```
% which psql
/Applications/Postgres.app/Contents/Versions/latest/bin/psql

% psql --version
psql (PostgreSQL) 16.1

% psql
fxn=# select datname from pg_database;
  datname
-----------
 postgres
 fxn
 template1
 template0
(4 rows)
```

(This is an up to date version 2.6.8 of Postgres.app.)

**Comment by tbussmann** [comment]
yes, this is expected as you cannot connect to `template0`. (See: `SELECT datname, datallowconn FROM pg_database;`) The databases listed in the UI allow establishing a quick connection by double clicking their icons. You can chose the client used for this connection in the settings.

**Comment by fxn** [comment]
Awesome, thank you!
