### ISSUE TITLE
pgAdmin 4 detects prior PostgreSQL which no longer exists

### ISSUE THREAD

**Issue by morningseal** [PostgresApp/PostgresApp#748]
MacOS 14.2.1 + pgAdmin4 8.2 shows DB server that no longer exists.

Hover over server & property comments indicate 'Auto-detected PostgreSQL 9.6 installation with the data directory at /Library/PostgreSQL/9.6/data'.

The directory does not exist.

Remove server temporarily deletes it, close & open pgAdmin4 brings it back to life.

**Comment by jakob** [comment]
Can you report this issue to the pgAdmin project? You can find their issue tracker here: https://github.com/pgadmin-org/pgadmin4/issues

**Comment by morningseal** [comment]
Yikes, will do. Thanks.
