### ISSUE TITLE
Disabling Permission Dialog is not respected by MenuHelper / Autostart

### ISSUE THREAD

**Issue by tbussmann** [PostgresApp/PostgresApp#752]
If you disable "Ask for permission when apps connect without password" in the preferences, this is only respected if the servers are started from the main app. If you start the server via the MenuHelper or if the server is auto-started on login (LoginHelper), the setting is not respected and the extension is loaded nevertheless.

A quick way to check the start parameters is `pg_ctl -D ~/Library/Application\ Support/Postgres/var-xxx status`.

I don't yet understand why this is the case as https://github.com/PostgresApp/PostgresApp/blob/master/Postgres/Server.swift#L554 looks good to me. However, the Key `PermissionDialogForTrustAuth` is not toggled between `0` and `1` if the checkbox is clicked in the preferences but between `0` and being removed (check with `defaults read com.postgresapp.Postgres2 PermissionDialogForTrustAuth`). I currently don't understand how this is connected.

**Comment by urkle** [comment]
I am also experiencing this issue.  @tbussmann what version of the PostgresApp are you using? I just upgraded today to 2.7.1 as the previous version kept asking over and over (causing havoc with my development) even though I had the setting off.  Right now the current version *appears* to be behaving.  But I have not yet restarted my computer again to see if it will continue to behave.

**Comment by jakob** [comment]
> I don't yet understand why this is the case as https://github.com/PostgresApp/PostgresApp/blob/master/Postgres/Server.swift#L554 looks good to me.

Good catch! I think the problem is that it checks the user defaults of the helper app instead of checking the defaults of the main app.

> the Key PermissionDialogForTrustAuth is not toggled between 0 and 1 if the checkbox is clicked in the preferences but between 0 and being removed

I think this is because the default value is set to 1 in register defaults. If that call is missing in the helper, that could also be the problem.

**Comment by tbussmann** [comment]
> Good catch! I think the problem is that it checks the user defaults of the helper app instead of checking the defaults of the main app.
I can confirm your assumption, `defaults write com.postgresapp.Postgres2MenuHelper PermissionDialogForTrustAuth 0` does disable the feature for the MenuHelper and Autostart.

**Comment by jakob** [comment]
@tbussmann Are you going to build a new release with this fix or should I? I think this is a pretty critical fix that we should probably release soon.

**Comment by tbussmann** [comment]
This should be fixed in the [v2.7.2 release](https://github.com/PostgresApp/PostgresApp/releases/tag/v2.7.2).
