### ISSUE TITLE
gives wrong fatal error message

### ISSUE THREAD

**Issue by martinmueller39** [PostgresApp/PostgresApp#758]
I recently update my version of Postgres.  I' not reall familiar with it, but it has always worked.  I use Aqua Data studio to connecto to the database.   I use a Mac with Sonoma.  On two occasions, when trying to open the database from AquaData Studio I got a fatal error message.  When I turned off the Mac and turned it on again this did not haappen. 

I don't really know what is going on, but it has something to do with authentication. I have always used the default setting, which I think you call 'trust', and it has never failed.  But it appears that with the most recent version it gets confused. When I log off the computer at night, log in the next morning, and try to get to Postgres via ADS I get that error message

**Comment by jakob** [comment]
This is probably because of the new permission dialog we added in Postgres.app 2.7.

First of all, please make sure you are on the latest version of Postgres.app (currently 2.7.2)

Next, please open Postgres.app, go to settings, and check if Aqua Data Studio appears in the list of clients?

**Comment by martinmueller39** [comment]
Thank you for your very prompt and clear response to my question!


Martin Mueller
Professor emeritus of English and Classics
Northwestern University


From: Jakob Egger ***@***.***>
Date: Thursday, April 4, 2024 at 9:34 AM
To: PostgresApp/PostgresApp ***@***.***>
Cc: Martin Mueller ***@***.***>, Author ***@***.***>
Subject: Re: [PostgresApp/PostgresApp] gives wrong fatal error message (Issue #758)

This is probably because of the new permission dialog we added in Postgres.app 2.7.

First of all, please make sure you are on the latest version of Postgres.app (currently 2.7.2)

Next, please open Postgres.app, go to settings, and check if Aqua Data Studio appears in the list of clients?

**Comment by martinmueller39** [comment]
It seems to be working well. Thank you for your concern!

I cana’t remember whether I pushed some button or whether the app figured it out by itself. But I haven’t had any problems.

From: Jakob Egger ***@***.***>
Date: Friday, April 12, 2024 at 3:04 AM
To: PostgresApp/PostgresApp ***@***.***>
Cc: Martin Mueller ***@***.***>, Author ***@***.***>
Subject: Re: [PostgresApp/PostgresApp] gives wrong fatal error message (Issue #758)

Are you still experiencing issues with Postgres.app and Aqua Data Studio?

Please let us know if you have been able to resolve the problem, or if you want us to further investigate the issue.

**Comment by martinmueller39** [comment]
I have a very stupid question for you.  I can’t find the datafiles for my Postgres database. Which I think was installed with your app.

I am thinking of adding the data files to my Dropbox account, which means that in addition to being backed up on a separate drive via Time Machine they would also be retrievable if the drive crashed.

I assume that is a safe procedure, but I am still confused a little about how to do this. Right now,  all my data are automatically backed up to /users/martinmueller/Dropbox, but all data stay on my machine. It isn’t clear to me whether or how I could add the various Postgress data files to that set up.

With thanks in advance for any help


Martin Mueller
Professor emeritus of English and Classics
Northwestern University


From: Jakob Egger ***@***.***>
Date: Friday, April 19, 2024 at 1:58 AM
To: PostgresApp/PostgresApp ***@***.***>
Cc: Martin Mueller ***@***.***>, Author ***@***.***>
Subject: Re: [PostgresApp/PostgresApp] gives wrong fatal error message (Issue #758)

Closed #758<https://urldefense.com/v3/__https:/github.com/PostgresApp/PostgresApp/issues/758__;!!Dq0X2DkFhyF93HkjWTBQKhk!XSoX4qNsSti3VLsCVJkqJTirNnarS6ok1PrM5QhmLh6hRHAxvFxCQFWaTQ6_AvXpL70ZgobesluCzW87_ofTUo8MSU0BQFS2PQ$> as completed.

**Comment by jakob** [comment]
> I can’t find the datafiles for my Postgres database.

The easiest way to find the data directory is to run the following query:

```sql
show data_directory;
```

> I am thinking of adding the data files to my Dropbox account, which means that in addition to being backed up on a separate drive via Time Machine they would also be retrievable if the drive crashed. I assume that is a safe procedure (...)

No! Do not put your data directory in Dropbox! There is a very high chance that this will corrupt your database. PostgreSQL doesn't like it when other apps manipulate its data directory, because then the different files will go out of sync.

Using TimeMachine on APFS to back up a PostgreSQL data directory is probably okay, because it uses file system snapshots. However, we haven't tested it. (If you do use time machine, make sure to always restore the full data directory, and do so only while the server is shut down.)

**Comment by martinmueller39** [comment]
Many thanks for this excellent advice

From: Jakob Egger ***@***.***>
Date: Monday, May 27, 2024 at 10:26 AM
To: PostgresApp/PostgresApp ***@***.***>
Cc: Martin Mueller ***@***.***>, Author ***@***.***>
Subject: Re: [PostgresApp/PostgresApp] gives wrong fatal error message (Issue #758)

I can’t find the datafiles for my Postgres database.

The easiest way to find the data directory is to run the following query:

show data_directory;

I am thinking of adding the data files to my Dropbox account, which means that in addition to being backed up on a separate drive via Time Machine they would also be retrievable if the drive crashed. I assume that is a safe procedure (...)

No! Do not put your data directory in Dropbox! There is a very high chance that this will corrupt your database. PostgreSQL doesn't like it when other apps manipulate its data directory, because then the different files will go out of sync.

Using TimeMachine on APFS to back up a PostgreSQL data directory is probably okay, because it uses file system snapshots. However, we haven't tested it. (If you do use time machine, make sure to always restore the full data directory, and do so only while the server is shut down.)
