### ISSUE TITLE
The auth_permission_dialog extension wasn't found.

### ISSUE THREAD

**Issue by robslotboom** [PostgresApp/PostgresApp#759]
Because I need a 9.6 version of Postgres I past this version in versions.
When I start this server I got the message “The auth_permission_dialog extension wasn't found".
Postgres app version 2.7.2

**Comment by robslotboom** [comment]
Hey Tobias, Yes, the server starts.
Thanks,

**Comment by tbussmann** [comment]
thanks for the feedback! I'm glad that this has helped.
