### ISSUE TITLE
What's the best way to grab the binaries to embed in, say, an Electron app?

### ISSUE THREAD

**Issue by mhkeller** [PostgresApp/PostgresApp#760]
I'm exploring bundling Postgres with an Electron app to save users the (in my view, minimal, but alas) step of downloading a separate app and initializing their instance. I'm wondering what the easiest way of doing that is. (Currently just looking at macOS support).

I did a very naive first attempt at grabbing the `shp2pgsql` binary and putting it in my app directory but there were missing dependencies when I tried to execute it. Could be I just need to grab more files. I also want to be able to pass in a custom, unused port when I boot up the embedded instance so as not to conflict with other services running.

If you have any pointers, let me know!

**Comment by jakob** [comment]
You can use `otool -L` to check what dynamic libraries a binary is linked with, so you know which libraries to include as well. However, some of the GIS libraries and PostgreSQL itself also depends on data files, and I don't know of an easy way to figure out the minimum number of files you need to copy.

If file size is of no concern, then the easiest way is to just copy the full directory from the "Versions" folder, eg. `/Applications/Postgres.app/Contents/Versions/16`. These directories are self-contained and include everything needed to run PostgreSQL. We made sure the dynamic libraries are all loaded with relative paths, so everything should work even if you move it to a different path.

If you include these directories in your app package, you probably need to re-sign them to avoid Gatekeeper warnings. The [build.sh](https://github.com/PostgresApp/PostgresApp/blob/master/buildscripts/build.sh) script code signs the PostgreSQL binaries, you can probably use the same script with some small modifications.

**Comment by mhkeller** [comment]
Thanks @jakob! I'll give this a try and poke around with how to get it initialized and running.
