### ISSUE TITLE
Unable to install postgre in mac

### ISSUE THREAD

**Issue by prasadnori** [PostgresApp/PostgresApp#774]
Below error:

Problem running post-install step. Installation may not complete correctly

The database cluster initialisation failed.

**Comment by jakob** [comment]
Hi! It sounds like you are using something other than Postgres.app. This Github project is about the app distributed on https://postgresapp.com 

How are you trying to install PostgreSQL? Did you download the EnterpriseDB installer, or are you using Homebrew, or MacPorts?

**Comment by prasadnori** [comment]
Installation got resolved.

Now i am facing new issue while trying to install a new data base server.

Attaching the screenshot

**Comment by jakob** [comment]
You are not answering questions, so I am closing this issue.

**Comment by prasadnori** [comment]
I dont understand

I just answered.

whats the problem?

Provide guidance to new comers instead of being rude

**Comment by prasadnori** [comment]
@jakob I am not too technical as you are

**Comment by prasadnori** [comment]
> Hi! It sounds like you are using something other than Postgres.app. This Github project is about the app distributed on https://postgresapp.com
> 
> How are you trying to install PostgreSQL? Did you download the EnterpriseDB installer, or are you using Homebrew, or MacPorts?

Yes I believe I have used installer..
