### ISSUE TITLE
Upgraded to 2.7.8 but cannot create v17 server

### ISSUE THREAD

**Issue by razvanioan** [PostgresApp/PostgresApp#780]
I am running Postgres 16 on an older version of the app on Mac with Apple Silicon chip
Today I've updated it to the latest version 2.7.8 to install also the new version 17 but apparently I cannot do that.

Am I missing something ? On the download page it states that this version supports Postgres 17.
What is the correct way to upgrade the app, keep old server(s) and databases + add the new version of Postgres ?

<img width="441" alt="image" src="https://github.com/user-attachments/assets/ff19067f-30b8-4649-b873-44c94b09fb03">

<img width="600" alt="image" src="https://github.com/user-attachments/assets/3f1f3993-a521-4e48-9de0-cf4a622ba3db">

**Comment by tbussmann** [comment]
It seems that you are running the single version bundle of Postgres.app with PostgreSQL 16. To access PostgreSQL 17 in addition, the easiest way is to download the bundle called "Postgres.app with all currently supported versions" under "Additional Releases" on the [Downloads Page](https://postgresapp.com/downloads.html) and replace your existing application with it.

**Comment by razvanioan** [comment]
Indeed that was the case
Thx
