### ISSUE TITLE
DYLIB troubles - Library not loaded: /usr/lib/libpq.5.dylib (LoadError)

### ISSUE THREAD

**Issue by swanson** [PostgresApp/PostgresApp#83]
Ruby 1.9.3
Rails 3.2.2
Postgres.app 1.0
OS X Mountain Lion 10.8.2

Purged system of other postgres installs (was using homebrew)

Bundler wasn't working until I ran

`gem install pg -- --with-pg-lib=/Applications/Postgres.app/Contents/MacOS/lib`

Then trying to start `rails s` gives this error:

``````
/Users/matt/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:251:in 
`require': dlopen(/Users/matt/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/pg-0.13.2/lib/pg_ext.bundle, 9): Library not 
    loaded: /usr/lib/libpq.5.dylib (LoadError)
      Referenced from: /Users/matt/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/pg-0.13.2/lib/pg_ext.bundle
      Reason: image not found - /Users/matt/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/pg-0.13.2/lib/pg_ext.bundle
        from /Users/matt/.rbenv/versions/1.9.3-p125/lib/ruby/gems/1.9.1/gems/activesupport-3.2.2/lib/active_support/dependencies.r```
``````

Then running:

```
> otool -L `which psql`
   /Applications/Postgres.app/Contents/MacOS/bin/psql:
    @executable_path/../lib/libpq.5.dylib (compatibility version 5.0.0, current version 5.4.0)
    /usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 47.0.0)
    @executable_path/../lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0) 
```

Current work around was to add

`export DYLD_LIBRARY_PATH='/Applications/Postgres.app/Contents/MacOS/lib'`

 to my `~/.zshrc` and that seems to make it work, but seems hacky. Any guidance?

The other "options" I saw were to try use homebrew to install postgres libs, but not run the server (not ideal)

**Comment by maniempire** [comment]
Thanks @Kobes, your solution worked for me.

**Comment by hangtwenty** [comment]
I had to add the following to my shell rcfile (for sake of installing the Ruby gem `pg`):

```
export PATH="$PATH:/Applications/Postgres.app/Contents/Versions/13/bin/"  # You may need to change the version, etc
```

The error was for the dylib issue above, but having `pg_config` on the `$PATH` made the installation work.

**Comment by georgipopivanov** [comment]
After 2 days of researching, the only thing that fixes the issue is:

 ibrew install postgresql

**Comment by henriqueblobato** [comment]
`
ln -s /opt/homebrew/opt/postgresql/lib/postgresql@14/* /opt/homebrew/opt/postgresql/lib/
`

**Comment by danblade** [comment]
sudo ln -s /usr/local/Cellar/libpq/14.5/lib/libpq.5.dylib /usr/local/opt/postgresql/lib/libpq.5.dylib

**Comment by Gerst20051** [comment]
`[$]> sudo ln -s /usr/local/opt/postgresql/lib/postgresql@14/libpq.5.dylib /usr/local/opt/postgresql/lib/libpq.5.dylib`
