### ISSUE TITLE
Could not open relation mapping file "global/pg_filenode.map"

### ISSUE THREAD

**Issue by adamfairhead** [PostgresApp/PostgresApp#96]
Upon firing up postgres.app I get the following terminal message:

```
$ /Applications/Postgres.app/Contents/MacOS/bin/psql ; exit;
psql: FATAL:  could not open relation mapping file "global/pg_filenode.map": No such file or directory
logout
[Process completed]
```

Any ideas on how I might sort that out?

**Comment by Cyruxx** [comment]
@nilbus Thank you so much! +1

**Comment by jakob** [comment]
Thanks for reporting this!

Since a bunch of people seem to have stumbled across this problem, I've added this error message to the troubleshooting page:
https://postgresapp.com/documentation/troubleshooting.html
